/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.acceso;

import jafrinventarios.controladores.validaciones.ValidadorFormulario;
import jafrinventarios.vistas.utilidades.DialogoBaseConSombra;
import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author JOHN FORERO
 */
public class DialogoCambiarContrasena extends DialogoBaseConSombra {

    private final CardLayout layaoutTarjetas;
    /**
     * Creates new form DialogoCambiarContrasena
     */
    public DialogoCambiarContrasena(JFrame parent, String titulo) {
        super(parent);
        initComponents();
        
        layaoutTarjetas = (CardLayout) contenedorTarjetas.getLayout();
        tituloDialogo.setText(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorFondoBlanco = new javax.swing.JPanel();
        contenedorHeader = new javax.swing.JPanel();
        margin_left = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        tituloDialogo = new javax.swing.JLabel();
        contenedorBtnCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        contenedorTarjetas = new javax.swing.JPanel();
        contenedorCorreo = new javax.swing.JPanel();
        contenedorEscribaCorreo = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        contenedorInputYErrorCorreo = new javax.swing.JPanel();
        inputCorreo = new javax.swing.JTextField();
        lblErrorInputCorreo = new javax.swing.JLabel();
        contenedorBtnEnviarCodigo = new javax.swing.JPanel();
        btnEnviarCodigo = new javax.swing.JButton();
        contenedorConfirmarCodigo = new javax.swing.JPanel();
        contenedorEscribaCodigo = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        contenedorInputYErrorConfirmarCodigo = new javax.swing.JPanel();
        inputConfirmarCodigo = new javax.swing.JTextField();
        lblErrorInputConfirmarCodigo = new javax.swing.JLabel();
        contenedorBtnConfirmarCodigo = new javax.swing.JPanel();
        btnConfirmarCodigo = new javax.swing.JButton();
        contenedorContrasenaAntigua = new javax.swing.JPanel();
        contenedorEscribaContrasenaAntigua = new javax.swing.JPanel();
        lblContrasenaAntigua = new javax.swing.JLabel();
        contenedorInputYErrorContrasenaAntigua = new javax.swing.JPanel();
        inputContrasenaAntigua = new javax.swing.JTextField();
        lblErrorInputContrasenaAntigua = new javax.swing.JLabel();
        contenedorBtnConfirmarContrasenaAntigua = new javax.swing.JPanel();
        btnConfirmarContrasenaAntigua = new javax.swing.JButton();
        contenedorContrasenaNueva = new javax.swing.JPanel();
        contenedorEscribaContrasenaNueva = new javax.swing.JPanel();
        lblContrasenaNueva = new javax.swing.JLabel();
        contenedorInputContrasenaNueva = new javax.swing.JPanel();
        inputContrasenaNueva = new javax.swing.JTextField();
        lblConfirmarContrasena = new javax.swing.JLabel();
        contenedorInputContrasenaNueva1 = new javax.swing.JPanel();
        inputConfirmarContrasena = new javax.swing.JTextField();
        contenedorBtnCambiarContrasena = new javax.swing.JPanel();
        btnCambiarContrasena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        setName("dialogCambiarContrasena"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 350));

        contenedorFondoBlanco.setMinimumSize(new java.awt.Dimension(500, 380));
        contenedorFondoBlanco.setPreferredSize(new java.awt.Dimension(500, 380));
        contenedorFondoBlanco.setLayout(new java.awt.BorderLayout());

        contenedorHeader.setBackground(new java.awt.Color(255, 255, 255));
        contenedorHeader.setMinimumSize(new java.awt.Dimension(0, 70));
        contenedorHeader.setPreferredSize(new java.awt.Dimension(0, 70));
        contenedorHeader.setLayout(new java.awt.BorderLayout());
        contenedorHeader.add(margin_left, java.awt.BorderLayout.WEST);

        tituloDialogo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        tituloDialogo.setForeground(new java.awt.Color(17, 35, 85));
        tituloDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDialogo.setText("Recuperar Contraseña");
        tituloDialogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tituloDialogo.setMaximumSize(new java.awt.Dimension(3000, 60));
        tituloDialogo.setMinimumSize(new java.awt.Dimension(0, 60));
        tituloDialogo.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorHeader.add(tituloDialogo, java.awt.BorderLayout.CENTER);

        contenedorBtnCerrar.setMinimumSize(new java.awt.Dimension(40, 0));
        contenedorBtnCerrar.setOpaque(false);
        contenedorBtnCerrar.setPreferredSize(new java.awt.Dimension(40, 0));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(17, 35, 85));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/carbon--close-filled.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusCycleRoot(true);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setPreferredSize(new java.awt.Dimension(30, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarcerrarDialogo(evt);
            }
        });
        contenedorBtnCerrar.add(btnCerrar);

        contenedorHeader.add(contenedorBtnCerrar, java.awt.BorderLayout.EAST);

        contenedorFondoBlanco.add(contenedorHeader, java.awt.BorderLayout.PAGE_START);

        contenedorTarjetas.setBackground(new java.awt.Color(255, 255, 255));
        contenedorTarjetas.setLayout(new java.awt.CardLayout());

        contenedorCorreo.setOpaque(false);
        contenedorCorreo.setLayout(new java.awt.BorderLayout());

        contenedorEscribaCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 40));
        contenedorEscribaCorreo.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorEscribaCorreo.setOpaque(false);
        contenedorEscribaCorreo.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorEscribaCorreo.setLayout(new java.awt.GridLayout(2, 1));

        lblCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("Escriba su correo y presione el botón enviar código. ");
        lblCorreo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        contenedorEscribaCorreo.add(lblCorreo);

        contenedorInputYErrorCorreo.setOpaque(false);
        contenedorInputYErrorCorreo.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorInputYErrorCorreo.setLayout(new java.awt.BorderLayout());

        inputCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputCorreo.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputCorreo.setMinimumSize(new java.awt.Dimension(0, 45));
        inputCorreo.setPreferredSize(new java.awt.Dimension(0, 41));
        contenedorInputYErrorCorreo.add(inputCorreo, java.awt.BorderLayout.NORTH);

        lblErrorInputCorreo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputCorreo.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputCorreo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblErrorInputCorreo.setAlignmentX(0.5F);
        lblErrorInputCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputCorreo.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorCorreo.add(lblErrorInputCorreo, java.awt.BorderLayout.CENTER);

        contenedorEscribaCorreo.add(contenedorInputYErrorCorreo);

        contenedorCorreo.add(contenedorEscribaCorreo, java.awt.BorderLayout.CENTER);

        contenedorBtnEnviarCodigo.setMinimumSize(new java.awt.Dimension(89, 100));
        contenedorBtnEnviarCodigo.setOpaque(false);
        contenedorBtnEnviarCodigo.setPreferredSize(new java.awt.Dimension(555, 100));

        btnEnviarCodigo.setBackground(new java.awt.Color(30, 166, 177));
        btnEnviarCodigo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEnviarCodigo.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarCodigo.setText("Enviar Código");
        btnEnviarCodigo.setToolTipText("");
        btnEnviarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarCodigo.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnEnviarCodigo.setMaximumSize(new java.awt.Dimension(200, 40));
        btnEnviarCodigo.setMinimumSize(new java.awt.Dimension(200, 40));
        btnEnviarCodigo.setPreferredSize(new java.awt.Dimension(200, 40));
        btnEnviarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCodigoActionPerformed(evt);
            }
        });
        contenedorBtnEnviarCodigo.add(btnEnviarCodigo);

        contenedorCorreo.add(contenedorBtnEnviarCodigo, java.awt.BorderLayout.SOUTH);

        contenedorTarjetas.add(contenedorCorreo, "cardCorreo");

        contenedorConfirmarCodigo.setOpaque(false);
        contenedorConfirmarCodigo.setLayout(new java.awt.BorderLayout());

        contenedorEscribaCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 40));
        contenedorEscribaCodigo.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorEscribaCodigo.setOpaque(false);
        contenedorEscribaCodigo.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorEscribaCodigo.setLayout(new java.awt.GridLayout(2, 1));

        lblCodigo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodigo.setText("Escriba el código que llego a su correo");
        lblCodigo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        contenedorEscribaCodigo.add(lblCodigo);

        contenedorInputYErrorConfirmarCodigo.setOpaque(false);
        contenedorInputYErrorConfirmarCodigo.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorInputYErrorConfirmarCodigo.setLayout(new java.awt.BorderLayout());

        inputConfirmarCodigo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputConfirmarCodigo.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputConfirmarCodigo.setMinimumSize(new java.awt.Dimension(0, 45));
        inputConfirmarCodigo.setPreferredSize(new java.awt.Dimension(0, 41));
        contenedorInputYErrorConfirmarCodigo.add(inputConfirmarCodigo, java.awt.BorderLayout.NORTH);

        lblErrorInputConfirmarCodigo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputConfirmarCodigo.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputConfirmarCodigo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblErrorInputConfirmarCodigo.setAlignmentX(0.5F);
        lblErrorInputConfirmarCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputConfirmarCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputConfirmarCodigo.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorConfirmarCodigo.add(lblErrorInputConfirmarCodigo, java.awt.BorderLayout.CENTER);

        contenedorEscribaCodigo.add(contenedorInputYErrorConfirmarCodigo);

        contenedorConfirmarCodigo.add(contenedorEscribaCodigo, java.awt.BorderLayout.CENTER);

        contenedorBtnConfirmarCodigo.setMinimumSize(new java.awt.Dimension(89, 100));
        contenedorBtnConfirmarCodigo.setOpaque(false);
        contenedorBtnConfirmarCodigo.setPreferredSize(new java.awt.Dimension(555, 100));

        btnConfirmarCodigo.setBackground(new java.awt.Color(30, 166, 177));
        btnConfirmarCodigo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnConfirmarCodigo.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarCodigo.setText("Confirmar Código");
        btnConfirmarCodigo.setToolTipText("");
        btnConfirmarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarCodigo.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnConfirmarCodigo.setMaximumSize(new java.awt.Dimension(200, 40));
        btnConfirmarCodigo.setMinimumSize(new java.awt.Dimension(200, 40));
        btnConfirmarCodigo.setPreferredSize(new java.awt.Dimension(200, 40));
        btnConfirmarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCodigoActionPerformed(evt);
            }
        });
        contenedorBtnConfirmarCodigo.add(btnConfirmarCodigo);

        contenedorConfirmarCodigo.add(contenedorBtnConfirmarCodigo, java.awt.BorderLayout.SOUTH);

        contenedorTarjetas.add(contenedorConfirmarCodigo, "cardConfirmarCodigo");

        contenedorContrasenaAntigua.setOpaque(false);
        contenedorContrasenaAntigua.setLayout(new java.awt.BorderLayout());

        contenedorEscribaContrasenaAntigua.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 40));
        contenedorEscribaContrasenaAntigua.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorEscribaContrasenaAntigua.setOpaque(false);
        contenedorEscribaContrasenaAntigua.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorEscribaContrasenaAntigua.setLayout(new java.awt.GridLayout(2, 1));

        lblContrasenaAntigua.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblContrasenaAntigua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContrasenaAntigua.setText("Escriba su contraseña actual");
        lblContrasenaAntigua.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblContrasenaAntigua.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        contenedorEscribaContrasenaAntigua.add(lblContrasenaAntigua);
        lblContrasenaAntigua.getAccessibleContext().setAccessibleName("Escriba su contraseña actual");

        contenedorInputYErrorContrasenaAntigua.setOpaque(false);
        contenedorInputYErrorContrasenaAntigua.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorInputYErrorContrasenaAntigua.setLayout(new java.awt.BorderLayout());

        inputContrasenaAntigua.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputContrasenaAntigua.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputContrasenaAntigua.setMinimumSize(new java.awt.Dimension(0, 45));
        inputContrasenaAntigua.setPreferredSize(new java.awt.Dimension(0, 41));
        contenedorInputYErrorContrasenaAntigua.add(inputContrasenaAntigua, java.awt.BorderLayout.NORTH);

        lblErrorInputContrasenaAntigua.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputContrasenaAntigua.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputContrasenaAntigua.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblErrorInputContrasenaAntigua.setAlignmentX(0.5F);
        lblErrorInputContrasenaAntigua.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputContrasenaAntigua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputContrasenaAntigua.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorContrasenaAntigua.add(lblErrorInputContrasenaAntigua, java.awt.BorderLayout.CENTER);

        contenedorEscribaContrasenaAntigua.add(contenedorInputYErrorContrasenaAntigua);

        contenedorContrasenaAntigua.add(contenedorEscribaContrasenaAntigua, java.awt.BorderLayout.CENTER);

        contenedorBtnConfirmarContrasenaAntigua.setMinimumSize(new java.awt.Dimension(89, 100));
        contenedorBtnConfirmarContrasenaAntigua.setOpaque(false);
        contenedorBtnConfirmarContrasenaAntigua.setPreferredSize(new java.awt.Dimension(555, 100));

        btnConfirmarContrasenaAntigua.setBackground(new java.awt.Color(30, 166, 177));
        btnConfirmarContrasenaAntigua.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnConfirmarContrasenaAntigua.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarContrasenaAntigua.setText("Confirmar");
        btnConfirmarContrasenaAntigua.setToolTipText("");
        btnConfirmarContrasenaAntigua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarContrasenaAntigua.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnConfirmarContrasenaAntigua.setMaximumSize(new java.awt.Dimension(200, 40));
        btnConfirmarContrasenaAntigua.setMinimumSize(new java.awt.Dimension(200, 40));
        btnConfirmarContrasenaAntigua.setPreferredSize(new java.awt.Dimension(200, 40));
        btnConfirmarContrasenaAntigua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarContrasenaAntiguaActionPerformed(evt);
            }
        });
        contenedorBtnConfirmarContrasenaAntigua.add(btnConfirmarContrasenaAntigua);

        contenedorContrasenaAntigua.add(contenedorBtnConfirmarContrasenaAntigua, java.awt.BorderLayout.SOUTH);

        contenedorTarjetas.add(contenedorContrasenaAntigua, "cardContrasenaAntigua");

        contenedorContrasenaNueva.setOpaque(false);
        contenedorContrasenaNueva.setLayout(new java.awt.BorderLayout());

        contenedorEscribaContrasenaNueva.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        contenedorEscribaContrasenaNueva.setOpaque(false);
        contenedorEscribaContrasenaNueva.setLayout(new java.awt.GridLayout(4, 1));

        lblContrasenaNueva.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblContrasenaNueva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContrasenaNueva.setText("Contraseña nueva:");
        lblContrasenaNueva.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 0));
        contenedorEscribaContrasenaNueva.add(lblContrasenaNueva);

        contenedorInputContrasenaNueva.setOpaque(false);

        inputContrasenaNueva.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputContrasenaNueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputContrasenaNueva.setMinimumSize(new java.awt.Dimension(300, 35));
        inputContrasenaNueva.setPreferredSize(new java.awt.Dimension(300, 35));
        contenedorInputContrasenaNueva.add(inputContrasenaNueva);

        contenedorEscribaContrasenaNueva.add(contenedorInputContrasenaNueva);

        lblConfirmarContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblConfirmarContrasena.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblConfirmarContrasena.setText("Confirmar Contraseña nueva:");
        lblConfirmarContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 0));
        contenedorEscribaContrasenaNueva.add(lblConfirmarContrasena);

        contenedorInputContrasenaNueva1.setOpaque(false);

        inputConfirmarContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputConfirmarContrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputConfirmarContrasena.setMinimumSize(new java.awt.Dimension(300, 35));
        inputConfirmarContrasena.setPreferredSize(new java.awt.Dimension(300, 35));
        contenedorInputContrasenaNueva1.add(inputConfirmarContrasena);

        contenedorEscribaContrasenaNueva.add(contenedorInputContrasenaNueva1);

        contenedorContrasenaNueva.add(contenedorEscribaContrasenaNueva, java.awt.BorderLayout.CENTER);

        contenedorBtnCambiarContrasena.setMinimumSize(new java.awt.Dimension(89, 100));
        contenedorBtnCambiarContrasena.setOpaque(false);
        contenedorBtnCambiarContrasena.setPreferredSize(new java.awt.Dimension(555, 100));

        btnCambiarContrasena.setBackground(new java.awt.Color(30, 166, 177));
        btnCambiarContrasena.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnCambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarContrasena.setText("Cambiar contraseña");
        btnCambiarContrasena.setToolTipText("");
        btnCambiarContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarContrasena.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnCambiarContrasena.setMaximumSize(new java.awt.Dimension(220, 40));
        btnCambiarContrasena.setMinimumSize(new java.awt.Dimension(220, 40));
        btnCambiarContrasena.setPreferredSize(new java.awt.Dimension(220, 40));
        btnCambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContrasenaActionPerformed(evt);
            }
        });
        contenedorBtnCambiarContrasena.add(btnCambiarContrasena);

        contenedorContrasenaNueva.add(contenedorBtnCambiarContrasena, java.awt.BorderLayout.SOUTH);

        contenedorTarjetas.add(contenedorContrasenaNueva, "cardContrasenaNueva");

        contenedorFondoBlanco.add(contenedorTarjetas, java.awt.BorderLayout.CENTER);

        getContentPane().add(contenedorFondoBlanco, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarcerrarDialogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarcerrarDialogo
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarcerrarDialogo

    private void btnEnviarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCodigoActionPerformed
        // Este boton antes de continuar valida si el correo existe en la base de datos
        mostrarTarjeta("cardConfirmarCodigo");
    }//GEN-LAST:event_btnEnviarCodigoActionPerformed

    private void btnCambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContrasenaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCambiarContrasenaActionPerformed

    private void btnConfirmarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCodigoActionPerformed
        // TODO add your handling code here:
        mostrarTarjeta("cardContrasenaNueva");
    }//GEN-LAST:event_btnConfirmarCodigoActionPerformed

    private void btnConfirmarContrasenaAntiguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarContrasenaAntiguaActionPerformed
        // TODO add your handling code here:
        mostrarTarjeta("cardContrasenaNueva");
    }//GEN-LAST:event_btnConfirmarContrasenaAntiguaActionPerformed

    
    private void mostrarTarjeta(String nombreTarjeta){
        layaoutTarjetas.show(contenedorTarjetas, nombreTarjeta);
    }
    
    
    
    public static void recuperarContrasena(JFrame padreFrame){
        DialogoCambiarContrasena dialogoRecuperarContrasena = 
                new DialogoCambiarContrasena( padreFrame, "Recuperar contraseña");
        
        dialogoRecuperarContrasena.mostrarTarjeta("cardCorreo");
        
        dialogoRecuperarContrasena.hacerVisibleDialogo();
    }
    
    
    
    public static void cambiarContrasena(JFrame padreFrame){
        DialogoCambiarContrasena dialogoCambiarContrasena = 
                new DialogoCambiarContrasena( padreFrame, "Cambiar contraseña");
        
        dialogoCambiarContrasena.mostrarTarjeta("cardContrasenaAntigua");
        
        dialogoCambiarContrasena.hacerVisibleDialogo();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarContrasena;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConfirmarCodigo;
    private javax.swing.JButton btnConfirmarContrasenaAntigua;
    private javax.swing.JButton btnEnviarCodigo;
    private javax.swing.JPanel contenedorBtnCambiarContrasena;
    private javax.swing.JPanel contenedorBtnCerrar;
    private javax.swing.JPanel contenedorBtnConfirmarCodigo;
    private javax.swing.JPanel contenedorBtnConfirmarContrasenaAntigua;
    private javax.swing.JPanel contenedorBtnEnviarCodigo;
    private javax.swing.JPanel contenedorConfirmarCodigo;
    private javax.swing.JPanel contenedorContrasenaAntigua;
    private javax.swing.JPanel contenedorContrasenaNueva;
    private javax.swing.JPanel contenedorCorreo;
    private javax.swing.JPanel contenedorEscribaCodigo;
    private javax.swing.JPanel contenedorEscribaContrasenaAntigua;
    private javax.swing.JPanel contenedorEscribaContrasenaNueva;
    private javax.swing.JPanel contenedorEscribaCorreo;
    private javax.swing.JPanel contenedorFondoBlanco;
    private javax.swing.JPanel contenedorHeader;
    private javax.swing.JPanel contenedorInputContrasenaNueva;
    private javax.swing.JPanel contenedorInputContrasenaNueva1;
    private javax.swing.JPanel contenedorInputYErrorConfirmarCodigo;
    private javax.swing.JPanel contenedorInputYErrorContrasenaAntigua;
    private javax.swing.JPanel contenedorInputYErrorCorreo;
    private javax.swing.JPanel contenedorTarjetas;
    private javax.swing.JTextField inputConfirmarCodigo;
    private javax.swing.JTextField inputConfirmarContrasena;
    private javax.swing.JTextField inputContrasenaAntigua;
    private javax.swing.JTextField inputContrasenaNueva;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblConfirmarContrasena;
    private javax.swing.JLabel lblContrasenaAntigua;
    private javax.swing.JLabel lblContrasenaNueva;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblErrorInputConfirmarCodigo;
    private javax.swing.JLabel lblErrorInputContrasenaAntigua;
    private javax.swing.JLabel lblErrorInputCorreo;
    private javax.swing.Box.Filler margin_left;
    private javax.swing.JLabel tituloDialogo;
    // End of variables declaration//GEN-END:variables
}
