/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.acceso;

import jafrinventarios.vistas.utilidades.DinamismoLink;

/**
 *
 * @author JOHN FORERO
 */
public class InicioSesionPanel extends javax.swing.JPanel {

    /**
     * Creates new form InicioSesionPanel
     */
    public InicioSesionPanel() {
        initComponents();
        
        DinamismoLink.aplicarEfecto(btnLinkRecuperarContraseña);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorTituloFormulario = new javax.swing.JPanel();
        tituloFormulario = new javax.swing.JLabel();
        contenedorCuerpoFormulario = new javax.swing.JPanel();
        labelCorreo = new javax.swing.JLabel();
        inputCorreo = new javax.swing.JTextField();
        labelContrasena = new javax.swing.JLabel();
        inputContrasena = new javax.swing.JTextField();
        contenedorRecuperarContrasena = new javax.swing.JPanel();
        btnLinkRecuperarContraseña = new javax.swing.JButton();
        contenedorBotonEnviarFormulario = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 205, 205));
        setMaximumSize(new java.awt.Dimension(32767, 400));
        setMinimumSize(new java.awt.Dimension(380, 400));
        setPreferredSize(new java.awt.Dimension(380, 400));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        contenedorTituloFormulario.setMaximumSize(new java.awt.Dimension(2147483647, 70));
        contenedorTituloFormulario.setMinimumSize(new java.awt.Dimension(500, 70));
        contenedorTituloFormulario.setOpaque(false);
        contenedorTituloFormulario.setPreferredSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setLayout(new java.awt.BorderLayout());

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(17, 35, 85));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Iniciar sesión");
        tituloFormulario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tituloFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setMaximumSize(new java.awt.Dimension(170, 30));
        tituloFormulario.setMinimumSize(new java.awt.Dimension(170, 30));
        tituloFormulario.setPreferredSize(new java.awt.Dimension(170, 30));
        contenedorTituloFormulario.add(tituloFormulario, java.awt.BorderLayout.CENTER);

        add(contenedorTituloFormulario);

        contenedorCuerpoFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 40));
        contenedorCuerpoFormulario.setMinimumSize(new java.awt.Dimension(80, 180));
        contenedorCuerpoFormulario.setOpaque(false);
        contenedorCuerpoFormulario.setPreferredSize(new java.awt.Dimension(400, 180));
        contenedorCuerpoFormulario.setRequestFocusEnabled(false);
        contenedorCuerpoFormulario.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        labelCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCorreo.setText("Correo:");
        labelCorreo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelCorreo.setMaximumSize(new java.awt.Dimension(0, 0));
        labelCorreo.setMinimumSize(new java.awt.Dimension(0, 0));
        labelCorreo.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorCuerpoFormulario.add(labelCorreo);

        inputCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputCorreo.setMargin(new java.awt.Insets(2, 15, 2, 15));
        inputCorreo.setMaximumSize(new java.awt.Dimension(0, 0));
        inputCorreo.setMinimumSize(new java.awt.Dimension(0, 0));
        inputCorreo.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorCuerpoFormulario.add(inputCorreo);

        labelContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelContrasena.setText("Contraseña:");
        labelContrasena.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelContrasena.setMaximumSize(new java.awt.Dimension(0, 0));
        labelContrasena.setMinimumSize(new java.awt.Dimension(0, 0));
        labelContrasena.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorCuerpoFormulario.add(labelContrasena);

        inputContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputContrasena.setMargin(new java.awt.Insets(2, 15, 2, 15));
        inputContrasena.setMaximumSize(new java.awt.Dimension(0, 0));
        inputContrasena.setMinimumSize(new java.awt.Dimension(0, 0));
        inputContrasena.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorCuerpoFormulario.add(inputContrasena);

        add(contenedorCuerpoFormulario);

        contenedorRecuperarContrasena.setMinimumSize(new java.awt.Dimension(500, 30));
        contenedorRecuperarContrasena.setOpaque(false);
        contenedorRecuperarContrasena.setPreferredSize(new java.awt.Dimension(500, 30));
        contenedorRecuperarContrasena.setRequestFocusEnabled(false);

        btnLinkRecuperarContraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLinkRecuperarContraseña.setForeground(new java.awt.Color(30, 166, 177));
        btnLinkRecuperarContraseña.setText("Recuperar Contraseña");
        contenedorRecuperarContrasena.add(btnLinkRecuperarContraseña);

        add(contenedorRecuperarContrasena);

        contenedorBotonEnviarFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        contenedorBotonEnviarFormulario.setOpaque(false);
        contenedorBotonEnviarFormulario.setPreferredSize(new java.awt.Dimension(500, 90));

        btnIngresar.setBackground(new java.awt.Color(30, 166, 177));
        btnIngresar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setToolTipText("");
        btnIngresar.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnIngresar.setMaximumSize(new java.awt.Dimension(200, 40));
        btnIngresar.setMinimumSize(new java.awt.Dimension(200, 40));
        btnIngresar.setPreferredSize(new java.awt.Dimension(200, 40));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        contenedorBotonEnviarFormulario.add(btnIngresar);

        add(contenedorBotonEnviarFormulario);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLinkRecuperarContraseña;
    private javax.swing.JPanel contenedorBotonEnviarFormulario;
    private javax.swing.JPanel contenedorCuerpoFormulario;
    private javax.swing.JPanel contenedorRecuperarContrasena;
    private javax.swing.JPanel contenedorTituloFormulario;
    private javax.swing.JTextField inputContrasena;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
