/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.acceso;

import jafrinventarios.vistas.utilidades.formularios.TipoDatoFormulario;
import jafrinventarios.vistas.utilidades.formularios.GestorFormulario;
import jafrinventarios.vistas.utilidades.componentes.DinamismoLink;
import jafrinventarios.vistas.utilidades.componentes.MostrarOcultarContrasena;
import java.util.HashMap;

/**
 *
 * @author JOHN FORERO
 */
public class InicioSesionPanel extends javax.swing.JPanel {

    private final GestorFormulario formularioIngreso ;
    /**
     * Creates new form InicioSesionPanel
     */
    public InicioSesionPanel() {
        this.formularioIngreso = new GestorFormulario();
        initComponents();
        
        DinamismoLink.aplicarEfecto(btnLinkRecuperarContraseña);
        MostrarOcultarContrasena.agregarFuncionalidad(inputContrasena, btnMostrarOcultarContrasena);
        
        // Agregar campos al validador
        formularioIngreso.agregarCampo(
                                            inputCorreo, 
                                            lblErrorInputCorreo, 
                                            TipoDatoFormulario.CORREO, 
                                            true);
        formularioIngreso.agregarCampo(
                                            inputContrasena, 
                                            lblErrorInputContrasena, 
                                            TipoDatoFormulario.REQUERIDO, 
                                            true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorTituloFormulario = new javax.swing.JPanel();
        tituloFormulario = new javax.swing.JLabel();
        contenedorCuerpoFormulario = new javax.swing.JPanel();
        labelCorreo = new javax.swing.JLabel();
        contenedorInputYErrorCorreo = new javax.swing.JPanel();
        inputCorreo = new javax.swing.JTextField();
        lblErrorInputCorreo = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        contenedorInputYErrorContrasena = new javax.swing.JPanel();
        contenedorInputContrasena = new javax.swing.JPanel();
        contenedorBtnMostrarOcultarContrasena = new javax.swing.JPanel();
        btnMostrarOcultarContrasena = new javax.swing.JButton();
        inputContrasena = new javax.swing.JPasswordField();
        lblErrorInputContrasena = new javax.swing.JLabel();
        contenedorRecuperarContrasena = new javax.swing.JPanel();
        btnLinkRecuperarContraseña = new javax.swing.JButton();
        contenedorBotonEnviarFormulario = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 205, 205));
        setMaximumSize(new java.awt.Dimension(32767, 400));
        setMinimumSize(new java.awt.Dimension(380, 400));
        setPreferredSize(new java.awt.Dimension(300, 400));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        contenedorTituloFormulario.setMaximumSize(new java.awt.Dimension(2147483647, 70));
        contenedorTituloFormulario.setMinimumSize(new java.awt.Dimension(500, 70));
        contenedorTituloFormulario.setOpaque(false);
        contenedorTituloFormulario.setPreferredSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setLayout(new java.awt.BorderLayout());

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(17, 35, 85));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Iniciar sesión");
        tituloFormulario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tituloFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setMaximumSize(new java.awt.Dimension(170, 30));
        tituloFormulario.setMinimumSize(new java.awt.Dimension(170, 30));
        tituloFormulario.setPreferredSize(new java.awt.Dimension(170, 30));
        contenedorTituloFormulario.add(tituloFormulario, java.awt.BorderLayout.CENTER);

        add(contenedorTituloFormulario);

        contenedorCuerpoFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 0, 40));
        contenedorCuerpoFormulario.setMinimumSize(new java.awt.Dimension(80, 180));
        contenedorCuerpoFormulario.setOpaque(false);
        contenedorCuerpoFormulario.setPreferredSize(new java.awt.Dimension(500, 200));
        contenedorCuerpoFormulario.setRequestFocusEnabled(false);
        contenedorCuerpoFormulario.setLayout(new javax.swing.BoxLayout(contenedorCuerpoFormulario, javax.swing.BoxLayout.Y_AXIS));

        labelCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCorreo.setText("Correo:");
        labelCorreo.setAlignmentX(0.5F);
        labelCorreo.setIconTextGap(0);
        labelCorreo.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        labelCorreo.setPreferredSize(new java.awt.Dimension(53, 40));
        contenedorCuerpoFormulario.add(labelCorreo);

        contenedorInputYErrorCorreo.setOpaque(false);
        contenedorInputYErrorCorreo.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorInputYErrorCorreo.setLayout(new java.awt.BorderLayout());

        inputCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputCorreo.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputCorreo.setMinimumSize(new java.awt.Dimension(0, 45));
        inputCorreo.setName("correo"); // NOI18N
        inputCorreo.setPreferredSize(new java.awt.Dimension(0, 41));
        contenedorInputYErrorCorreo.add(inputCorreo, java.awt.BorderLayout.NORTH);

        lblErrorInputCorreo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputCorreo.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputCorreo.setAlignmentX(0.5F);
        lblErrorInputCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputCorreo.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorCorreo.add(lblErrorInputCorreo, java.awt.BorderLayout.SOUTH);

        contenedorCuerpoFormulario.add(contenedorInputYErrorCorreo);

        labelContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelContrasena.setText("Contraseña:");
        labelContrasena.setAlignmentX(0.5F);
        labelContrasena.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        labelContrasena.setPreferredSize(new java.awt.Dimension(85, 40));
        contenedorCuerpoFormulario.add(labelContrasena);

        contenedorInputYErrorContrasena.setOpaque(false);
        contenedorInputYErrorContrasena.setPreferredSize(new java.awt.Dimension(400, 60));
        contenedorInputYErrorContrasena.setLayout(new java.awt.BorderLayout());

        contenedorInputContrasena.setBackground(new java.awt.Color(255, 255, 255));
        contenedorInputContrasena.setMaximumSize(new java.awt.Dimension(0, 0));
        contenedorInputContrasena.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorInputContrasena.setName(""); // NOI18N
        contenedorInputContrasena.setOpaque(false);
        contenedorInputContrasena.setPreferredSize(new java.awt.Dimension(0, 41));
        contenedorInputContrasena.setLayout(new javax.swing.OverlayLayout(contenedorInputContrasena));

        contenedorBtnMostrarOcultarContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 4));
        contenedorBtnMostrarOcultarContrasena.setAlignmentY(0.55F);
        contenedorBtnMostrarOcultarContrasena.setOpaque(false);
        contenedorBtnMostrarOcultarContrasena.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorBtnMostrarOcultarContrasena.setLayout(new javax.swing.BoxLayout(contenedorBtnMostrarOcultarContrasena, javax.swing.BoxLayout.Y_AXIS));

        btnMostrarOcultarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarOcultarContrasena.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnMostrarOcultarContrasena.setForeground(new java.awt.Color(17, 35, 85));
        btnMostrarOcultarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/mdi-light--eye-off.png"))); // NOI18N
        btnMostrarOcultarContrasena.setToolTipText("");
        btnMostrarOcultarContrasena.setAlignmentX(1.0F);
        btnMostrarOcultarContrasena.setAlignmentY(0.0F);
        btnMostrarOcultarContrasena.setBorderPainted(false);
        btnMostrarOcultarContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarOcultarContrasena.setFocusCycleRoot(true);
        btnMostrarOcultarContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrarOcultarContrasena.setIconTextGap(0);
        btnMostrarOcultarContrasena.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMostrarOcultarContrasena.setMaximumSize(new java.awt.Dimension(30, 26));
        btnMostrarOcultarContrasena.setMinimumSize(new java.awt.Dimension(30, 26));
        btnMostrarOcultarContrasena.setPreferredSize(new java.awt.Dimension(30, 26));
        contenedorBtnMostrarOcultarContrasena.add(btnMostrarOcultarContrasena);

        contenedorInputContrasena.add(contenedorBtnMostrarOcultarContrasena);

        inputContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputContrasena.setToolTipText("");
        inputContrasena.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputContrasena.setMinimumSize(new java.awt.Dimension(0, 34));
        inputContrasena.setName("contrasena"); // NOI18N
        inputContrasena.setPreferredSize(new java.awt.Dimension(0, 41));
        contenedorInputContrasena.add(inputContrasena);

        contenedorInputYErrorContrasena.add(contenedorInputContrasena, java.awt.BorderLayout.NORTH);

        lblErrorInputContrasena.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputContrasena.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputContrasena.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorContrasena.add(lblErrorInputContrasena, java.awt.BorderLayout.SOUTH);

        contenedorCuerpoFormulario.add(contenedorInputYErrorContrasena);

        add(contenedorCuerpoFormulario);

        contenedorRecuperarContrasena.setMinimumSize(new java.awt.Dimension(500, 30));
        contenedorRecuperarContrasena.setOpaque(false);
        contenedorRecuperarContrasena.setPreferredSize(new java.awt.Dimension(500, 30));
        contenedorRecuperarContrasena.setRequestFocusEnabled(false);

        btnLinkRecuperarContraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLinkRecuperarContraseña.setForeground(new java.awt.Color(30, 166, 177));
        btnLinkRecuperarContraseña.setText("Recuperar Contraseña");
        contenedorRecuperarContrasena.add(btnLinkRecuperarContraseña);

        add(contenedorRecuperarContrasena);

        contenedorBotonEnviarFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        contenedorBotonEnviarFormulario.setOpaque(false);
        contenedorBotonEnviarFormulario.setPreferredSize(new java.awt.Dimension(500, 90));

        btnIngresar.setBackground(new java.awt.Color(30, 166, 177));
        btnIngresar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setToolTipText("");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnIngresar.setMaximumSize(new java.awt.Dimension(200, 40));
        btnIngresar.setMinimumSize(new java.awt.Dimension(200, 40));
        btnIngresar.setPreferredSize(new java.awt.Dimension(200, 40));
        contenedorBotonEnviarFormulario.add(btnIngresar);

        add(contenedorBotonEnviarFormulario);
    }// </editor-fold>//GEN-END:initComponents

    
    // =======================================================
    // MÉTODOS PÚBLICOS PARA EL CONTROLADOR
    // =======================================================

    //Exponer los botones
    public javax.swing.JButton getBtnIngresar() {
        return btnIngresar;
    }

    public javax.swing.JButton getBtnLinkRecuperarContraseña() {
        return btnLinkRecuperarContraseña;
    }

    // Exponer la validación visual
    public boolean ejecutarValidacionFormulario() {
        return formularioIngreso.validar();
    }
    
    // Exponer los datos del formulario en un hash map
    public HashMap<String, String> recolectarDatosFormulario(){
        return formularioIngreso.recolectarDatos();
    }
    
    public void mostrarErrorRespuestaBD(HashMap<String, String> erroresCamposBD ){
        formularioIngreso.mostrarErrorRespuestaBD(erroresCamposBD);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLinkRecuperarContraseña;
    private javax.swing.JButton btnMostrarOcultarContrasena;
    private javax.swing.JPanel contenedorBotonEnviarFormulario;
    private javax.swing.JPanel contenedorBtnMostrarOcultarContrasena;
    private javax.swing.JPanel contenedorCuerpoFormulario;
    private javax.swing.JPanel contenedorInputContrasena;
    private javax.swing.JPanel contenedorInputYErrorContrasena;
    private javax.swing.JPanel contenedorInputYErrorCorreo;
    private javax.swing.JPanel contenedorRecuperarContrasena;
    private javax.swing.JPanel contenedorTituloFormulario;
    private javax.swing.JPasswordField inputContrasena;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel lblErrorInputContrasena;
    private javax.swing.JLabel lblErrorInputCorreo;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
