/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.acceso;

import jafrinventarios.vistas.utilidades.formularios.TipoDatoFormulario;
import jafrinventarios.vistas.utilidades.formularios.GestorFormulario;
import jafrinventarios.vistas.utilidades.dialogos.DialogoMensajePersonalizado;
import jafrinventarios.vistas.utilidades.componentes.MostrarOcultarContrasena;
import jafrinventarios.vistas.utilidades.iconos.IconosBotones;
import jafrinventarios.vistas.utilidades.iconos.IconosDialogosMensajePersonalizado;
import java.util.HashMap;
import javax.swing.JFrame;

/**
 *
 * @author JOHN FORERO
 */
public class RegistroUsuarioPanel extends javax.swing.JPanel {
    
    /* Se crea de manera global para reducir codigo y que desde el checkbox 
        se asigne el mensaje pertinente segun el rol */
    private String mensajeAyudaCodigo;
    
    private final GestorFormulario formularioRegistro = new GestorFormulario();

    /**
     * Creates new form RegistroUsuarioPanel
     */
    public RegistroUsuarioPanel() {
        initComponents();
        mostrarContenedorDatosEmpresa(false);
        
        inyectarCamposAFormulario();
        
        configurarDinamismoAContrasenas();
        
        btnAyudaCodigo.setIcon(IconosBotones.AYUDA.getIcono());
         
        mostrarFormularioDesdeInicio();
        
    }
    
    private void mostrarFormularioDesdeInicio(){
        //Mostramos el formulario desde el inicio, ya que el lblTextAreaDescripcionContrasena
        //por defecto mueve el cursor de escritura hasta su ubicacion, haciendo que el formulario
        //haga scroll hasta su posicion.
        java.awt.EventQueue.invokeLater(() -> {
            panelPrincipalScrolleable.getVerticalScrollBar().setValue(0);
        });
         
    }
    
    private void inyectarCamposAFormulario(){
        
        // Campos Nombre completo
        formularioRegistro.agregarCampo(
                inputPrimerNombre, lblErrorInputPrimerNombre, 
                TipoDatoFormulario.NOMBRE, true);
        formularioRegistro.agregarCampo(
                inputSegundoNombre, lblErrorInputSegundoNombre, 
                TipoDatoFormulario.NOMBRE, false);
        formularioRegistro.agregarCampo(
                inputPrimerApellido, lblErrorInputPrimerApellido, 
                TipoDatoFormulario.NOMBRE, true);
        formularioRegistro.agregarCampo(
                inputSegundoApellido, lblErrorInputSegundoApellido, 
                TipoDatoFormulario.NOMBRE, false);
        
        //Campos Datos de contacto
        formularioRegistro.agregarCampo(
                inputTelefono, lblErrorInputTelefono, 
                TipoDatoFormulario.TELEFONO, true);
        formularioRegistro.agregarCampo(
                inputCorreo, lblErrorInputCorreo, 
                TipoDatoFormulario.CORREO, true);
        
        //Campos credenciales de acceso
        formularioRegistro.agregarCampo(
                inputAlias, lblErrorInputAlias, 
                TipoDatoFormulario.ALIAS, true);
        formularioRegistro.agregarCampo(
                inputContrasena, lblErrorInputContrasena, 
                TipoDatoFormulario.CONTRASENA, true);
        formularioRegistro.agregarCampoConfirmarContrasena(
                inputConfirmarContrasena, inputContrasena, lblErrorInputConfirmarContrasena);
        formularioRegistro.agregarCampo(
                inputCodigo, lblErrorInputCodigo, 
                TipoDatoFormulario.CODIGO, true);
        
        //Campo datos de la empresa se inyecta dependiendo de la seleccion del tipo de usuario
    
    }
    
    
    private void configurarDinamismoAContrasenas(){
        
        MostrarOcultarContrasena.agregarFuncionalidad(inputContrasena, btnMostrarOcultarContrasena);
        MostrarOcultarContrasena.agregarFuncionalidad(inputConfirmarContrasena, btnMostrarOcultarConfirmarContrasena);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipalScrolleable = new javax.swing.JScrollPane();
        contenedorFormulario = new javax.swing.JPanel();
        contenedorTituloFormulario = new javax.swing.JPanel();
        tituloFormulario = new javax.swing.JLabel();
        contenedorCuerpoFormulario = new javax.swing.JPanel();
        contenedorComboBox = new javax.swing.JPanel();
        comboBoxRolUsuario = new javax.swing.JComboBox<>();
        contenedorNombreCompleto = new javax.swing.JPanel();
        contenedorTituloNombreCompleto = new javax.swing.JPanel();
        subtituloNombreCompleto = new javax.swing.JLabel();
        contenedorEntradasNombreCompleto = new javax.swing.JPanel();
        labelPrimerNombre = new javax.swing.JLabel();
        contenedorInputYErrorPrimerNombre = new javax.swing.JPanel();
        inputPrimerNombre = new javax.swing.JTextField();
        lblErrorInputPrimerNombre = new javax.swing.JLabel();
        labelSegundoNombre = new javax.swing.JLabel();
        contenedorInputYErrorSegundoNombre = new javax.swing.JPanel();
        inputSegundoNombre = new javax.swing.JTextField();
        lblErrorInputSegundoNombre = new javax.swing.JLabel();
        labelPrimerApellido = new javax.swing.JLabel();
        contenedorInputYErrorPrimerApellido = new javax.swing.JPanel();
        inputPrimerApellido = new javax.swing.JTextField();
        lblErrorInputPrimerApellido = new javax.swing.JLabel();
        labelSegundoApellido = new javax.swing.JLabel();
        contenedorInputYErrorSegundoApellido = new javax.swing.JPanel();
        inputSegundoApellido = new javax.swing.JTextField();
        lblErrorInputSegundoApellido = new javax.swing.JLabel();
        contenedorDatosContacto = new javax.swing.JPanel();
        contenedorTituloDatosContacto = new javax.swing.JPanel();
        subtituloDatosContacto = new javax.swing.JLabel();
        contenedorEntradasDatosContacto = new javax.swing.JPanel();
        labelTelefono = new javax.swing.JLabel();
        contenedorInputYErrorTelefono = new javax.swing.JPanel();
        inputTelefono = new javax.swing.JTextField();
        lblErrorInputTelefono = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        contenedorInputYErrorCorreo = new javax.swing.JPanel();
        inputCorreo = new javax.swing.JTextField();
        lblErrorInputCorreo = new javax.swing.JLabel();
        contenedorCredenciales = new javax.swing.JPanel();
        contenedorTituloCredenciales = new javax.swing.JPanel();
        subtituloCredenciales = new javax.swing.JLabel();
        contenedorEntradasCredenciales = new javax.swing.JPanel();
        labelAlias = new javax.swing.JLabel();
        contenedorInputYErrorAlias = new javax.swing.JPanel();
        inputAlias = new javax.swing.JTextField();
        lblErrorInputAlias = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        contenedorInputYErrorContrasena = new javax.swing.JPanel();
        contenedorInputContrasena = new javax.swing.JPanel();
        contenedorBtnMostrarOcultarContrasena = new javax.swing.JPanel();
        btnMostrarOcultarContrasena = new javax.swing.JButton();
        inputContrasena = new javax.swing.JPasswordField();
        lblErrorInputContrasena = new javax.swing.JLabel();
        contenedorDescripcionContrasena = new javax.swing.JPanel();
        lblTextAreaDescripcionContrasena = new javax.swing.JTextArea();
        labelConfirmarContrasena = new javax.swing.JLabel();
        contenedorInputYErrorConfirmarContrasena = new javax.swing.JPanel();
        contenedorInputConfirmarContrasena = new javax.swing.JPanel();
        contenedorBtnMostrarOcultarConfirmarContrasena = new javax.swing.JPanel();
        btnMostrarOcultarConfirmarContrasena = new javax.swing.JButton();
        inputConfirmarContrasena = new javax.swing.JPasswordField();
        lblErrorInputConfirmarContrasena = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        contenedorInputYErrorCodigo = new javax.swing.JPanel();
        contenedorInputCodigo = new javax.swing.JPanel();
        contenedorBtnAyudaCodigo = new javax.swing.JPanel();
        btnAyudaCodigo = new javax.swing.JButton();
        inputCodigo = new javax.swing.JTextField();
        lblErrorInputCodigo = new javax.swing.JLabel();
        contenedorDatosEmpresa = new javax.swing.JPanel();
        contenedorTituloDatosEmpresa = new javax.swing.JPanel();
        subtituloDatosEmpresa = new javax.swing.JLabel();
        contenedorEntradasDatosEmpresa = new javax.swing.JPanel();
        labelNombreComercial = new javax.swing.JLabel();
        contenedorInputYErrorNombreComercial = new javax.swing.JPanel();
        inputNombreComercial = new javax.swing.JTextField();
        lblErrorInputNombreComercial = new javax.swing.JLabel();
        contenedorBotonEnviarFormulario = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 205, 205));
        setMaximumSize(new java.awt.Dimension(32767, 850));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(502, 850));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipalScrolleable.setBackground(new java.awt.Color(205, 205, 205));
        panelPrincipalScrolleable.setOpaque(false);

        contenedorFormulario.setBackground(new java.awt.Color(205, 205, 205));
        contenedorFormulario.setLayout(new java.awt.BorderLayout());

        contenedorTituloFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
        contenedorTituloFormulario.setMinimumSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setOpaque(false);
        contenedorTituloFormulario.setPreferredSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setLayout(new java.awt.BorderLayout());

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(17, 35, 85));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Registrarse");
        tituloFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setVerifyInputWhenFocusTarget(false);
        contenedorTituloFormulario.add(tituloFormulario, java.awt.BorderLayout.PAGE_END);

        contenedorFormulario.add(contenedorTituloFormulario, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpoFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 50));
        contenedorCuerpoFormulario.setOpaque(false);
        java.awt.GridBagLayout contenedorCuerpoFormularioLayout = new java.awt.GridBagLayout();
        contenedorCuerpoFormularioLayout.columnWeights = new double[] {1.0};
        contenedorCuerpoFormularioLayout.rowWeights = new double[] {0.0, 0.0, 0.0, 0.0};
        contenedorCuerpoFormulario.setLayout(contenedorCuerpoFormularioLayout);

        contenedorComboBox.setBackground(new java.awt.Color(205, 205, 205));
        contenedorComboBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        contenedorComboBox.setOpaque(false);

        comboBoxRolUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Tipo de Usuario", "Administrador", "Vendedor" }));
        comboBoxRolUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxRolUsuario.setMinimumSize(new java.awt.Dimension(250, 27));
        comboBoxRolUsuario.setName("rol"); // NOI18N
        comboBoxRolUsuario.setPreferredSize(new java.awt.Dimension(250, 31));
        comboBoxRolUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRolUsuarioActionPerformed(evt);
            }
        });
        contenedorComboBox.add(comboBoxRolUsuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorCuerpoFormulario.add(contenedorComboBox, gridBagConstraints);

        contenedorNombreCompleto.setOpaque(false);
        contenedorNombreCompleto.setLayout(new javax.swing.BoxLayout(contenedorNombreCompleto, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloNombreCompleto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloNombreCompleto.setOpaque(false);
        contenedorTituloNombreCompleto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloNombreCompleto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloNombreCompleto.setText("Nombre Completo");
        subtituloNombreCompleto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloNombreCompleto.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloNombreCompleto.add(subtituloNombreCompleto);

        contenedorNombreCompleto.add(contenedorTituloNombreCompleto);

        contenedorEntradasNombreCompleto.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 0, 20));
        contenedorEntradasNombreCompleto.setOpaque(false);
        contenedorEntradasNombreCompleto.setLayout(new java.awt.GridBagLayout());

        labelPrimerNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelPrimerNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPrimerNombre.setText("Primer Nombre :");
        labelPrimerNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelPrimerNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelPrimerNombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelPrimerNombre.setMaximumSize(new java.awt.Dimension(0, 0));
        labelPrimerNombre.setMinimumSize(new java.awt.Dimension(0, 0));
        labelPrimerNombre.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasNombreCompleto.add(labelPrimerNombre, gridBagConstraints);

        contenedorInputYErrorPrimerNombre.setOpaque(false);
        contenedorInputYErrorPrimerNombre.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorPrimerNombre.setLayout(new java.awt.BorderLayout());

        inputPrimerNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputPrimerNombre.setEnabled(false);
        inputPrimerNombre.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputPrimerNombre.setName("primerNombre"); // NOI18N
        inputPrimerNombre.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorPrimerNombre.add(inputPrimerNombre, java.awt.BorderLayout.NORTH);

        lblErrorInputPrimerNombre.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputPrimerNombre.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputPrimerNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputPrimerNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputPrimerNombre.setPreferredSize(new java.awt.Dimension(0, 17));
        lblErrorInputPrimerNombre.setRequestFocusEnabled(false);
        contenedorInputYErrorPrimerNombre.add(lblErrorInputPrimerNombre, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorPrimerNombre, gridBagConstraints);

        labelSegundoNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelSegundoNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSegundoNombre.setText("Segundo Nombre :");
        labelSegundoNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelSegundoNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelSegundoNombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelSegundoNombre.setMaximumSize(new java.awt.Dimension(0, 0));
        labelSegundoNombre.setMinimumSize(new java.awt.Dimension(0, 0));
        labelSegundoNombre.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasNombreCompleto.add(labelSegundoNombre, gridBagConstraints);

        contenedorInputYErrorSegundoNombre.setOpaque(false);
        contenedorInputYErrorSegundoNombre.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorSegundoNombre.setLayout(new java.awt.BorderLayout());

        inputSegundoNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputSegundoNombre.setEnabled(false);
        inputSegundoNombre.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputSegundoNombre.setName("segundoNombre"); // NOI18N
        inputSegundoNombre.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorSegundoNombre.add(inputSegundoNombre, java.awt.BorderLayout.NORTH);

        lblErrorInputSegundoNombre.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputSegundoNombre.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputSegundoNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputSegundoNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputSegundoNombre.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorSegundoNombre.add(lblErrorInputSegundoNombre, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorSegundoNombre, gridBagConstraints);

        labelPrimerApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelPrimerApellido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelPrimerApellido.setText("Primer Apellido :");
        labelPrimerApellido.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelPrimerApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelPrimerApellido.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelPrimerApellido.setMaximumSize(new java.awt.Dimension(0, 0));
        labelPrimerApellido.setMinimumSize(new java.awt.Dimension(0, 0));
        labelPrimerApellido.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasNombreCompleto.add(labelPrimerApellido, gridBagConstraints);

        contenedorInputYErrorPrimerApellido.setOpaque(false);
        contenedorInputYErrorPrimerApellido.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorPrimerApellido.setLayout(new java.awt.BorderLayout());

        inputPrimerApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputPrimerApellido.setToolTipText("");
        inputPrimerApellido.setEnabled(false);
        inputPrimerApellido.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputPrimerApellido.setName("primerApellido"); // NOI18N
        inputPrimerApellido.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorPrimerApellido.add(inputPrimerApellido, java.awt.BorderLayout.NORTH);

        lblErrorInputPrimerApellido.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputPrimerApellido.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputPrimerApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputPrimerApellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputPrimerApellido.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorPrimerApellido.add(lblErrorInputPrimerApellido, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorPrimerApellido, gridBagConstraints);

        labelSegundoApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelSegundoApellido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelSegundoApellido.setText("Segundo Apellido :");
        labelSegundoApellido.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelSegundoApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelSegundoApellido.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelSegundoApellido.setMaximumSize(new java.awt.Dimension(0, 0));
        labelSegundoApellido.setMinimumSize(new java.awt.Dimension(0, 0));
        labelSegundoApellido.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorEntradasNombreCompleto.add(labelSegundoApellido, gridBagConstraints);

        contenedorInputYErrorSegundoApellido.setOpaque(false);
        contenedorInputYErrorSegundoApellido.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorSegundoApellido.setLayout(new java.awt.BorderLayout());

        inputSegundoApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputSegundoApellido.setEnabled(false);
        inputSegundoApellido.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputSegundoApellido.setName("segundoApellido"); // NOI18N
        inputSegundoApellido.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorSegundoApellido.add(inputSegundoApellido, java.awt.BorderLayout.NORTH);

        lblErrorInputSegundoApellido.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputSegundoApellido.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputSegundoApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputSegundoApellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputSegundoApellido.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorSegundoApellido.add(lblErrorInputSegundoApellido, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorSegundoApellido, gridBagConstraints);

        contenedorNombreCompleto.add(contenedorEntradasNombreCompleto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorCuerpoFormulario.add(contenedorNombreCompleto, gridBagConstraints);

        contenedorDatosContacto.setOpaque(false);
        contenedorDatosContacto.setLayout(new javax.swing.BoxLayout(contenedorDatosContacto, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloDatosContacto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloDatosContacto.setOpaque(false);
        contenedorTituloDatosContacto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloDatosContacto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloDatosContacto.setText("Datos de contacto");
        subtituloDatosContacto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloDatosContacto.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloDatosContacto.add(subtituloDatosContacto);

        contenedorDatosContacto.add(contenedorTituloDatosContacto);

        contenedorEntradasDatosContacto.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 20, 0, 20));
        contenedorEntradasDatosContacto.setOpaque(false);
        contenedorEntradasDatosContacto.setLayout(new java.awt.GridBagLayout());

        labelTelefono.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTelefono.setText("Telefono :");
        labelTelefono.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelTelefono.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelTelefono.setMaximumSize(new java.awt.Dimension(0, 0));
        labelTelefono.setMinimumSize(new java.awt.Dimension(0, 0));
        labelTelefono.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasDatosContacto.add(labelTelefono, gridBagConstraints);

        contenedorInputYErrorTelefono.setOpaque(false);
        contenedorInputYErrorTelefono.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorTelefono.setLayout(new java.awt.BorderLayout());

        inputTelefono.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputTelefono.setEnabled(false);
        inputTelefono.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputTelefono.setName("telefono"); // NOI18N
        inputTelefono.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorTelefono.add(inputTelefono, java.awt.BorderLayout.NORTH);

        lblErrorInputTelefono.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputTelefono.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputTelefono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputTelefono.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorTelefono.add(lblErrorInputTelefono, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasDatosContacto.add(contenedorInputYErrorTelefono, gridBagConstraints);

        labelCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCorreo.setText("Correo :");
        labelCorreo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelCorreo.setMaximumSize(new java.awt.Dimension(0, 0));
        labelCorreo.setMinimumSize(new java.awt.Dimension(0, 0));
        labelCorreo.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorEntradasDatosContacto.add(labelCorreo, gridBagConstraints);

        contenedorInputYErrorCorreo.setOpaque(false);
        contenedorInputYErrorCorreo.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorCorreo.setLayout(new java.awt.BorderLayout());

        inputCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputCorreo.setEnabled(false);
        inputCorreo.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputCorreo.setName("correo"); // NOI18N
        inputCorreo.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorCorreo.add(inputCorreo, java.awt.BorderLayout.NORTH);

        lblErrorInputCorreo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputCorreo.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputCorreo.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorCorreo.add(lblErrorInputCorreo, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasDatosContacto.add(contenedorInputYErrorCorreo, gridBagConstraints);

        contenedorDatosContacto.add(contenedorEntradasDatosContacto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorCuerpoFormulario.add(contenedorDatosContacto, gridBagConstraints);

        contenedorCredenciales.setOpaque(false);
        contenedorCredenciales.setLayout(new javax.swing.BoxLayout(contenedorCredenciales, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloCredenciales.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloCredenciales.setOpaque(false);
        contenedorTituloCredenciales.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloCredenciales.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloCredenciales.setText("Credenciales de Acceso");
        subtituloCredenciales.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloCredenciales.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloCredenciales.add(subtituloCredenciales);

        contenedorCredenciales.add(contenedorTituloCredenciales);

        contenedorEntradasCredenciales.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 20, 0, 20));
        contenedorEntradasCredenciales.setOpaque(false);
        contenedorEntradasCredenciales.setLayout(new java.awt.GridBagLayout());

        labelAlias.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelAlias.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAlias.setText("Alias :");
        labelAlias.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelAlias.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelAlias.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelAlias.setMaximumSize(new java.awt.Dimension(0, 0));
        labelAlias.setMinimumSize(new java.awt.Dimension(0, 0));
        labelAlias.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasCredenciales.add(labelAlias, gridBagConstraints);

        contenedorInputYErrorAlias.setOpaque(false);
        contenedorInputYErrorAlias.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorAlias.setLayout(new java.awt.BorderLayout());

        inputAlias.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputAlias.setEnabled(false);
        inputAlias.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputAlias.setName("alias"); // NOI18N
        inputAlias.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorAlias.add(inputAlias, java.awt.BorderLayout.NORTH);

        lblErrorInputAlias.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputAlias.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputAlias.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputAlias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputAlias.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorAlias.add(lblErrorInputAlias, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasCredenciales.add(contenedorInputYErrorAlias, gridBagConstraints);

        labelContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelContrasena.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelContrasena.setText("Contraseña :");
        labelContrasena.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelContrasena.setMaximumSize(new java.awt.Dimension(0, 0));
        labelContrasena.setMinimumSize(new java.awt.Dimension(0, 0));
        labelContrasena.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasCredenciales.add(labelContrasena, gridBagConstraints);

        contenedorInputYErrorContrasena.setOpaque(false);
        contenedorInputYErrorContrasena.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorContrasena.setLayout(new java.awt.BorderLayout());

        contenedorInputContrasena.setBackground(new java.awt.Color(255, 255, 255));
        contenedorInputContrasena.setMaximumSize(new java.awt.Dimension(0, 0));
        contenedorInputContrasena.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorInputContrasena.setName(""); // NOI18N
        contenedorInputContrasena.setOpaque(false);
        contenedorInputContrasena.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputContrasena.setLayout(new javax.swing.OverlayLayout(contenedorInputContrasena));

        contenedorBtnMostrarOcultarContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 4));
        contenedorBtnMostrarOcultarContrasena.setAlignmentY(0.55F);
        contenedorBtnMostrarOcultarContrasena.setMaximumSize(new java.awt.Dimension(34, 26));
        contenedorBtnMostrarOcultarContrasena.setMinimumSize(new java.awt.Dimension(34, 26));
        contenedorBtnMostrarOcultarContrasena.setOpaque(false);
        contenedorBtnMostrarOcultarContrasena.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorBtnMostrarOcultarContrasena.setLayout(new javax.swing.BoxLayout(contenedorBtnMostrarOcultarContrasena, javax.swing.BoxLayout.Y_AXIS));

        btnMostrarOcultarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarOcultarContrasena.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnMostrarOcultarContrasena.setForeground(new java.awt.Color(17, 35, 85));
        btnMostrarOcultarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/mdi-light--eye-off.png"))); // NOI18N
        btnMostrarOcultarContrasena.setToolTipText("");
        btnMostrarOcultarContrasena.setAlignmentX(1.0F);
        btnMostrarOcultarContrasena.setAlignmentY(0.0F);
        btnMostrarOcultarContrasena.setBorderPainted(false);
        btnMostrarOcultarContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarOcultarContrasena.setEnabled(false);
        btnMostrarOcultarContrasena.setFocusCycleRoot(true);
        btnMostrarOcultarContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrarOcultarContrasena.setIconTextGap(0);
        btnMostrarOcultarContrasena.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMostrarOcultarContrasena.setMaximumSize(new java.awt.Dimension(30, 26));
        btnMostrarOcultarContrasena.setMinimumSize(new java.awt.Dimension(30, 26));
        btnMostrarOcultarContrasena.setPreferredSize(new java.awt.Dimension(30, 26));
        contenedorBtnMostrarOcultarContrasena.add(btnMostrarOcultarContrasena);

        contenedorInputContrasena.add(contenedorBtnMostrarOcultarContrasena);

        inputContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputContrasena.setToolTipText("");
        inputContrasena.setEnabled(false);
        inputContrasena.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputContrasena.setMinimumSize(new java.awt.Dimension(0, 34));
        inputContrasena.setName("contrasena"); // NOI18N
        inputContrasena.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputContrasena.add(inputContrasena);

        contenedorInputYErrorContrasena.add(contenedorInputContrasena, java.awt.BorderLayout.NORTH);

        lblErrorInputContrasena.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputContrasena.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputContrasena.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorContrasena.add(lblErrorInputContrasena, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        contenedorEntradasCredenciales.add(contenedorInputYErrorContrasena, gridBagConstraints);

        contenedorDescripcionContrasena.setOpaque(false);
        contenedorDescripcionContrasena.setPreferredSize(new java.awt.Dimension(0, 96));
        contenedorDescripcionContrasena.setLayout(new java.awt.BorderLayout());

        lblTextAreaDescripcionContrasena.setEditable(false);
        lblTextAreaDescripcionContrasena.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTextAreaDescripcionContrasena.setRows(5);
        lblTextAreaDescripcionContrasena.setText("La contraseña debe contener por lo menos:\n* Una mayuscula\n* Una minuscula\n* Un número\n* Un caracter especial\n* Minimo 8 caraceres");
        lblTextAreaDescripcionContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 0));
        lblTextAreaDescripcionContrasena.setCaretPosition(0);
        lblTextAreaDescripcionContrasena.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTextAreaDescripcionContrasena.setOpaque(false);
        lblTextAreaDescripcionContrasena.setPreferredSize(new java.awt.Dimension(0, 85));
        contenedorDescripcionContrasena.add(lblTextAreaDescripcionContrasena, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 14, 0);
        contenedorEntradasCredenciales.add(contenedorDescripcionContrasena, gridBagConstraints);

        labelConfirmarContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelConfirmarContrasena.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelConfirmarContrasena.setText("Confirmar Contraseña :");
        labelConfirmarContrasena.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelConfirmarContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelConfirmarContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelConfirmarContrasena.setMaximumSize(new java.awt.Dimension(0, 0));
        labelConfirmarContrasena.setMinimumSize(new java.awt.Dimension(0, 0));
        labelConfirmarContrasena.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasCredenciales.add(labelConfirmarContrasena, gridBagConstraints);

        contenedorInputYErrorConfirmarContrasena.setOpaque(false);
        contenedorInputYErrorConfirmarContrasena.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorConfirmarContrasena.setLayout(new java.awt.BorderLayout());

        contenedorInputConfirmarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        contenedorInputConfirmarContrasena.setMaximumSize(new java.awt.Dimension(0, 0));
        contenedorInputConfirmarContrasena.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorInputConfirmarContrasena.setName(""); // NOI18N
        contenedorInputConfirmarContrasena.setOpaque(false);
        contenedorInputConfirmarContrasena.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputConfirmarContrasena.setLayout(new javax.swing.OverlayLayout(contenedorInputConfirmarContrasena));

        contenedorBtnMostrarOcultarConfirmarContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 4));
        contenedorBtnMostrarOcultarConfirmarContrasena.setAlignmentY(0.55F);
        contenedorBtnMostrarOcultarConfirmarContrasena.setOpaque(false);
        contenedorBtnMostrarOcultarConfirmarContrasena.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorBtnMostrarOcultarConfirmarContrasena.setLayout(new javax.swing.BoxLayout(contenedorBtnMostrarOcultarConfirmarContrasena, javax.swing.BoxLayout.Y_AXIS));

        btnMostrarOcultarConfirmarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarOcultarConfirmarContrasena.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnMostrarOcultarConfirmarContrasena.setForeground(new java.awt.Color(17, 35, 85));
        btnMostrarOcultarConfirmarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/mdi-light--eye-off.png"))); // NOI18N
        btnMostrarOcultarConfirmarContrasena.setToolTipText("");
        btnMostrarOcultarConfirmarContrasena.setAlignmentX(1.0F);
        btnMostrarOcultarConfirmarContrasena.setAlignmentY(0.0F);
        btnMostrarOcultarConfirmarContrasena.setBorderPainted(false);
        btnMostrarOcultarConfirmarContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarOcultarConfirmarContrasena.setEnabled(false);
        btnMostrarOcultarConfirmarContrasena.setFocusCycleRoot(true);
        btnMostrarOcultarConfirmarContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrarOcultarConfirmarContrasena.setIconTextGap(0);
        btnMostrarOcultarConfirmarContrasena.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMostrarOcultarConfirmarContrasena.setMaximumSize(new java.awt.Dimension(30, 26));
        btnMostrarOcultarConfirmarContrasena.setMinimumSize(new java.awt.Dimension(30, 26));
        btnMostrarOcultarConfirmarContrasena.setPreferredSize(new java.awt.Dimension(30, 26));
        contenedorBtnMostrarOcultarConfirmarContrasena.add(btnMostrarOcultarConfirmarContrasena);

        contenedorInputConfirmarContrasena.add(contenedorBtnMostrarOcultarConfirmarContrasena);

        inputConfirmarContrasena.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputConfirmarContrasena.setToolTipText("");
        inputConfirmarContrasena.setEnabled(false);
        inputConfirmarContrasena.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputConfirmarContrasena.setMinimumSize(new java.awt.Dimension(0, 34));
        inputConfirmarContrasena.setName("confirmarContrasena"); // NOI18N
        inputConfirmarContrasena.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputConfirmarContrasena.add(inputConfirmarContrasena);

        contenedorInputYErrorConfirmarContrasena.add(contenedorInputConfirmarContrasena, java.awt.BorderLayout.NORTH);

        lblErrorInputConfirmarContrasena.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputConfirmarContrasena.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputConfirmarContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputConfirmarContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputConfirmarContrasena.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorConfirmarContrasena.add(lblErrorInputConfirmarContrasena, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasCredenciales.add(contenedorInputYErrorConfirmarContrasena, gridBagConstraints);

        labelCodigo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCodigo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelCodigo.setText("Código de acceso :");
        labelCodigo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelCodigo.setMaximumSize(new java.awt.Dimension(0, 0));
        labelCodigo.setMinimumSize(new java.awt.Dimension(0, 0));
        labelCodigo.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorEntradasCredenciales.add(labelCodigo, gridBagConstraints);

        contenedorInputYErrorCodigo.setOpaque(false);
        contenedorInputYErrorCodigo.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorCodigo.setLayout(new java.awt.BorderLayout());

        contenedorInputCodigo.setBackground(new java.awt.Color(255, 255, 255));
        contenedorInputCodigo.setMaximumSize(new java.awt.Dimension(0, 0));
        contenedorInputCodigo.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorInputCodigo.setOpaque(false);
        contenedorInputCodigo.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputCodigo.setLayout(new javax.swing.OverlayLayout(contenedorInputCodigo));

        contenedorBtnAyudaCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 4));
        contenedorBtnAyudaCodigo.setOpaque(false);
        contenedorBtnAyudaCodigo.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorBtnAyudaCodigo.setLayout(new javax.swing.BoxLayout(contenedorBtnAyudaCodigo, javax.swing.BoxLayout.Y_AXIS));

        btnAyudaCodigo.setBackground(new java.awt.Color(255, 255, 255));
        btnAyudaCodigo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAyudaCodigo.setForeground(new java.awt.Color(17, 35, 85));
        btnAyudaCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/fluent--chat-help-24-filled.png"))); // NOI18N
        btnAyudaCodigo.setToolTipText("");
        btnAyudaCodigo.setAlignmentX(1.0F);
        btnAyudaCodigo.setBorderPainted(false);
        btnAyudaCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyudaCodigo.setEnabled(false);
        btnAyudaCodigo.setFocusCycleRoot(true);
        btnAyudaCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAyudaCodigo.setIconTextGap(0);
        btnAyudaCodigo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAyudaCodigo.setMaximumSize(new java.awt.Dimension(30, 26));
        btnAyudaCodigo.setMinimumSize(new java.awt.Dimension(30, 26));
        btnAyudaCodigo.setPreferredSize(new java.awt.Dimension(30, 26));
        btnAyudaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaCodigoActionPerformed(evt);
            }
        });
        contenedorBtnAyudaCodigo.add(btnAyudaCodigo);

        contenedorInputCodigo.add(contenedorBtnAyudaCodigo);

        inputCodigo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputCodigo.setEnabled(false);
        inputCodigo.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputCodigo.setMinimumSize(new java.awt.Dimension(0, 34));
        inputCodigo.setName("codigo"); // NOI18N
        inputCodigo.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputCodigo.add(inputCodigo);

        contenedorInputYErrorCodigo.add(contenedorInputCodigo, java.awt.BorderLayout.NORTH);

        lblErrorInputCodigo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputCodigo.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputCodigo.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorCodigo.add(lblErrorInputCodigo, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasCredenciales.add(contenedorInputYErrorCodigo, gridBagConstraints);

        contenedorCredenciales.add(contenedorEntradasCredenciales);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorCuerpoFormulario.add(contenedorCredenciales, gridBagConstraints);

        contenedorDatosEmpresa.setOpaque(false);
        contenedorDatosEmpresa.setLayout(new javax.swing.BoxLayout(contenedorDatosEmpresa, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloDatosEmpresa.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloDatosEmpresa.setOpaque(false);
        contenedorTituloDatosEmpresa.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloDatosEmpresa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloDatosEmpresa.setText("Datos de la empresa");
        subtituloDatosEmpresa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloDatosEmpresa.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloDatosEmpresa.add(subtituloDatosEmpresa);

        contenedorDatosEmpresa.add(contenedorTituloDatosEmpresa);

        contenedorEntradasDatosEmpresa.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 20, 0, 20));
        contenedorEntradasDatosEmpresa.setOpaque(false);
        contenedorEntradasDatosEmpresa.setLayout(new java.awt.GridBagLayout());

        labelNombreComercial.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelNombreComercial.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelNombreComercial.setText("Nombre comercial :");
        labelNombreComercial.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelNombreComercial.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelNombreComercial.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelNombreComercial.setMaximumSize(new java.awt.Dimension(0, 0));
        labelNombreComercial.setMinimumSize(new java.awt.Dimension(0, 0));
        labelNombreComercial.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorEntradasDatosEmpresa.add(labelNombreComercial, gridBagConstraints);

        contenedorInputYErrorNombreComercial.setOpaque(false);
        contenedorInputYErrorNombreComercial.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorNombreComercial.setLayout(new java.awt.BorderLayout());

        inputNombreComercial.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputNombreComercial.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputNombreComercial.setName("nombreEmpresa"); // NOI18N
        inputNombreComercial.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorNombreComercial.add(inputNombreComercial, java.awt.BorderLayout.NORTH);

        lblErrorInputNombreComercial.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputNombreComercial.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputNombreComercial.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputNombreComercial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputNombreComercial.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorNombreComercial.add(lblErrorInputNombreComercial, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasDatosEmpresa.add(contenedorInputYErrorNombreComercial, gridBagConstraints);

        contenedorDatosEmpresa.add(contenedorEntradasDatosEmpresa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contenedorCuerpoFormulario.add(contenedorDatosEmpresa, gridBagConstraints);

        contenedorFormulario.add(contenedorCuerpoFormulario, java.awt.BorderLayout.CENTER);

        contenedorBotonEnviarFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        contenedorBotonEnviarFormulario.setOpaque(false);
        contenedorBotonEnviarFormulario.setPreferredSize(new java.awt.Dimension(500, 90));

        btnRegistrar.setBackground(new java.awt.Color(30, 166, 177));
        btnRegistrar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrarme");
        btnRegistrar.setToolTipText("");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setEnabled(false);
        btnRegistrar.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnRegistrar.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegistrar.setMinimumSize(new java.awt.Dimension(200, 40));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(200, 40));
        contenedorBotonEnviarFormulario.add(btnRegistrar);

        contenedorFormulario.add(contenedorBotonEnviarFormulario, java.awt.BorderLayout.PAGE_END);

        panelPrincipalScrolleable.setViewportView(contenedorFormulario);

        add(panelPrincipalScrolleable);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxRolUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRolUsuarioActionPerformed
        
        String rolSeleccionado = (String) comboBoxRolUsuario.getSelectedItem();
        
        if(rolSeleccionado == null || comboBoxRolUsuario.getSelectedIndex() == 0){
            desactivarFormulario();
        }else{
            /*
               Los roles previamente se conoce que se van a nombrar como administrador
                y vendedor debido a que esto depende de como se personaliza el 
                formulario, es imperativo tener congruencia con la base de datos
            */
            switch(rolSeleccionado.toLowerCase()){
                case "administrador":
                    activarFormularioAdministrador();
                    mensajeAyudaCodigo = "El código de acceso se obtiene con el creador del programa.";
                    break;
                case "vendedor":
                    activarFormularioVendedor();
                    mensajeAyudaCodigo = "El código de acceso se obtiene con el administrador de la empresa.";
                    break;
                default:
                    System.out.println("Rol de usuario desconocido");
                    break;
            }           
        }
        
        formularioRegistro.limpiarErrores();
    }//GEN-LAST:event_comboBoxRolUsuarioActionPerformed

    private void btnAyudaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaCodigoActionPerformed
        mostrarMensajeAyudaCodigo();
    }//GEN-LAST:event_btnAyudaCodigoActionPerformed

    
    private void activarFormularioAdministrador(){
        asignarEdicionCamposFormulario(true);
        mostrarContenedorDatosEmpresa(true);
    }
    
    private void activarFormularioVendedor(){   
        asignarEdicionCamposFormulario(true);
        mostrarContenedorDatosEmpresa(false);
    }
    
    private void desactivarFormulario(){
        asignarEdicionCamposFormulario(false);
        mostrarContenedorDatosEmpresa(false);
    }
    
    private void asignarEdicionCamposFormulario(boolean editable){
        
        inputPrimerNombre.setEnabled(editable);
        inputSegundoNombre.setEnabled(editable);
        inputPrimerApellido.setEnabled(editable);
        inputSegundoApellido.setEnabled(editable);
        
        inputTelefono.setEnabled(editable);
        inputCorreo.setEnabled(editable);
        
        inputAlias.setEnabled(editable);
        inputContrasena.setEnabled(editable);
        btnMostrarOcultarContrasena.setEnabled(editable);
        inputConfirmarContrasena.setEnabled(editable);
        btnMostrarOcultarConfirmarContrasena.setEnabled(editable);
        inputCodigo.setEnabled(editable);
        btnAyudaCodigo.setEnabled(editable);
        btnRegistrar.setEnabled(editable);
        
    }
    
    private void mostrarContenedorDatosEmpresa(boolean mostrar){
        contenedorDatosEmpresa.setVisible(mostrar);
        
        //Inyectar o Eliminar Campo datos de la empresa a camposFormularioRegistro
        if(mostrar){
            formularioRegistro.agregarCampo(
                inputNombreComercial, lblErrorInputNombreComercial, 
                TipoDatoFormulario.NOMBRE, true);
        }else{
            formularioRegistro.eliminarCualquierCampo(inputNombreComercial);
        }

    }
    
    
    private void mostrarMensajeAyudaCodigo (){
           
        DialogoMensajePersonalizado.mostrar(
                (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), 
                "Información código de acceso",
                mensajeAyudaCodigo,
                IconosDialogosMensajePersonalizado.INFORMACION,
                false
                );
        
    } 
    
    
    // =======================================================
    // MÉTODOS PÚBLICOS PARA EL CONTROLADOR
    // =======================================================
    
    // metodo para que el constructor envie los roles que estan en la base de datos
    // Se espera que la clave sea el nombre y el valor sea el id, este se utilizara
    // estrategicamente en un nuevo campovalidable de tipo chechbox para devolver el id
    // cuando el controlador solicite recopilar la informacion del formulario
    // Se ha creado dentro del constructor del comboBox una funcion para que cargue el hashmap enviado al comboBox
    public void inicializarComboBoxRoles(HashMap<String, Integer> rolesDeBD) {
        
        formularioRegistro.agregarCampoComboBox(
                comboBoxRolUsuario,
                "Tipo de Usuario",
                rolesDeBD, 
                null, 
                true);
        
    }
    
     //Exponer los botones
    public javax.swing.JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    // Exponer la validación visual
    public boolean ejecutarValidacionFormulario() {
        return formularioRegistro.validar();
    }
    
    // Exponer los datos del formulario en un hash map
    public HashMap<String, String> recolectarDatosFormulario(){
        return formularioRegistro.recolectarDatos();
    }
    
    public void mostrarErrorRespuestaBD(HashMap<String, String> erroresCamposBD ){
        formularioRegistro.mostrarErrorRespuestaBD(erroresCamposBD);
    }
    
    public void ejecutarLimpiezaFormulario(){
        formularioRegistro.limpiarCampos();
        mostrarFormularioDesdeInicio();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyudaCodigo;
    private javax.swing.JButton btnMostrarOcultarConfirmarContrasena;
    private javax.swing.JButton btnMostrarOcultarContrasena;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboBoxRolUsuario;
    private javax.swing.JPanel contenedorBotonEnviarFormulario;
    private javax.swing.JPanel contenedorBtnAyudaCodigo;
    private javax.swing.JPanel contenedorBtnMostrarOcultarConfirmarContrasena;
    private javax.swing.JPanel contenedorBtnMostrarOcultarContrasena;
    private javax.swing.JPanel contenedorComboBox;
    private javax.swing.JPanel contenedorCredenciales;
    private javax.swing.JPanel contenedorCuerpoFormulario;
    private javax.swing.JPanel contenedorDatosContacto;
    private javax.swing.JPanel contenedorDatosEmpresa;
    private javax.swing.JPanel contenedorDescripcionContrasena;
    private javax.swing.JPanel contenedorEntradasCredenciales;
    private javax.swing.JPanel contenedorEntradasDatosContacto;
    private javax.swing.JPanel contenedorEntradasDatosEmpresa;
    private javax.swing.JPanel contenedorEntradasNombreCompleto;
    private javax.swing.JPanel contenedorFormulario;
    private javax.swing.JPanel contenedorInputCodigo;
    private javax.swing.JPanel contenedorInputConfirmarContrasena;
    private javax.swing.JPanel contenedorInputContrasena;
    private javax.swing.JPanel contenedorInputYErrorAlias;
    private javax.swing.JPanel contenedorInputYErrorCodigo;
    private javax.swing.JPanel contenedorInputYErrorConfirmarContrasena;
    private javax.swing.JPanel contenedorInputYErrorContrasena;
    private javax.swing.JPanel contenedorInputYErrorCorreo;
    private javax.swing.JPanel contenedorInputYErrorNombreComercial;
    private javax.swing.JPanel contenedorInputYErrorPrimerApellido;
    private javax.swing.JPanel contenedorInputYErrorPrimerNombre;
    private javax.swing.JPanel contenedorInputYErrorSegundoApellido;
    private javax.swing.JPanel contenedorInputYErrorSegundoNombre;
    private javax.swing.JPanel contenedorInputYErrorTelefono;
    private javax.swing.JPanel contenedorNombreCompleto;
    private javax.swing.JPanel contenedorTituloCredenciales;
    private javax.swing.JPanel contenedorTituloDatosContacto;
    private javax.swing.JPanel contenedorTituloDatosEmpresa;
    private javax.swing.JPanel contenedorTituloFormulario;
    private javax.swing.JPanel contenedorTituloNombreCompleto;
    private javax.swing.JTextField inputAlias;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JPasswordField inputConfirmarContrasena;
    private javax.swing.JPasswordField inputContrasena;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputNombreComercial;
    private javax.swing.JTextField inputPrimerApellido;
    private javax.swing.JTextField inputPrimerNombre;
    private javax.swing.JTextField inputSegundoApellido;
    private javax.swing.JTextField inputSegundoNombre;
    private javax.swing.JTextField inputTelefono;
    private javax.swing.JLabel labelAlias;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelConfirmarContrasena;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelNombreComercial;
    private javax.swing.JLabel labelPrimerApellido;
    private javax.swing.JLabel labelPrimerNombre;
    private javax.swing.JLabel labelSegundoApellido;
    private javax.swing.JLabel labelSegundoNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel lblErrorInputAlias;
    private javax.swing.JLabel lblErrorInputCodigo;
    private javax.swing.JLabel lblErrorInputConfirmarContrasena;
    private javax.swing.JLabel lblErrorInputContrasena;
    private javax.swing.JLabel lblErrorInputCorreo;
    private javax.swing.JLabel lblErrorInputNombreComercial;
    private javax.swing.JLabel lblErrorInputPrimerApellido;
    private javax.swing.JLabel lblErrorInputPrimerNombre;
    private javax.swing.JLabel lblErrorInputSegundoApellido;
    private javax.swing.JLabel lblErrorInputSegundoNombre;
    private javax.swing.JLabel lblErrorInputTelefono;
    private javax.swing.JTextArea lblTextAreaDescripcionContrasena;
    private javax.swing.JScrollPane panelPrincipalScrolleable;
    private javax.swing.JLabel subtituloCredenciales;
    private javax.swing.JLabel subtituloDatosContacto;
    private javax.swing.JLabel subtituloDatosEmpresa;
    private javax.swing.JLabel subtituloNombreCompleto;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables

}
