
package jafrinventarios.vistas.principal;

import jafrinventarios.vistas.utilidades.componentes.DinamismoLink;
import jafrinventarios.vistas.utilidades.iconos.IconosSecciones;
import javax.swing.JButton;

/**
 *
 * @author JOHN FORERO
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu(boolean esAdministrador) {
        initComponents();
        if(!esAdministrador){
            personalizarRolNoAdministrador();          
        }

        aplicarIconosDesdeEnum(esAdministrador);
        aplicarEfectoLinkABotones(esAdministrador);
    }
    
    private void personalizarRolNoAdministrador(){
        menuSeccionUsuarios.setVisible(false);
        menuSeccionProveedores.setVisible(false);
        menuSeccionCompras.setVisible(false);
        menuSeccionReporte.setVisible(false);
    }
    
    private void aplicarIconosDesdeEnum(boolean esAdministrador){
        btnLinkSeccionInicio.setIcon( IconosSecciones.INICIO.getIcono() );
        btnLinkSeccionProductos.setIcon( IconosSecciones.PRODUCTOS.getIcono() );
        btnLinkSeccionClientes.setIcon( IconosSecciones.CLIENTES.getIcono() );
        btnLinkSeccionVentas.setIcon( IconosSecciones.VENTAS.getIcono() );
        btnLinkSeccionInventario.setIcon( IconosSecciones.INVENTARIO.getIcono() );
        
        if(esAdministrador){
            btnLinkSeccionUsuarios.setIcon( IconosSecciones.USUARIOS.getIcono() );
            btnLinkSeccionProveedores.setIcon( IconosSecciones.PROVEEDORES.getIcono() );
            btnLinkSeccionCompras.setIcon( IconosSecciones.COMPRAS.getIcono() );
            btnLinkSeccionReporte.setIcon( IconosSecciones.REPORTE.getIcono() );
        }
    }
    
    private void aplicarEfectoLinkABotones(boolean esAdministrador){
        DinamismoLink.aplicarEfecto(btnLinkSeccionInicio);
        DinamismoLink.aplicarEfecto(btnLinkSeccionProductos);
        DinamismoLink.aplicarEfecto(btnLinkSeccionClientes);
        DinamismoLink.aplicarEfecto(btnLinkSeccionVentas);
        DinamismoLink.aplicarEfecto(btnLinkSeccionInventario);
        
        if(esAdministrador){
            DinamismoLink.aplicarEfecto(btnLinkSeccionUsuarios);
            DinamismoLink.aplicarEfecto(btnLinkSeccionProveedores);  
            DinamismoLink.aplicarEfecto(btnLinkSeccionCompras);
            DinamismoLink.aplicarEfecto(btnLinkSeccionReporte);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorHeader = new javax.swing.JPanel();
        tituloMenu = new javax.swing.JLabel();
        contenedorCuerpo = new javax.swing.JPanel();
        marginAutoLeft = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        contenedorContenido = new javax.swing.JPanel();
        menuSeccionInicio = new javax.swing.JPanel();
        btnLinkSeccionInicio = new javax.swing.JButton();
        menuSeccionUsuarios = new javax.swing.JPanel();
        btnLinkSeccionUsuarios = new javax.swing.JButton();
        menuSeccionProductos = new javax.swing.JPanel();
        btnLinkSeccionProductos = new javax.swing.JButton();
        menuSeccionProveedores = new javax.swing.JPanel();
        btnLinkSeccionProveedores = new javax.swing.JButton();
        menuSeccionClientes = new javax.swing.JPanel();
        btnLinkSeccionClientes = new javax.swing.JButton();
        menuSeccionCompras = new javax.swing.JPanel();
        btnLinkSeccionCompras = new javax.swing.JButton();
        menuSeccionVentas = new javax.swing.JPanel();
        btnLinkSeccionVentas = new javax.swing.JButton();
        menuSeccionInventario = new javax.swing.JPanel();
        btnLinkSeccionInventario = new javax.swing.JButton();
        menuSeccionReporte = new javax.swing.JPanel();
        btnLinkSeccionReporte = new javax.swing.JButton();
        marginAutoRight = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 650));
        setMinimumSize(new java.awt.Dimension(300, 600));
        setPreferredSize(new java.awt.Dimension(300, 650));
        setLayout(new java.awt.BorderLayout());

        contenedorHeader.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(22, 226, 230)), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
        contenedorHeader.setOpaque(false);
        contenedorHeader.setPreferredSize(new java.awt.Dimension(0, 70));
        contenedorHeader.setLayout(new java.awt.GridLayout(1, 1));

        tituloMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloMenu.setForeground(new java.awt.Color(17, 35, 85));
        tituloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMenu.setText("Menu");
        contenedorHeader.add(tituloMenu);

        add(contenedorHeader, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpo.setAlignmentX(0.0F);
        contenedorCuerpo.setOpaque(false);
        contenedorCuerpo.setLayout(new javax.swing.BoxLayout(contenedorCuerpo, javax.swing.BoxLayout.X_AXIS));
        contenedorCuerpo.add(marginAutoLeft);

        contenedorContenido.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        contenedorContenido.setAlignmentX(0.0F);
        contenedorContenido.setAlignmentY(0.0F);
        contenedorContenido.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        contenedorContenido.setMinimumSize(new java.awt.Dimension(200, 0));
        contenedorContenido.setOpaque(false);
        contenedorContenido.setPreferredSize(new java.awt.Dimension(200, 0));
        contenedorContenido.setLayout(new javax.swing.BoxLayout(contenedorContenido, javax.swing.BoxLayout.Y_AXIS));

        menuSeccionInicio.setOpaque(false);
        menuSeccionInicio.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionInicio.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionInicio.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/mdi--home.png"))); // NOI18N
        btnLinkSeccionInicio.setText("Inicio");
        btnLinkSeccionInicio.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionInicio.add(btnLinkSeccionInicio, gridBagConstraints);

        contenedorContenido.add(menuSeccionInicio);

        menuSeccionUsuarios.setOpaque(false);
        menuSeccionUsuarios.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionUsuarios.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/mdi--users.png"))); // NOI18N
        btnLinkSeccionUsuarios.setText("Usuarios");
        btnLinkSeccionUsuarios.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionUsuarios.add(btnLinkSeccionUsuarios, gridBagConstraints);

        contenedorContenido.add(menuSeccionUsuarios);

        menuSeccionProductos.setOpaque(false);
        menuSeccionProductos.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionProductos.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionProductos.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/mdi--bread.png"))); // NOI18N
        btnLinkSeccionProductos.setText("Productos");
        btnLinkSeccionProductos.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionProductos.add(btnLinkSeccionProductos, gridBagConstraints);

        contenedorContenido.add(menuSeccionProductos);

        menuSeccionProveedores.setOpaque(false);
        menuSeccionProveedores.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionProveedores.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionProveedores.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/clarity--building-line.png"))); // NOI18N
        btnLinkSeccionProveedores.setText("Proveedores");
        btnLinkSeccionProveedores.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionProveedores.add(btnLinkSeccionProveedores, gridBagConstraints);

        contenedorContenido.add(menuSeccionProveedores);

        menuSeccionClientes.setOpaque(false);
        menuSeccionClientes.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionClientes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionClientes.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/bxs--store.png"))); // NOI18N
        btnLinkSeccionClientes.setText("Clientes");
        btnLinkSeccionClientes.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionClientes.add(btnLinkSeccionClientes, gridBagConstraints);

        contenedorContenido.add(menuSeccionClientes);

        menuSeccionCompras.setOpaque(false);
        menuSeccionCompras.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionCompras.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionCompras.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/fa7-solid--bag-shopping.png"))); // NOI18N
        btnLinkSeccionCompras.setText("Compras");
        btnLinkSeccionCompras.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionCompras.add(btnLinkSeccionCompras, gridBagConstraints);

        contenedorContenido.add(menuSeccionCompras);

        menuSeccionVentas.setOpaque(false);
        menuSeccionVentas.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionVentas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionVentas.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/bi--cash-coin.png"))); // NOI18N
        btnLinkSeccionVentas.setText("Ventas");
        btnLinkSeccionVentas.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionVentas.add(btnLinkSeccionVentas, gridBagConstraints);

        contenedorContenido.add(menuSeccionVentas);

        menuSeccionInventario.setOpaque(false);
        menuSeccionInventario.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionInventario.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionInventario.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/mingcute--cube-fill.png"))); // NOI18N
        btnLinkSeccionInventario.setText("Inventario");
        btnLinkSeccionInventario.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionInventario.add(btnLinkSeccionInventario, gridBagConstraints);

        contenedorContenido.add(menuSeccionInventario);

        menuSeccionReporte.setOpaque(false);
        menuSeccionReporte.setLayout(new java.awt.GridBagLayout());

        btnLinkSeccionReporte.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLinkSeccionReporte.setForeground(new java.awt.Color(17, 35, 85));
        btnLinkSeccionReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/secciones/mdi--file-chart.png"))); // NOI18N
        btnLinkSeccionReporte.setText("Reporte");
        btnLinkSeccionReporte.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        menuSeccionReporte.add(btnLinkSeccionReporte, gridBagConstraints);

        contenedorContenido.add(menuSeccionReporte);

        contenedorCuerpo.add(contenedorContenido);
        contenedorCuerpo.add(marginAutoRight);

        add(contenedorCuerpo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // =======================================================
    // MÉTODOS PÚBLICOS PARA EL CONTROLADOR
    // =======================================================

    //Exponer los botones link 
    public JButton getBtnLinkSeccionInicio(){
        return btnLinkSeccionInicio;
    }
    
    public JButton getBtnLinkSeccionUsuarios(){
        return btnLinkSeccionUsuarios;
    }
    
    public JButton getBtnLinkSeccionProductos(){
        return btnLinkSeccionProductos;
    }
    
    public JButton getBtnLinkSeccionProveedores(){
        return btnLinkSeccionProveedores;
    }
    
    public JButton getBtnLinkSeccionClientes(){
        return btnLinkSeccionClientes;
    }
    
    public JButton getBtnLinkSeccionCompras(){
        return btnLinkSeccionCompras;
    }
    
    public JButton getBtnLinkSeccionVentas(){
        return btnLinkSeccionVentas;
    }
    
    public JButton getBtnLinkSeccionInventario(){
        return btnLinkSeccionInventario;
    }
    
    public JButton getBtnLinkSeccionReporte(){
        return btnLinkSeccionReporte;
    }
    
            
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLinkSeccionClientes;
    private javax.swing.JButton btnLinkSeccionCompras;
    private javax.swing.JButton btnLinkSeccionInicio;
    private javax.swing.JButton btnLinkSeccionInventario;
    private javax.swing.JButton btnLinkSeccionProductos;
    private javax.swing.JButton btnLinkSeccionProveedores;
    private javax.swing.JButton btnLinkSeccionReporte;
    private javax.swing.JButton btnLinkSeccionUsuarios;
    private javax.swing.JButton btnLinkSeccionVentas;
    private javax.swing.JPanel contenedorContenido;
    private javax.swing.JPanel contenedorCuerpo;
    private javax.swing.JPanel contenedorHeader;
    private javax.swing.Box.Filler marginAutoLeft;
    private javax.swing.Box.Filler marginAutoRight;
    private javax.swing.JPanel menuSeccionClientes;
    private javax.swing.JPanel menuSeccionCompras;
    private javax.swing.JPanel menuSeccionInicio;
    private javax.swing.JPanel menuSeccionInventario;
    private javax.swing.JPanel menuSeccionProductos;
    private javax.swing.JPanel menuSeccionProveedores;
    private javax.swing.JPanel menuSeccionReporte;
    private javax.swing.JPanel menuSeccionUsuarios;
    private javax.swing.JPanel menuSeccionVentas;
    private javax.swing.JLabel tituloMenu;
    // End of variables declaration//GEN-END:variables
}
