
package jafrinventarios.vistas.principal;

import javax.swing.JPanel;

/**
 *
 * @author JOHN FORERO
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
        
         // Asignar el icono personalizado de JAFR a la ventana
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jafrinventarios/recursos/imagenes/icono.png")));
        
        // Forzar que la ventana se abra maximizada ocupando toda la pantalla
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorFondo = new javax.swing.JPanel();
        marginLeftAuto = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        contenedorPrincipal = new javax.swing.JPanel();
        contenedorHeader = new javax.swing.JPanel();
        headerPanel = new jafrinventarios.vistas.principal.HeaderPanel();
        contenedorCentro = new javax.swing.JPanel();
        contenedorFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();
        marginRightAuto = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JAFR inventarios");
        setBackground(new java.awt.Color(205, 205, 205));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName("VentanaPrincipal"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        contenedorFondo.setBackground(new java.awt.Color(205, 205, 205));
        contenedorFondo.setLayout(new javax.swing.BoxLayout(contenedorFondo, javax.swing.BoxLayout.LINE_AXIS));

        marginLeftAuto.setOpaque(true);
        contenedorFondo.add(marginLeftAuto);

        contenedorPrincipal.setBackground(new java.awt.Color(205, 205, 205));
        contenedorPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        contenedorPrincipal.setMaximumSize(new java.awt.Dimension(1920, 32767));
        contenedorPrincipal.setMinimumSize(new java.awt.Dimension(1024, 0));
        contenedorPrincipal.setPreferredSize(new java.awt.Dimension(1920, 0));
        contenedorPrincipal.setLayout(new java.awt.BorderLayout());

        contenedorHeader.setMaximumSize(new java.awt.Dimension(32767, 70));
        contenedorHeader.setMinimumSize(new java.awt.Dimension(0, 60));
        contenedorHeader.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorHeader.setLayout(new java.awt.BorderLayout());
        contenedorHeader.add(headerPanel, java.awt.BorderLayout.CENTER);

        contenedorPrincipal.add(contenedorHeader, java.awt.BorderLayout.PAGE_START);

        contenedorCentro.setBackground(new java.awt.Color(205, 205, 205));
        contenedorCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));
        contenedorCentro.setLayout(new javax.swing.BoxLayout(contenedorCentro, javax.swing.BoxLayout.LINE_AXIS));
        contenedorPrincipal.add(contenedorCentro, java.awt.BorderLayout.CENTER);

        contenedorFooter.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFooter.setMaximumSize(new java.awt.Dimension(32767, 40));
        contenedorFooter.setMinimumSize(new java.awt.Dimension(259, 40));
        contenedorFooter.setPreferredSize(new java.awt.Dimension(1067, 40));
        contenedorFooter.setLayout(new java.awt.GridLayout(1, 1));

        lblFooter.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(33, 37, 41));
        lblFooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFooter.setText("© 2026 JAFR - Administra tu inventario. ");
        contenedorFooter.add(lblFooter);

        contenedorPrincipal.add(contenedorFooter, java.awt.BorderLayout.PAGE_END);

        contenedorFondo.add(contenedorPrincipal);

        marginRightAuto.setBackground(new java.awt.Color(205, 205, 205));
        contenedorFondo.add(marginRightAuto);

        getContentPane().add(contenedorFondo);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // =======================================================
    // MÉTODOS PÚBLICOS PARA EL CONTROLADOR
    // =======================================================
    
    public HeaderPanel getHeaderPanel(){
        return headerPanel;
    }
    
    public JPanel getContenedorPrincipal(){
        return contenedorPrincipal;
    }
    
    public void agregarPanelModulo(JPanel moduloPanel){
        contenedorCentro.removeAll();
        contenedorCentro.add(moduloPanel);
        contenedorPrincipal.revalidate();
        contenedorPrincipal.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorCentro;
    private javax.swing.JPanel contenedorFondo;
    private javax.swing.JPanel contenedorFooter;
    private javax.swing.JPanel contenedorHeader;
    private javax.swing.JPanel contenedorPrincipal;
    private jafrinventarios.vistas.principal.HeaderPanel headerPanel;
    private javax.swing.JLabel lblFooter;
    private javax.swing.Box.Filler marginLeftAuto;
    private javax.swing.Box.Filler marginRightAuto;
    // End of variables declaration//GEN-END:variables
}
