
package jafrinventarios.vistas.compras.dialogoCompra;

import jafrinventarios.vistas.utilidades.componentes.DinamismoLink;
import jafrinventarios.vistas.utilidades.dialogos.DialogoBaseConSombra;
import jafrinventarios.vistas.utilidades.formularios.GestorFormulario;
import java.awt.Window;
import javax.swing.JButton;

/**
 *
 * @author JOHN FORERO
 */
public class DialogoFormularioCompra extends DialogoBaseConSombra {

    /*
      Objeto enum auxiliar para mejorar la legibilidad del codigo
    */
    public static enum TipoDialogo {
        EDITAR_COMPRA,
        CREAR_NUEVA_COMPRA
    }
    
    private GestorFormulario formularioDatosCompra;
    
    /*
    ============================================================================
                            CONSTRUCTOR PUBLICO
    ============================================================================
    El controlador ofrece metodos estaticos para poder establecer con el mismo
    cuales son los paremetros que sean acorde a la intencion del metodo estatico.
    */
    public DialogoFormularioCompra( Window parent, TipoDialogo tipoDialogo) {
        super(parent);
        initComponents();
        
        if(tipoDialogo == TipoDialogo.CREAR_NUEVA_COMPRA){
            tituloFormulario.setText("Crear compra");
            btnEnviarFormulario.setText("Crear Compra");
            /*
            Para el dialogo crear nuevo registro se ocultan algunos elementos y
            para mantener un diseño uniforme se realizan los siguientes ajustes.
            */
            contenedorDatosGenerales.remove(contenedorIDComprayUsuario);
            contenedorDatosGenerales.setPreferredSize(new java.awt.Dimension(37200, 45));
            contenedorDatosGenerales.setLayout(new java.awt.GridLayout(1, 1));
            btnLinkEliminarRegistro.setVisible(false);
            
        }
        
        if(tipoDialogo == TipoDialogo.EDITAR_COMPRA){
            DinamismoLink.aplicarEfecto(btnLinkEliminarRegistro);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorFormulario = new javax.swing.JPanel();
        contenedorTituloFormulario = new javax.swing.JPanel();
        margin_left = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        tituloFormulario = new javax.swing.JLabel();
        contenedorBtnCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        contenedorCuerpoFormulario = new javax.swing.JPanel();
        contenedorDatosGenerales = new javax.swing.JPanel();
        contenedorIDComprayUsuario = new javax.swing.JPanel();
        contenedorIDCompra = new javax.swing.JPanel();
        lblTituloId = new javax.swing.JLabel();
        lblDatoId = new javax.swing.JLabel();
        contenedorUsuario = new javax.swing.JPanel();
        lblTituloUsuario = new javax.swing.JLabel();
        lblDatoUsuario = new javax.swing.JLabel();
        contenedorProveedorYFecha = new javax.swing.JPanel();
        contenedorProveedor = new javax.swing.JPanel();
        lblTituloProveedor = new javax.swing.JLabel();
        comboBoxProveedores = new javax.swing.JComboBox<>();
        contenedorFecha = new javax.swing.JPanel();
        lblTituloFecha = new javax.swing.JLabel();
        selectorFechaYHora = new com.github.lgooddatepicker.components.DateTimePicker();
        contenedorGlobalDetalles = new javax.swing.JPanel();
        contenedorHeaderDetalles = new javax.swing.JPanel();
        lblTituloDetalles = new javax.swing.JLabel();
        contenedorCuerpoDetalles = new javax.swing.JPanel();
        contenedorTitulosTabla = new javax.swing.JPanel();
        lblTituloItem = new javax.swing.JLabel();
        lblTituloProducto = new javax.swing.JLabel();
        lblTituloCantidad = new javax.swing.JLabel();
        lblTituloPrecioUnitario = new javax.swing.JLabel();
        lblTituloPrecioTotal = new javax.swing.JLabel();
        lblTituloEliminar = new javax.swing.JLabel();
        panelScrollDetalles = new javax.swing.JScrollPane();
        contenedorDetalles = new javax.swing.JPanel();
        contenedorBtnAgregarProducto = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JButton();
        contenedorTotal = new javax.swing.JPanel();
        lblTituloTotal = new javax.swing.JLabel();
        lblDatoTotal = new javax.swing.JLabel();
        contenedorBotonesCRUD = new javax.swing.JPanel();
        btnEnviarFormulario = new javax.swing.JButton();
        btnLinkEliminarRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(950, 700));
        setName("dialogoCompra"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 700));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        contenedorFormulario.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFormulario.setLayout(new java.awt.BorderLayout());

        contenedorTituloFormulario.setMinimumSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setPreferredSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setOpaque(false);
        contenedorTituloFormulario.setLayout(new java.awt.BorderLayout());
        contenedorTituloFormulario.add(margin_left, java.awt.BorderLayout.WEST);

        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Editar Compra");
        tituloFormulario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tituloFormulario.setAlignmentX(0.5F);
        tituloFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(17, 35, 85));
        tituloFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setVerifyInputWhenFocusTarget(false);
        contenedorTituloFormulario.add(tituloFormulario, java.awt.BorderLayout.CENTER);

        contenedorBtnCerrar.setMinimumSize(new java.awt.Dimension(40, 0));
        contenedorBtnCerrar.setOpaque(false);
        contenedorBtnCerrar.setPreferredSize(new java.awt.Dimension(40, 0));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        contenedorBtnCerrar.setLayout(flowLayout1);

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(17, 35, 85));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/carbon--close-filled.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusCycleRoot(true);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setPreferredSize(new java.awt.Dimension(30, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarcerrarDialogo(evt);
            }
        });
        contenedorBtnCerrar.add(btnCerrar);

        contenedorTituloFormulario.add(contenedorBtnCerrar, java.awt.BorderLayout.EAST);

        contenedorFormulario.add(contenedorTituloFormulario, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpoFormulario.setBackground(new java.awt.Color(255, 255, 255));
        contenedorCuerpoFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 0, 50));
        contenedorCuerpoFormulario.setPreferredSize(new java.awt.Dimension(600, 439));
        contenedorCuerpoFormulario.setLayout(new java.awt.BorderLayout());

        contenedorDatosGenerales.setBackground(new java.awt.Color(255, 255, 255));
        contenedorDatosGenerales.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        contenedorDatosGenerales.setPreferredSize(new java.awt.Dimension(600, 90));
        contenedorDatosGenerales.setLayout(new java.awt.GridLayout(2, 1));

        contenedorIDComprayUsuario.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorIDComprayUsuario.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorIDComprayUsuario.setOpaque(false);
        contenedorIDComprayUsuario.setLayout(new java.awt.GridBagLayout());

        contenedorIDCompra.setOpaque(false);
        contenedorIDCompra.setLayout(new java.awt.GridBagLayout());

        lblTituloId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTituloId.setText("Id :");
        lblTituloId.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloId.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloId.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloId.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorIDCompra.add(lblTituloId, gridBagConstraints);

        lblDatoId.setText("001");
        lblDatoId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoId.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoId.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoId.setName(""); // NOI18N
        lblDatoId.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorIDCompra.add(lblDatoId, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorIDComprayUsuario.add(contenedorIDCompra, gridBagConstraints);

        contenedorUsuario.setOpaque(false);
        contenedorUsuario.setLayout(new java.awt.GridBagLayout());

        lblTituloUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTituloUsuario.setText("Usuario :");
        lblTituloUsuario.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloUsuario.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloUsuario.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorUsuario.add(lblTituloUsuario, gridBagConstraints);

        lblDatoUsuario.setText("John Forero");
        lblDatoUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoUsuario.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoUsuario.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoUsuario.setPreferredSize(new java.awt.Dimension(0, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        contenedorUsuario.add(lblDatoUsuario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.5;
        gridBagConstraints.weighty = 1.0;
        contenedorIDComprayUsuario.add(contenedorUsuario, gridBagConstraints);

        contenedorDatosGenerales.add(contenedorIDComprayUsuario);

        contenedorProveedorYFecha.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorProveedorYFecha.setOpaque(false);
        contenedorProveedorYFecha.setLayout(new java.awt.GridBagLayout());

        contenedorProveedor.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorProveedor.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorProveedor.setOpaque(false);
        contenedorProveedor.setLayout(new java.awt.GridBagLayout());

        lblTituloProveedor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTituloProveedor.setText("Proveedor :");
        lblTituloProveedor.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloProveedor.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloProveedor.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorProveedor.add(lblTituloProveedor, gridBagConstraints);

        comboBoxProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Proveedor" }));
        comboBoxProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxProveedores.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxProveedores.setMinimumSize(new java.awt.Dimension(0, 0));
        comboBoxProveedores.setName("proveedor"); // NOI18N
        comboBoxProveedores.setPreferredSize(new java.awt.Dimension(0, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorProveedor.add(comboBoxProveedores, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorProveedorYFecha.add(contenedorProveedor, gridBagConstraints);

        contenedorFecha.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorFecha.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorFecha.setOpaque(false);
        contenedorFecha.setLayout(new java.awt.GridBagLayout());

        lblTituloFecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloFecha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTituloFecha.setText("Fecha :");
        lblTituloFecha.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloFecha.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloFecha.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorFecha.add(lblTituloFecha, gridBagConstraints);

        selectorFechaYHora.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        selectorFechaYHora.setMinimumSize(new java.awt.Dimension(0, 0));
        selectorFechaYHora.setPreferredSize(new java.awt.Dimension(0, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        contenedorFecha.add(selectorFechaYHora, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.5;
        gridBagConstraints.weighty = 1.0;
        contenedorProveedorYFecha.add(contenedorFecha, gridBagConstraints);

        contenedorDatosGenerales.add(contenedorProveedorYFecha);

        contenedorCuerpoFormulario.add(contenedorDatosGenerales, java.awt.BorderLayout.PAGE_START);

        contenedorGlobalDetalles.setBackground(new java.awt.Color(255, 255, 255));
        contenedorGlobalDetalles.setLayout(new java.awt.BorderLayout());

        contenedorHeaderDetalles.setBackground(new java.awt.Color(255, 255, 255));
        contenedorHeaderDetalles.setPreferredSize(new java.awt.Dimension(600, 40));
        contenedorHeaderDetalles.setOpaque(false);
        contenedorHeaderDetalles.setLayout(new javax.swing.BoxLayout(contenedorHeaderDetalles, javax.swing.BoxLayout.LINE_AXIS));

        lblTituloDetalles.setText("Detalles");
        lblTituloDetalles.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTituloDetalles.setAlignmentX(0.5F);
        lblTituloDetalles.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloDetalles.setMaximumSize(new java.awt.Dimension(37270, 36));
        lblTituloDetalles.setMinimumSize(new java.awt.Dimension(400, 36));
        lblTituloDetalles.setPreferredSize(new java.awt.Dimension(400, 36));
        contenedorHeaderDetalles.add(lblTituloDetalles);

        contenedorGlobalDetalles.add(contenedorHeaderDetalles, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpoDetalles.setLayout(new java.awt.BorderLayout());

        contenedorTitulosTabla.setBackground(new java.awt.Color(255, 255, 255));
        contenedorTitulosTabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        contenedorTitulosTabla.setMaximumSize(new java.awt.Dimension(32767, 50));
        contenedorTitulosTabla.setMinimumSize(new java.awt.Dimension(41, 50));
        contenedorTitulosTabla.setPreferredSize(new java.awt.Dimension(0, 50));
        contenedorTitulosTabla.setLayout(new java.awt.GridBagLayout());

        lblTituloItem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloItem.setText("Item");
        lblTituloItem.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloItem.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloItem.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosTabla.add(lblTituloItem, gridBagConstraints);

        lblTituloProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloProducto.setText("Producto");
        lblTituloProducto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloProducto.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloProducto.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloProducto.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosTabla.add(lblTituloProducto, gridBagConstraints);

        lblTituloCantidad.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCantidad.setText("Cantidad");
        lblTituloCantidad.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloCantidad.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloCantidad.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosTabla.add(lblTituloCantidad, gridBagConstraints);

        lblTituloPrecioUnitario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloPrecioUnitario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPrecioUnitario.setText("Precio Unitario");
        lblTituloPrecioUnitario.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloPrecioUnitario.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloPrecioUnitario.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosTabla.add(lblTituloPrecioUnitario, gridBagConstraints);

        lblTituloPrecioTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloPrecioTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPrecioTotal.setText("Total");
        lblTituloPrecioTotal.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloPrecioTotal.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloPrecioTotal.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosTabla.add(lblTituloPrecioTotal, gridBagConstraints);

        lblTituloEliminar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloEliminar.setText("Eliminar");
        lblTituloEliminar.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloEliminar.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloEliminar.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        contenedorTitulosTabla.add(lblTituloEliminar, gridBagConstraints);

        contenedorCuerpoDetalles.add(contenedorTitulosTabla, java.awt.BorderLayout.PAGE_START);

        panelScrollDetalles.setBackground(new java.awt.Color(255, 255, 255));
        panelScrollDetalles.setColumnHeaderView(contenedorTitulosTabla);

        contenedorDetalles.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenedorDetallesLayout = new javax.swing.GroupLayout(contenedorDetalles);
        contenedorDetalles.setLayout(contenedorDetallesLayout);
        contenedorDetallesLayout.setHorizontalGroup(
            contenedorDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        contenedorDetallesLayout.setVerticalGroup(
            contenedorDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        panelScrollDetalles.setViewportView(contenedorDetalles);

        contenedorCuerpoDetalles.add(panelScrollDetalles, java.awt.BorderLayout.CENTER);

        contenedorGlobalDetalles.add(contenedorCuerpoDetalles, java.awt.BorderLayout.CENTER);

        contenedorBtnAgregarProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        contenedorBtnAgregarProducto.setPreferredSize(new java.awt.Dimension(0, 50));
        contenedorBtnAgregarProducto.setOpaque(false);
        contenedorBtnAgregarProducto.setLayout(new javax.swing.BoxLayout(contenedorBtnAgregarProducto, javax.swing.BoxLayout.LINE_AXIS));

        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.setBackground(new java.awt.Color(30, 166, 177));
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnAgregarProducto.setMaximumSize(new java.awt.Dimension(180, 38));
        btnAgregarProducto.setMinimumSize(new java.awt.Dimension(180, 38));
        btnAgregarProducto.setPreferredSize(new java.awt.Dimension(180, 38));
        btnAgregarProducto.setToolTipText("");
        contenedorBtnAgregarProducto.add(btnAgregarProducto);

        contenedorGlobalDetalles.add(contenedorBtnAgregarProducto, java.awt.BorderLayout.PAGE_END);

        contenedorCuerpoFormulario.add(contenedorGlobalDetalles, java.awt.BorderLayout.CENTER);

        contenedorTotal.setBackground(new java.awt.Color(255, 255, 255));
        contenedorTotal.setMinimumSize(new java.awt.Dimension(41, 100));
        contenedorTotal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lblTituloTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloTotal.setText("Total :");
        lblTituloTotal.setPreferredSize(new java.awt.Dimension(48, 50));
        contenedorTotal.add(lblTituloTotal);

        lblDatoTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoTotal.setText("$ 000000.00");
        lblDatoTotal.setToolTipText("");
        lblDatoTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 0));
        lblDatoTotal.setPreferredSize(new java.awt.Dimension(300, 50));
        contenedorTotal.add(lblDatoTotal);

        contenedorCuerpoFormulario.add(contenedorTotal, java.awt.BorderLayout.PAGE_END);

        contenedorFormulario.add(contenedorCuerpoFormulario, java.awt.BorderLayout.CENTER);

        contenedorBotonesCRUD.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 10, 40));
        contenedorBotonesCRUD.setMinimumSize(new java.awt.Dimension(287, 60));
        contenedorBotonesCRUD.setPreferredSize(new java.awt.Dimension(500, 90));
        contenedorBotonesCRUD.setOpaque(false);
        contenedorBotonesCRUD.setLayout(new java.awt.GridBagLayout());

        btnEnviarFormulario.setText("Actualizar");
        btnEnviarFormulario.setBackground(new java.awt.Color(30, 166, 177));
        btnEnviarFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarFormulario.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEnviarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarFormulario.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnEnviarFormulario.setMaximumSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setMinimumSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setPreferredSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotonesCRUD.add(btnEnviarFormulario, gridBagConstraints);

        btnLinkEliminarRegistro.setText("Eliminar Compra");
        btnLinkEliminarRegistro.setAlignmentX(0.5F);
        btnLinkEliminarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnLinkEliminarRegistro.setForeground(new java.awt.Color(200, 0, 0));
        btnLinkEliminarRegistro.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotonesCRUD.add(btnLinkEliminarRegistro, gridBagConstraints);

        contenedorFormulario.add(contenedorBotonesCRUD, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(contenedorFormulario);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarcerrarDialogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarcerrarDialogo
        this.dispose();
    }//GEN-LAST:event_btnCerrarcerrarDialogo

    
    /*
    ============================================================================
                      MÉTODOS PÚBLICOS PARA EL CONTROLADOR
    ============================================================================
    */
    
    public void setIdCompra( Integer id ){
        lblDatoId.setText( Integer.toString(id) );
    }
    
    public void setAliasUsuario( String aliasUsuario ){
        lblDatoUsuario.setText( aliasUsuario );
    }
    
    
    //Exponer botones
    public JButton getBtnAgregarProducto(){
        return btnAgregarProducto;
    }
    public JButton getBtnEnviarFormulario(){
        return btnEnviarFormulario;
    }
    public JButton getBtnLinkEliminarRegistro(){
        return btnLinkEliminarRegistro;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviarFormulario;
    private javax.swing.JButton btnLinkEliminarRegistro;
    private javax.swing.JComboBox<String> comboBoxProveedores;
    private javax.swing.JPanel contenedorBotonesCRUD;
    private javax.swing.JPanel contenedorBtnAgregarProducto;
    private javax.swing.JPanel contenedorBtnCerrar;
    private javax.swing.JPanel contenedorCuerpoDetalles;
    private javax.swing.JPanel contenedorCuerpoFormulario;
    private javax.swing.JPanel contenedorDatosGenerales;
    private javax.swing.JPanel contenedorDetalles;
    private javax.swing.JPanel contenedorFecha;
    private javax.swing.JPanel contenedorFormulario;
    private javax.swing.JPanel contenedorGlobalDetalles;
    private javax.swing.JPanel contenedorHeaderDetalles;
    private javax.swing.JPanel contenedorIDCompra;
    private javax.swing.JPanel contenedorIDComprayUsuario;
    private javax.swing.JPanel contenedorProveedor;
    private javax.swing.JPanel contenedorProveedorYFecha;
    private javax.swing.JPanel contenedorTituloFormulario;
    private javax.swing.JPanel contenedorTitulosTabla;
    private javax.swing.JPanel contenedorTotal;
    private javax.swing.JPanel contenedorUsuario;
    private javax.swing.JLabel lblDatoId;
    private javax.swing.JLabel lblDatoTotal;
    private javax.swing.JLabel lblDatoUsuario;
    private javax.swing.JLabel lblTituloCantidad;
    private javax.swing.JLabel lblTituloDetalles;
    private javax.swing.JLabel lblTituloEliminar;
    private javax.swing.JLabel lblTituloFecha;
    private javax.swing.JLabel lblTituloId;
    private javax.swing.JLabel lblTituloItem;
    private javax.swing.JLabel lblTituloPrecioTotal;
    private javax.swing.JLabel lblTituloPrecioUnitario;
    private javax.swing.JLabel lblTituloProducto;
    private javax.swing.JLabel lblTituloProveedor;
    private javax.swing.JLabel lblTituloTotal;
    private javax.swing.JLabel lblTituloUsuario;
    private javax.swing.Box.Filler margin_left;
    private javax.swing.JScrollPane panelScrollDetalles;
    private com.github.lgooddatepicker.components.DateTimePicker selectorFechaYHora;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
