/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.compras.dialogoCompra;

import jafrinventarios.vistas.utilidades.dialogos.DialogoBaseConSombra;
import java.awt.Window;

/**
 *
 * @author JOHN FORERO
 */
public class DialogoFormularioCompra extends DialogoBaseConSombra {

    /**
     * Creates new form DialogoFormularioCompra
     */
    public DialogoFormularioCompra( Window parent, boolean modal) {
        super(parent);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorFormulario = new javax.swing.JPanel();
        contenedorTituloFormulario = new javax.swing.JPanel();
        margin_left = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        tituloFormulario = new javax.swing.JLabel();
        contenedorBtnCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        contenedorCuerpoFormulario = new javax.swing.JPanel();
        contenedorDatosGenerales = new javax.swing.JPanel();
        contenedorIDComprayUsuario = new javax.swing.JPanel();
        contenedorIDCompra = new javax.swing.JPanel();
        lblTituloId = new javax.swing.JLabel();
        lblDatoId = new javax.swing.JLabel();
        contenedorUsuario = new javax.swing.JPanel();
        lblTituloUsuario = new javax.swing.JLabel();
        lblDatoUsuario = new javax.swing.JLabel();
        contenedorProveedorYFecha = new javax.swing.JPanel();
        contenedorProveedor = new javax.swing.JPanel();
        lblTituloProveedor = new javax.swing.JLabel();
        comboBoxProveedores = new javax.swing.JComboBox<>();
        contenedorFecha = new javax.swing.JPanel();
        lblTituloFecha = new javax.swing.JLabel();
        comboBoxFecha = new javax.swing.JComboBox<>();
        contenedorGlobalDetalles = new javax.swing.JPanel();
        contenedorTotal = new javax.swing.JPanel();
        lblTituloTotal = new javax.swing.JLabel();
        lblDatoTotal = new javax.swing.JLabel();
        contenedorBotones = new javax.swing.JPanel();
        btnEnviarFormulario = new javax.swing.JButton();
        btnLinkEliminarRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("dialogoCompra"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        contenedorFormulario.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFormulario.setLayout(new java.awt.BorderLayout());

        contenedorTituloFormulario.setMinimumSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setOpaque(false);
        contenedorTituloFormulario.setPreferredSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setLayout(new java.awt.BorderLayout());
        contenedorTituloFormulario.add(margin_left, java.awt.BorderLayout.WEST);

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(17, 35, 85));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Editar Compra");
        tituloFormulario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tituloFormulario.setAlignmentX(0.5F);
        tituloFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        tituloFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setVerifyInputWhenFocusTarget(false);
        contenedorTituloFormulario.add(tituloFormulario, java.awt.BorderLayout.CENTER);

        contenedorBtnCerrar.setMinimumSize(new java.awt.Dimension(40, 0));
        contenedorBtnCerrar.setOpaque(false);
        contenedorBtnCerrar.setPreferredSize(new java.awt.Dimension(40, 0));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        contenedorBtnCerrar.setLayout(flowLayout1);

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(17, 35, 85));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/carbon--close-filled.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusCycleRoot(true);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setPreferredSize(new java.awt.Dimension(30, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarcerrarDialogo(evt);
            }
        });
        contenedorBtnCerrar.add(btnCerrar);

        contenedorTituloFormulario.add(contenedorBtnCerrar, java.awt.BorderLayout.EAST);

        contenedorFormulario.add(contenedorTituloFormulario, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpoFormulario.setBackground(new java.awt.Color(255, 255, 255));
        contenedorCuerpoFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 50));
        contenedorCuerpoFormulario.setPreferredSize(new java.awt.Dimension(600, 439));
        contenedorCuerpoFormulario.setLayout(new java.awt.BorderLayout());

        contenedorDatosGenerales.setBackground(new java.awt.Color(255, 255, 255));
        contenedorDatosGenerales.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        contenedorDatosGenerales.setPreferredSize(new java.awt.Dimension(600, 90));
        contenedorDatosGenerales.setLayout(new java.awt.GridLayout(2, 1));

        contenedorIDComprayUsuario.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorIDComprayUsuario.setOpaque(false);
        contenedorIDComprayUsuario.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorIDComprayUsuario.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        contenedorIDCompra.setOpaque(false);
        contenedorIDCompra.setLayout(new java.awt.GridBagLayout());

        lblTituloId.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTituloId.setText("Id :");
        lblTituloId.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloId.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloId.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorIDCompra.add(lblTituloId, gridBagConstraints);

        lblDatoId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoId.setText("001");
        lblDatoId.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoId.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoId.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorIDCompra.add(lblDatoId, gridBagConstraints);

        contenedorIDComprayUsuario.add(contenedorIDCompra);

        contenedorUsuario.setOpaque(false);
        contenedorUsuario.setLayout(new java.awt.GridBagLayout());

        lblTituloUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTituloUsuario.setText("Usuario :");
        lblTituloUsuario.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloUsuario.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloUsuario.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorUsuario.add(lblTituloUsuario, gridBagConstraints);

        lblDatoUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoUsuario.setText("John Forero");
        lblDatoUsuario.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoUsuario.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoUsuario.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorUsuario.add(lblDatoUsuario, gridBagConstraints);

        contenedorIDComprayUsuario.add(contenedorUsuario);

        contenedorDatosGenerales.add(contenedorIDComprayUsuario);

        contenedorProveedorYFecha.setOpaque(false);
        contenedorProveedorYFecha.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorProveedorYFecha.setLayout(new java.awt.GridLayout(1, 2));

        contenedorProveedor.setOpaque(false);
        contenedorProveedor.setLayout(new java.awt.GridBagLayout());

        lblTituloProveedor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTituloProveedor.setText("Proveedor :");
        lblTituloProveedor.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloProveedor.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloProveedor.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorProveedor.add(lblTituloProveedor, gridBagConstraints);

        comboBoxProveedores.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Proveedor" }));
        comboBoxProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxProveedores.setMinimumSize(new java.awt.Dimension(0, 0));
        comboBoxProveedores.setName("proveedor"); // NOI18N
        comboBoxProveedores.setPreferredSize(new java.awt.Dimension(0, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorProveedor.add(comboBoxProveedores, gridBagConstraints);

        contenedorProveedorYFecha.add(contenedorProveedor);

        contenedorFecha.setOpaque(false);
        contenedorFecha.setLayout(new java.awt.GridBagLayout());

        lblTituloFecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloFecha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTituloFecha.setText("Fecha :");
        lblTituloFecha.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloFecha.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloFecha.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorFecha.add(lblTituloFecha, gridBagConstraints);

        comboBoxFecha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar fecha" }));
        comboBoxFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxFecha.setMinimumSize(new java.awt.Dimension(0, 0));
        comboBoxFecha.setName("proveedor"); // NOI18N
        comboBoxFecha.setPreferredSize(new java.awt.Dimension(0, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorFecha.add(comboBoxFecha, gridBagConstraints);

        contenedorProveedorYFecha.add(contenedorFecha);

        contenedorDatosGenerales.add(contenedorProveedorYFecha);

        contenedorCuerpoFormulario.add(contenedorDatosGenerales, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout contenedorGlobalDetallesLayout = new javax.swing.GroupLayout(contenedorGlobalDetalles);
        contenedorGlobalDetalles.setLayout(contenedorGlobalDetallesLayout);
        contenedorGlobalDetallesLayout.setHorizontalGroup(
            contenedorGlobalDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        contenedorGlobalDetallesLayout.setVerticalGroup(
            contenedorGlobalDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        contenedorCuerpoFormulario.add(contenedorGlobalDetalles, java.awt.BorderLayout.CENTER);

        contenedorTotal.setBackground(new java.awt.Color(255, 255, 255));
        contenedorTotal.setMinimumSize(new java.awt.Dimension(41, 100));
        contenedorTotal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lblTituloTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloTotal.setText("Total :");
        lblTituloTotal.setPreferredSize(new java.awt.Dimension(48, 50));
        contenedorTotal.add(lblTituloTotal);

        lblDatoTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoTotal.setText("$ 000000.00");
        lblDatoTotal.setToolTipText("");
        lblDatoTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 0));
        lblDatoTotal.setPreferredSize(new java.awt.Dimension(300, 50));
        contenedorTotal.add(lblDatoTotal);

        contenedorCuerpoFormulario.add(contenedorTotal, java.awt.BorderLayout.PAGE_END);

        contenedorFormulario.add(contenedorCuerpoFormulario, java.awt.BorderLayout.CENTER);

        contenedorBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 10, 40));
        contenedorBotones.setMinimumSize(new java.awt.Dimension(287, 60));
        contenedorBotones.setOpaque(false);
        contenedorBotones.setPreferredSize(new java.awt.Dimension(500, 130));
        contenedorBotones.setLayout(new java.awt.GridBagLayout());

        btnEnviarFormulario.setBackground(new java.awt.Color(30, 166, 177));
        btnEnviarFormulario.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEnviarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarFormulario.setText("Actualizar");
        btnEnviarFormulario.setToolTipText("");
        btnEnviarFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarFormulario.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnEnviarFormulario.setMaximumSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setMinimumSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotones.add(btnEnviarFormulario, gridBagConstraints);

        btnLinkEliminarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnLinkEliminarRegistro.setForeground(new java.awt.Color(200, 0, 0));
        btnLinkEliminarRegistro.setText("Eliminar Compra");
        btnLinkEliminarRegistro.setAlignmentX(0.5F);
        btnLinkEliminarRegistro.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotones.add(btnLinkEliminarRegistro, gridBagConstraints);

        contenedorFormulario.add(contenedorBotones, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(contenedorFormulario);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarcerrarDialogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarcerrarDialogo
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarcerrarDialogo



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviarFormulario;
    private javax.swing.JButton btnLinkEliminarRegistro;
    private javax.swing.JComboBox<String> comboBoxFecha;
    private javax.swing.JComboBox<String> comboBoxProveedores;
    private javax.swing.JPanel contenedorBotones;
    private javax.swing.JPanel contenedorBtnCerrar;
    private javax.swing.JPanel contenedorCuerpoFormulario;
    private javax.swing.JPanel contenedorDatosGenerales;
    private javax.swing.JPanel contenedorFecha;
    private javax.swing.JPanel contenedorFormulario;
    private javax.swing.JPanel contenedorGlobalDetalles;
    private javax.swing.JPanel contenedorIDCompra;
    private javax.swing.JPanel contenedorIDComprayUsuario;
    private javax.swing.JPanel contenedorProveedor;
    private javax.swing.JPanel contenedorProveedorYFecha;
    private javax.swing.JPanel contenedorTituloFormulario;
    private javax.swing.JPanel contenedorTotal;
    private javax.swing.JPanel contenedorUsuario;
    private javax.swing.JLabel lblDatoId;
    private javax.swing.JLabel lblDatoTotal;
    private javax.swing.JLabel lblDatoUsuario;
    private javax.swing.JLabel lblTituloFecha;
    private javax.swing.JLabel lblTituloId;
    private javax.swing.JLabel lblTituloProveedor;
    private javax.swing.JLabel lblTituloTotal;
    private javax.swing.JLabel lblTituloUsuario;
    private javax.swing.Box.Filler margin_left;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
