
package jafrinventarios.vistas.ventas;

import jafrinventarios.vistas.utilidades.componentes.EfectoHoverPanel;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author JOHN FORERO
 */
public class FilaTablaVentas extends javax.swing.JPanel {

    /**
     * Creates new form FilaTablaUsuarios
     */
    public FilaTablaVentas() {
        initComponents();
        
        EfectoHoverPanel.aplicarEfecto(contenedorDatosGenerales);
        contenedorGlobalDetallesVenta.setVisible(false);
        redibujarPanel(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorFila = new javax.swing.JPanel();
        contenedorDatosGenerales = new javax.swing.JPanel();
        lblDatoId = new javax.swing.JLabel();
        lblDatoCliente = new javax.swing.JLabel();
        lblDatoFecha = new javax.swing.JLabel();
        lblDatoTotal = new javax.swing.JLabel();
        lblDatoAliasUsuario = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnVerDetalles = new javax.swing.JButton();
        contenedorGlobalDetallesVenta = new javax.swing.JPanel();
        contenedorTituloDetallesVenta = new javax.swing.JPanel();
        lblTituloDetallesVenta = new javax.swing.JLabel();
        contenedorTitulosDetalles = new javax.swing.JPanel();
        lblTituloItem = new javax.swing.JLabel();
        lblTituloNombreProducto = new javax.swing.JLabel();
        lblTituloCantidadProducto = new javax.swing.JLabel();
        lblTituloPrecioUnitario = new javax.swing.JLabel();
        lblTituloTotal = new javax.swing.JLabel();
        contenedorDetallesVenta = new javax.swing.JPanel();

        setBackground(new java.awt.Color(205, 205, 205));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        contenedorFila.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFila.setLayout(new java.awt.BorderLayout());

        contenedorDatosGenerales.setBackground(new java.awt.Color(255, 255, 255));
        contenedorDatosGenerales.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(222, 226, 230)));
        contenedorDatosGenerales.setMaximumSize(new java.awt.Dimension(32767, 50));
        contenedorDatosGenerales.setMinimumSize(new java.awt.Dimension(41, 50));
        contenedorDatosGenerales.setPreferredSize(new java.awt.Dimension(0, 50));
        contenedorDatosGenerales.setLayout(new java.awt.GridBagLayout());

        lblDatoId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoId.setText("Id");
        lblDatoId.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoId.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoId.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatosGenerales.add(lblDatoId, gridBagConstraints);

        lblDatoCliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoCliente.setText("Cliente");
        lblDatoCliente.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoCliente.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoCliente.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatosGenerales.add(lblDatoCliente, gridBagConstraints);

        lblDatoFecha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoFecha.setText("Fecha");
        lblDatoFecha.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoFecha.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoFecha.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatosGenerales.add(lblDatoFecha, gridBagConstraints);

        lblDatoTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoTotal.setText("Total");
        lblDatoTotal.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoTotal.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoTotal.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatosGenerales.add(lblDatoTotal, gridBagConstraints);

        lblDatoAliasUsuario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoAliasUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoAliasUsuario.setText("Usuario");
        lblDatoAliasUsuario.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoAliasUsuario.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoAliasUsuario.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatosGenerales.add(lblDatoAliasUsuario, gridBagConstraints);

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(17, 35, 85));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/boxicons--edit-filled.png"))); // NOI18N
        btnEditar.setAlignmentX(0.5F);
        btnEditar.setBorderPainted(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setIconTextGap(0);
        btnEditar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEditar.setMaximumSize(new java.awt.Dimension(0, 0));
        btnEditar.setMinimumSize(new java.awt.Dimension(0, 0));
        btnEditar.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        contenedorDatosGenerales.add(btnEditar, gridBagConstraints);

        btnVerDetalles.setBackground(new java.awt.Color(255, 255, 255));
        btnVerDetalles.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVerDetalles.setForeground(new java.awt.Color(17, 35, 85));
        btnVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/pixel--chevron-down-solid.png"))); // NOI18N
        btnVerDetalles.setAlignmentX(0.5F);
        btnVerDetalles.setBorderPainted(false);
        btnVerDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerDetalles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerDetalles.setIconTextGap(0);
        btnVerDetalles.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVerDetalles.setMaximumSize(new java.awt.Dimension(0, 0));
        btnVerDetalles.setMinimumSize(new java.awt.Dimension(0, 0));
        btnVerDetalles.setPreferredSize(new java.awt.Dimension(0, 0));
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        contenedorDatosGenerales.add(btnVerDetalles, gridBagConstraints);

        contenedorFila.add(contenedorDatosGenerales, java.awt.BorderLayout.PAGE_START);

        contenedorGlobalDetallesVenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 20, 50));
        contenedorGlobalDetallesVenta.setOpaque(false);
        contenedorGlobalDetallesVenta.setLayout(new java.awt.BorderLayout());

        contenedorTituloDetallesVenta.setBackground(new java.awt.Color(255, 255, 255));
        contenedorTituloDetallesVenta.setMaximumSize(new java.awt.Dimension(32767, 80));
        contenedorTituloDetallesVenta.setMinimumSize(new java.awt.Dimension(0, 80));
        contenedorTituloDetallesVenta.setPreferredSize(new java.awt.Dimension(0, 80));
        contenedorTituloDetallesVenta.setLayout(new java.awt.GridLayout(2, 1));

        lblTituloDetallesVenta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloDetallesVenta.setForeground(new java.awt.Color(89, 92, 95));
        lblTituloDetallesVenta.setText("Detalles de la compra");
        lblTituloDetallesVenta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(222, 226, 230)));
        contenedorTituloDetallesVenta.add(lblTituloDetallesVenta);

        contenedorTitulosDetalles.setBackground(new java.awt.Color(255, 255, 255));
        contenedorTitulosDetalles.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(222, 226, 230)));
        contenedorTitulosDetalles.setMaximumSize(new java.awt.Dimension(32767, 40));
        contenedorTitulosDetalles.setMinimumSize(new java.awt.Dimension(41, 40));
        contenedorTitulosDetalles.setPreferredSize(new java.awt.Dimension(0, 40));
        contenedorTitulosDetalles.setLayout(new java.awt.GridBagLayout());

        lblTituloItem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloItem.setText("Item");
        lblTituloItem.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloItem.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloItem.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosDetalles.add(lblTituloItem, gridBagConstraints);

        lblTituloNombreProducto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloNombreProducto.setText("Producto");
        lblTituloNombreProducto.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloNombreProducto.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloNombreProducto.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosDetalles.add(lblTituloNombreProducto, gridBagConstraints);

        lblTituloCantidadProducto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloCantidadProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCantidadProducto.setText("cantidad");
        lblTituloCantidadProducto.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloCantidadProducto.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloCantidadProducto.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosDetalles.add(lblTituloCantidadProducto, gridBagConstraints);

        lblTituloPrecioUnitario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloPrecioUnitario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPrecioUnitario.setText("Precio Unitario");
        lblTituloPrecioUnitario.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloPrecioUnitario.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloPrecioUnitario.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosDetalles.add(lblTituloPrecioUnitario, gridBagConstraints);

        lblTituloTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTotal.setText("Total");
        lblTituloTotal.setMaximumSize(new java.awt.Dimension(0, 0));
        lblTituloTotal.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTituloTotal.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorTitulosDetalles.add(lblTituloTotal, gridBagConstraints);

        contenedorTituloDetallesVenta.add(contenedorTitulosDetalles);

        contenedorGlobalDetallesVenta.add(contenedorTituloDetallesVenta, java.awt.BorderLayout.PAGE_START);

        contenedorDetallesVenta.setOpaque(false);
        contenedorDetallesVenta.setLayout(new javax.swing.BoxLayout(contenedorDetallesVenta, javax.swing.BoxLayout.Y_AXIS));
        contenedorGlobalDetallesVenta.add(contenedorDetallesVenta, java.awt.BorderLayout.CENTER);

        contenedorFila.add(contenedorGlobalDetallesVenta, java.awt.BorderLayout.CENTER);

        add(contenedorFila);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        boolean isVisibleDetalles = contenedorGlobalDetallesVenta.isVisible();
        contenedorGlobalDetallesVenta.setVisible(!isVisibleDetalles);
        redibujarPanel( contenedorGlobalDetallesVenta.isVisible() );
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    /*
    ============================================================================
                                METODOS PRIVADOS
    ============================================================================
    */

    /*
    Estos setter son privados puesto que el controlador tendra que mandar toda
    la informacion ya sea para actualizar la fila o asignar los datos iniciales.
    */
    private void setId( int  id ) {
        this.lblDatoId.setText( Integer.toString(id) );
    }
    
    private void setCliente (String dato) {
        this.lblDatoCliente.setText(dato);
    }

    private void setFecha ( String fecha ) {
        this.lblDatoFecha.setText( fecha );
    }

    private void setTotal( double precio ) {
        this.lblDatoTotal.setText( precioAString(precio) );
    }

    private void setAliasUsuario( String aliasUsuario ) {
        this.lblDatoAliasUsuario.setText( aliasUsuario );
    }
    
    
    /*
    Metodo para estandarizar la conversion de un precio con su simbolo
    */
    private String precioAString ( double precio ){
        return String.format("$%.2f", precio);
    }

    
    /*
    ============================================================================
                    METODOS PUBLICOS PARA EL CONTROLADOR
    ============================================================================
    */
    
    
    //SETTERS
    
    public void setDatos(   int id,
                            String nombreCliente,
                            String fecha,
                            double totalVenta,
                            String aliasUsuario ){
    
        setId(id);
        setCliente(nombreCliente);
        setFecha(fecha);
        setTotal(totalVenta);
        setAliasUsuario(aliasUsuario);
        
    }

    
    // Disponible para cuando se muestren las compras a un usuario no administrador
    public void ocultarBtnEditar(){
        contenedorDatosGenerales.remove(btnEditar);
        contenedorDatosGenerales.revalidate(); // Re calcula el diseño GridBagLayout
        contenedorDatosGenerales.repaint();    // Redibuja el panel en pantalla
    }
    
    
    public void inyectarFilasDetalles( ArrayList<FilaTablaDetalleVenta> filasDetallesVenta ){
        contenedorDetallesVenta.removeAll();
        
        filasDetallesVenta.forEach(fila -> {
            contenedorDetallesVenta.add(fila);
        });
        
    }
    
    private void redibujarPanel( boolean isVisibleDetalles ){
        if(isVisibleDetalles)
            setMaximumSize(null);
        else
            //Solucion para que cuando se muestran poquitas ventas mantenga su altura de 60 y no se expandan a lo alto
            setMaximumSize(new java.awt.Dimension(32767, 60)); 
        
        this.revalidate();
        this.repaint();
    }
    
    
    //GETTERS
    
    public JButton getBtnEditar() {
        return btnEditar;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JPanel contenedorDatosGenerales;
    private javax.swing.JPanel contenedorDetallesVenta;
    private javax.swing.JPanel contenedorFila;
    private javax.swing.JPanel contenedorGlobalDetallesVenta;
    private javax.swing.JPanel contenedorTituloDetallesVenta;
    private javax.swing.JPanel contenedorTitulosDetalles;
    private javax.swing.JLabel lblDatoAliasUsuario;
    private javax.swing.JLabel lblDatoCliente;
    private javax.swing.JLabel lblDatoFecha;
    private javax.swing.JLabel lblDatoId;
    private javax.swing.JLabel lblDatoTotal;
    private javax.swing.JLabel lblTituloCantidadProducto;
    private javax.swing.JLabel lblTituloDetallesVenta;
    private javax.swing.JLabel lblTituloItem;
    private javax.swing.JLabel lblTituloNombreProducto;
    private javax.swing.JLabel lblTituloPrecioUnitario;
    private javax.swing.JLabel lblTituloTotal;
    // End of variables declaration//GEN-END:variables
}
