
package jafrinventarios.vistas.ventas;

import jafrinventarios.vistas.utilidades.componentes.EfectoHoverPanel;

/**
 *
 * @author JOHN FORERO
 */
public class FilaTablaDetalleVenta extends javax.swing.JPanel {

    /**
     * Creates new form FilaTablaUsuarios
     */
    public FilaTablaDetalleVenta() {
        initComponents();
        
        EfectoHoverPanel.aplicarEfecto(contenedorDatos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorFila = new javax.swing.JPanel();
        contenedorDatos = new javax.swing.JPanel();
        lblDatoItem = new javax.swing.JLabel();
        lblDatoNombreProducto = new javax.swing.JLabel();
        lblDatoCantidadProducto = new javax.swing.JLabel();
        lblDatoPrecioUnitario = new javax.swing.JLabel();
        lblDatoTotal = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 40));
        setMinimumSize(new java.awt.Dimension(0, 40));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(0, 40));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        contenedorFila.setMaximumSize(new java.awt.Dimension(32767, 40));
        contenedorFila.setMinimumSize(new java.awt.Dimension(41, 40));
        contenedorFila.setOpaque(false);
        contenedorFila.setPreferredSize(new java.awt.Dimension(100, 40));
        contenedorFila.setLayout(new java.awt.BorderLayout());

        contenedorDatos.setBackground(new java.awt.Color(255, 255, 255));
        contenedorDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(222, 226, 230)));
        contenedorDatos.setMaximumSize(new java.awt.Dimension(32767, 40));
        contenedorDatos.setMinimumSize(new java.awt.Dimension(41, 40));
        contenedorDatos.setPreferredSize(new java.awt.Dimension(0, 40));
        contenedorDatos.setLayout(new java.awt.GridBagLayout());

        lblDatoItem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDatoItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoItem.setText("Item");
        lblDatoItem.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoItem.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoItem.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoItem, gridBagConstraints);

        lblDatoNombreProducto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoNombreProducto.setText("Producto");
        lblDatoNombreProducto.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoNombreProducto.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoNombreProducto.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoNombreProducto, gridBagConstraints);

        lblDatoCantidadProducto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoCantidadProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoCantidadProducto.setText("cantidad");
        lblDatoCantidadProducto.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoCantidadProducto.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoCantidadProducto.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoCantidadProducto, gridBagConstraints);

        lblDatoPrecioUnitario.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoPrecioUnitario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoPrecioUnitario.setText("Precio Unitario");
        lblDatoPrecioUnitario.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoPrecioUnitario.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoPrecioUnitario.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoPrecioUnitario, gridBagConstraints);

        lblDatoTotal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoTotal.setText("Total");
        lblDatoTotal.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoTotal.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoTotal.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoTotal, gridBagConstraints);

        contenedorFila.add(contenedorDatos, java.awt.BorderLayout.PAGE_START);

        add(contenedorFila);
    }// </editor-fold>//GEN-END:initComponents

    /*
    ============================================================================
                                METODOS PRIVADOS
    ============================================================================
    */

    /*
    Estos setter son privados puesto que el controlador tendra que mandar toda
    la informacion ya sea para actualizar la fila o asignar los datos iniciales.
    */
    private void setItem( int  item ) {
        this.lblDatoItem.setText( Integer.toString(item) );
    }
    
    private void setNombreProducto (String dato) {
        this.lblDatoNombreProducto.setText(dato);
    }

    private void setCantidadProducto ( int cantidad ) {
        this.lblDatoCantidadProducto.setText( Integer.toString(cantidad) );
    }

    private void setPrecioUnitario( double precio ) {
        this.lblDatoPrecioUnitario.setText( precioAString(precio) );
    }

    private void setPrecioTotal( double precio ) {
        this.lblDatoTotal.setText( precioAString(precio) );
    }
    
    
    /*
    Metodo para estandarizar la conversion de un precio con su simbolo
    */
    private String precioAString ( double precio ){
        return String.format("$%.2f", precio);
    }

    
    /*
    ============================================================================
                    METODOS PUBLICOS PARA EL CONTROLADOR
    ============================================================================
    */
    
    
    //SETTERS
    
    public void setDatos(   int item,
                            String nombreProducto,
                            int cantidadProducto,
                            double precioUnitario,
                            double precioTotal ){
    
        setItem(item);
        setNombreProducto(nombreProducto);
        setCantidadProducto(cantidadProducto);
        setPrecioUnitario(precioUnitario);
        setPrecioTotal(precioTotal);
        
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorDatos;
    private javax.swing.JPanel contenedorFila;
    private javax.swing.JLabel lblDatoCantidadProducto;
    private javax.swing.JLabel lblDatoItem;
    private javax.swing.JLabel lblDatoNombreProducto;
    private javax.swing.JLabel lblDatoPrecioUnitario;
    private javax.swing.JLabel lblDatoTotal;
    // End of variables declaration//GEN-END:variables
}
