/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.usuarios;

import jafrinventarios.vistas.utilidades.componentes.PanelBusquedaYRegistro;


/**
 *
 * @author JOHN FORERO
 */
public class UsuariosPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsuariosPanel
     */
    public UsuariosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorBusquedaYCreacion = new javax.swing.JPanel();
        panelBusquedaYCreacion = new jafrinventarios.vistas.utilidades.componentes.PanelBusquedaYRegistro();
        contenedorTabla = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        contenedorBusquedaYCreacion.setMaximumSize(new java.awt.Dimension(32767, 60));
        contenedorBusquedaYCreacion.setMinimumSize(new java.awt.Dimension(0, 60));
        contenedorBusquedaYCreacion.setOpaque(false);
        contenedorBusquedaYCreacion.setPreferredSize(new java.awt.Dimension(1032, 60));
        contenedorBusquedaYCreacion.setLayout(new javax.swing.BoxLayout(contenedorBusquedaYCreacion, javax.swing.BoxLayout.LINE_AXIS));
        contenedorBusquedaYCreacion.add(panelBusquedaYCreacion);

        add(contenedorBusquedaYCreacion, java.awt.BorderLayout.PAGE_START);

        contenedorTabla.setOpaque(false);

        javax.swing.GroupLayout contenedorTablaLayout = new javax.swing.GroupLayout(contenedorTabla);
        contenedorTabla.setLayout(contenedorTablaLayout);
        contenedorTablaLayout.setHorizontalGroup(
            contenedorTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        contenedorTablaLayout.setVerticalGroup(
            contenedorTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        add(contenedorTabla, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    /*
    ============================================================================
                        MÉTODOS PÚBLICOS PARA EL CONTROLADOR
    ============================================================================
    */
    
    public PanelBusquedaYRegistro getPanelBusquedaYRegistro(){
        return panelBusquedaYCreacion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorBusquedaYCreacion;
    private javax.swing.JPanel contenedorTabla;
    private jafrinventarios.vistas.utilidades.componentes.PanelBusquedaYRegistro panelBusquedaYCreacion;
    // End of variables declaration//GEN-END:variables
}
