/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.utilidades;

/**
 *
 * @author johna
 * Esta clase se realiza para poder personalizar dialogos propios
 * y asi mantener el diseño de la aplicacion uniforme
 */
public class DialogoPersonalizado extends javax.swing.JDialog {

    /**
     * Creates new form DialogoPersonalizado
     */
    public DialogoPersonalizado(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Centrar en pantalla relativo al padre
        setLocationRelativeTo(parent);
        contenedorBotonUnico.setVisible(false);
    }
    
    public enum TipoIcono{
        ERROR,
        ADVERTENCIA,
        INFORMACION,
        EXITO,
        CARGANDO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorFondoBlanco = new javax.swing.JPanel();
        contenedorHeader = new javax.swing.JPanel();
        margin_left = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        iconoDialogo = new javax.swing.JLabel();
        contenedorBtnCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        contenedorCuerpo = new javax.swing.JPanel();
        tituloDialogo = new javax.swing.JLabel();
        mensajeDialogo = new javax.swing.JTextArea();
        contenedorBotonUnico = new javax.swing.JPanel();
        btnCentro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        contenedorFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFondoBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contenedorFondoBlanco.setLayout(new java.awt.BorderLayout());

        contenedorHeader.setMinimumSize(new java.awt.Dimension(0, 80));
        contenedorHeader.setOpaque(false);
        contenedorHeader.setPreferredSize(new java.awt.Dimension(0, 80));
        contenedorHeader.setLayout(new java.awt.BorderLayout());
        contenedorHeader.add(margin_left, java.awt.BorderLayout.WEST);

        iconoDialogo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        iconoDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/vaadin--ban.png"))); // NOI18N
        iconoDialogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        iconoDialogo.setMaximumSize(new java.awt.Dimension(3000, 50));
        iconoDialogo.setMinimumSize(new java.awt.Dimension(0, 50));
        iconoDialogo.setPreferredSize(new java.awt.Dimension(0, 50));
        contenedorHeader.add(iconoDialogo, java.awt.BorderLayout.CENTER);

        contenedorBtnCerrar.setMinimumSize(new java.awt.Dimension(40, 0));
        contenedorBtnCerrar.setOpaque(false);
        contenedorBtnCerrar.setPreferredSize(new java.awt.Dimension(40, 0));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(17, 35, 85));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/carbon--close-filled.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusCycleRoot(true);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setPreferredSize(new java.awt.Dimension(30, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        contenedorBtnCerrar.add(btnCerrar);

        contenedorHeader.add(contenedorBtnCerrar, java.awt.BorderLayout.EAST);

        contenedorFondoBlanco.add(contenedorHeader, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpo.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 40, 20, 40));
        contenedorCuerpo.setOpaque(false);
        contenedorCuerpo.setLayout(new java.awt.BorderLayout(0, 15));

        tituloDialogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tituloDialogo.setForeground(new java.awt.Color(17, 35, 85));
        tituloDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDialogo.setText("titulo del dialogo");
        contenedorCuerpo.add(tituloDialogo, java.awt.BorderLayout.PAGE_START);

        mensajeDialogo.setEditable(false);
        mensajeDialogo.setColumns(25);
        mensajeDialogo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mensajeDialogo.setLineWrap(true);
        mensajeDialogo.setRows(1);
        mensajeDialogo.setTabSize(1);
        mensajeDialogo.setWrapStyleWord(true);
        mensajeDialogo.setOpaque(false);
        contenedorCuerpo.add(mensajeDialogo, java.awt.BorderLayout.CENTER);

        contenedorFondoBlanco.add(contenedorCuerpo, java.awt.BorderLayout.CENTER);

        contenedorBotonUnico.setMaximumSize(new java.awt.Dimension(0, 60));
        contenedorBotonUnico.setMinimumSize(new java.awt.Dimension(0, 60));
        contenedorBotonUnico.setOpaque(false);
        contenedorBotonUnico.setPreferredSize(new java.awt.Dimension(0, 60));

        btnCentro.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCentro.setText("Entendido");
        btnCentro.setMaximumSize(new java.awt.Dimension(160, 35));
        btnCentro.setMinimumSize(new java.awt.Dimension(160, 35));
        btnCentro.setPreferredSize(new java.awt.Dimension(160, 35));
        contenedorBotonUnico.add(btnCentro);

        contenedorFondoBlanco.add(contenedorBotonUnico, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(contenedorFondoBlanco, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoPersonalizado dialog = new DialogoPersonalizado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Método estático que podrás llamar desde cualquier parte de tu código
    public static void mostrarDialogo(javax.swing.JFrame padreFrame, String titulo, String mensaje, TipoIcono tipoIcono) {
        
        DialogoPersonalizado dialogo = new DialogoPersonalizado(padreFrame, true);
        
        // Asignar los textos a tus JLabels del diseño
        dialogo.tituloDialogo.setText(titulo);
        dialogo.mensajeDialogo.setText(mensaje);
    
        
        dialogo.iconoDialogo.setIcon(
                dialogo.obtenerImagenIcono(tipoIcono)
        );  
        
        // Se crea un JPanel especial con transparencia dedicado para asignar al glassPane del frame padre
        GlassPaneSemiOscuro panelSemiOscuro = new GlassPaneSemiOscuro();

        if (padreFrame != null) {
            padreFrame.setGlassPane(panelSemiOscuro);
            panelSemiOscuro.setVisible(true); 
        }
        
        // Mostrar el diálogo (el código se pausa aquí hasta que se cierra el modal)
        dialogo.pack();
        dialogo.setVisible(true);
        
        // Al cerrar el modal, dejamos de mostrar el fondo semitransparente
        if (padreFrame != null) {
            panelSemiOscuro.setVisible(false);
        }
    }
    
    
    private javax.swing.ImageIcon obtenerImagenIcono(TipoIcono icono){
        
        String rutaCarpetaIconos = "/jafrinventarios/recursos/iconos/";
        String nombreArchivoIcono = "icono_fluent--chat-help-24-filled.png";
        
        switch(icono){
            case ERROR:
                nombreArchivoIcono = "vaadin--ban.png";
                break;
            case ADVERTENCIA:
                nombreArchivoIcono = "noto-v1--warning.png";
                break;
            case INFORMACION:
                nombreArchivoIcono = "mdi--information.png";
                break;
            case EXITO:
                nombreArchivoIcono = "lets-icons--check-fill.png";
                break;
            case CARGANDO:
                nombreArchivoIcono = "fluent--spinner-ios-16-filled.png";
                break;
            default:
                break;
        }
                
        return new javax.swing.ImageIcon(
                    getClass().getResource( rutaCarpetaIconos + nombreArchivoIcono )
                );
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentro;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel contenedorBotonUnico;
    private javax.swing.JPanel contenedorBtnCerrar;
    private javax.swing.JPanel contenedorCuerpo;
    private javax.swing.JPanel contenedorFondoBlanco;
    private javax.swing.JPanel contenedorHeader;
    private javax.swing.JLabel iconoDialogo;
    private javax.swing.Box.Filler margin_left;
    private javax.swing.JTextArea mensajeDialogo;
    private javax.swing.JLabel tituloDialogo;
    // End of variables declaration//GEN-END:variables
}
