/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.utilidades;

import javax.swing.JFrame;

/**
 *
 * @author johna
 * Esta clase se realiza para poder personalizar dialogos propios
 * y asi mantener el diseño de la aplicacion uniforme
 */
public class DialogoPersonalizado extends javax.swing.JDialog {

        //Variable enum para poder mostrar en codigo las opciones validas de TipoIcono
        public enum TipoIcono{
        ERROR,
        ADVERTENCIA,
        INFORMACION,
        EXITO,
        CARGANDO
        }
        
        //Variable global para mejorar legibilidad del codigo
        // Se crea un JPanel especial con transparencia dedicado para asignar al glassPane del frame padre
        private final GlassPaneSemiOscuro panelSemiOscuro = new GlassPaneSemiOscuro();
        
        private final JFrame padreFrame;
        
        private boolean respuesta = false;
    /**
     * Creates new form DialogoPersonalizado
     */
    private DialogoPersonalizado(JFrame parent, boolean modal, String titulo, String mensaje, TipoIcono tipoIcono, boolean mostrarBotones) {
        super(parent, modal);
        this.padreFrame = parent;
        
        initComponents();

        configurarContenidoDialogo(titulo, mensaje, tipoIcono);
        
        contenedorBotonesAdvertencia.setVisible(mostrarBotones);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorFondoBlanco = new javax.swing.JPanel();
        contenedorHeader = new javax.swing.JPanel();
        margin_left = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        iconoDialogo = new javax.swing.JLabel();
        contenedorBtnCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        contenedorCuerpo = new javax.swing.JPanel();
        tituloDialogo = new javax.swing.JLabel();
        mensajeDialogo = new javax.swing.JLabel();
        contenedorBotonesAdvertencia = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 2147483647));
        setUndecorated(true);

        contenedorFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFondoBlanco.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 0, 20, 0)));
        contenedorFondoBlanco.setLayout(new java.awt.BorderLayout());

        contenedorHeader.setMinimumSize(new java.awt.Dimension(0, 100));
        contenedorHeader.setOpaque(false);
        contenedorHeader.setPreferredSize(new java.awt.Dimension(0, 100));
        contenedorHeader.setLayout(new java.awt.BorderLayout());
        contenedorHeader.add(margin_left, java.awt.BorderLayout.WEST);

        iconoDialogo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        iconoDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/dialogos/vaadin--ban.png"))); // NOI18N
        iconoDialogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        iconoDialogo.setMaximumSize(new java.awt.Dimension(3000, 60));
        iconoDialogo.setMinimumSize(new java.awt.Dimension(0, 60));
        iconoDialogo.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorHeader.add(iconoDialogo, java.awt.BorderLayout.CENTER);

        contenedorBtnCerrar.setMinimumSize(new java.awt.Dimension(40, 0));
        contenedorBtnCerrar.setOpaque(false);
        contenedorBtnCerrar.setPreferredSize(new java.awt.Dimension(40, 0));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(17, 35, 85));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/carbon--close-filled.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusCycleRoot(true);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setPreferredSize(new java.awt.Dimension(30, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDialogo(evt);
            }
        });
        contenedorBtnCerrar.add(btnCerrar);

        contenedorHeader.add(contenedorBtnCerrar, java.awt.BorderLayout.EAST);

        contenedorFondoBlanco.add(contenedorHeader, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpo.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 60, 25, 60));
        contenedorCuerpo.setOpaque(false);
        contenedorCuerpo.setLayout(new java.awt.BorderLayout(0, 25));

        tituloDialogo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        tituloDialogo.setForeground(new java.awt.Color(17, 35, 85));
        tituloDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDialogo.setText("titulo del dialogo");
        contenedorCuerpo.add(tituloDialogo, java.awt.BorderLayout.PAGE_START);

        mensajeDialogo.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        mensajeDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeDialogo.setText("Texto de prueba");
        contenedorCuerpo.add(mensajeDialogo, java.awt.BorderLayout.CENTER);

        contenedorFondoBlanco.add(contenedorCuerpo, java.awt.BorderLayout.CENTER);

        contenedorBotonesAdvertencia.setMaximumSize(new java.awt.Dimension(0, 60));
        contenedorBotonesAdvertencia.setMinimumSize(new java.awt.Dimension(0, 60));
        contenedorBotonesAdvertencia.setOpaque(false);
        contenedorBotonesAdvertencia.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorBotonesAdvertencia.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        btnContinuar.setBackground(new java.awt.Color(255, 0, 0));
        btnContinuar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar.setMaximumSize(new java.awt.Dimension(160, 35));
        btnContinuar.setMinimumSize(new java.awt.Dimension(160, 35));
        btnContinuar.setPreferredSize(new java.awt.Dimension(160, 35));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        contenedorBotonesAdvertencia.add(btnContinuar);

        btnCancelar.setBackground(new java.awt.Color(17, 35, 85));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setMaximumSize(new java.awt.Dimension(160, 35));
        btnCancelar.setMinimumSize(new java.awt.Dimension(160, 35));
        btnCancelar.setPreferredSize(new java.awt.Dimension(160, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDialogo(evt);
            }
        });
        contenedorBotonesAdvertencia.add(btnCancelar);

        contenedorFondoBlanco.add(contenedorBotonesAdvertencia, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(contenedorFondoBlanco, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.respuesta = true;
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void cerrarDialogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarDialogo
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarDialogo

    
    // Método estático que podrás llamar desde cualquier parte del proyecto
    public static boolean mostrarDialogo(JFrame padreFrame, String titulo, String mensaje, TipoIcono tipoIcono, boolean mostrarBotones) {
        
        DialogoPersonalizado dialogo = new DialogoPersonalizado(padreFrame, true, titulo, mensaje, tipoIcono, mostrarBotones);
        
        dialogo.hacerVisibleDialogo();
        // Mostrar el diálogo (el código se pausa aquí hasta que se cierra el modal)
        
        // Al cerrar el modal, se deja de mostrar el fondo semitransparente
        dialogo.ocultarGlassPanePadreDialogo();
        
        return dialogo.respuesta;
    }
    
    private void configurarContenidoDialogo( String titulo, String mensaje, TipoIcono tipoIcono){
        //Asignar el incono segun el tipo recibido
        iconoDialogo.setIcon(
                obtenerImagenIcono(tipoIcono)
        );  
        
        // Asignar los textos a los JLabels del diseño
        tituloDialogo.setText(titulo);
        mensajeDialogo.setText(empaquetarMensaje(mensaje));
    }
    
    private String empaquetarMensaje(String mensaje){
        int ancho;

        if (mensaje.length() < 120) {
            ancho = 250;
        } else if (mensaje.length() < 250) {
            ancho = 300;
        } else {
            ancho = 350;   
        }
        
        return  "<html>"
                + "<div style=' "
                +   "width:" + ancho + "px; "
                +   "font-family:'Segoe UI', Arial; "
                +   "font-size:19px; "
                +   "text-align:center;"
                + " '>"
                + mensaje
                + "</div>"
                + "</html>";
    }
    
    private void mostrarGlassPanePadreDialogo(){
        if (padreFrame != null) {
            padreFrame.setGlassPane(panelSemiOscuro);
            panelSemiOscuro.setVisible(true); 
        }
    }
    
    private void ocultarGlassPanePadreDialogo(){
        if (padreFrame != null) {
            panelSemiOscuro.setVisible(false);
        }
    }
    
    private void hacerVisibleDialogo(){
        // mostrar fondo semitransparente
        mostrarGlassPanePadreDialogo();
        // Recalcular tamaño del dialog segun el tamaño que necesite cada componente interno
        pack();
        // Centrar el dialogo con respecto a su padre
        setLocationRelativeTo(padreFrame);
        // Mostrar el diálogo (el código se pausa aquí hasta que se cierra el modal)
        setVisible(true);
    }
    
    
    
    private javax.swing.ImageIcon obtenerImagenIcono(TipoIcono icono){
        
        String rutaCarpetaIconos = "/jafrinventarios/recursos/iconos/dialogos/";
        String nombreArchivoIcono = "icono_fluent--chat-help-24-filled.png";
        
        switch(icono){
            case ERROR:
                nombreArchivoIcono = "vaadin--ban.png";
                break;
            case ADVERTENCIA:
                nombreArchivoIcono = "noto-v1--warning.png";
                break;
            case INFORMACION:
                nombreArchivoIcono = "mdi--information.png";
                break;
            case EXITO:
                nombreArchivoIcono = "lets-icons--check-fill.png";
                break;
            case CARGANDO:
                nombreArchivoIcono = "fluent--spinner-ios-16-filled.png";
                break;
            default:
                break;
        }
                
        return new javax.swing.ImageIcon(
                    getClass().getResource( rutaCarpetaIconos + nombreArchivoIcono )
                );
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JPanel contenedorBotonesAdvertencia;
    private javax.swing.JPanel contenedorBtnCerrar;
    private javax.swing.JPanel contenedorCuerpo;
    private javax.swing.JPanel contenedorFondoBlanco;
    private javax.swing.JPanel contenedorHeader;
    private javax.swing.JLabel iconoDialogo;
    private javax.swing.Box.Filler margin_left;
    private javax.swing.JLabel mensajeDialogo;
    private javax.swing.JLabel tituloDialogo;
    // End of variables declaration//GEN-END:variables
}
