
package jafrinventarios.vistas.proveedores;

import jafrinventarios.vistas.utilidades.componentes.DinamismoLink;
import jafrinventarios.vistas.utilidades.dialogos.DialogoAlerta;
import jafrinventarios.vistas.utilidades.dialogos.DialogoBaseConSombra;
import jafrinventarios.vistas.utilidades.formularios.TipoDatoFormulario;
import jafrinventarios.vistas.utilidades.formularios.GestorFormulario;
import java.awt.Window;
import java.util.HashMap;
import java.util.LinkedHashMap;
import javax.swing.JButton;

/**
 *
 * @author JOHN FORERO
 */
public class DialogoFormularioProveedor extends DialogoBaseConSombra{

    /*
      Objeto enum auxiliar para mejorar la legibilidad del codigo
    */
    public static enum TipoDialogo {
        EDITAR_PROVEEDOR,
        CREAR_NUEVO_PROVEEDOR
    }
    
    private GestorFormulario formularioDatosProveedor;
    
    private TipoDialogo tipoDialogo;
    
    /*
    ============================================================================
                            CONSTRUCTOR PUBLICO
    ============================================================================
    El controlador ofrece metodos estaticos para poder establecer con el mismo
    cuales son los paremetros que sean acorde a la intencion del metodo estatico.
    */
    public DialogoFormularioProveedor(   Window parent, 
                                        TipoDialogo tipoDialogo) {
        
        super(parent);
        initComponents();
        
        formularioDatosProveedor = new GestorFormulario();
        this.tipoDialogo = tipoDialogo;
        
        if (this.tipoDialogo == TipoDialogo.CREAR_NUEVO_PROVEEDOR) {
            contenedorIdRegistro.setVisible(false);
            tituloFormulario.setText("Crear Nuevo Proveedor");
        }
        
        //Ocultamos los botones por que es el controlador quien decide cual mostrar
        btnLinkEditarEstadoRegistro.setVisible(false);
        btnLinkEliminarRegistro.setVisible(false);
        
        agregarCamposAGestorFormulario();
        
    }
    
    
    private void agregarCamposAGestorFormulario(){
        
        formularioDatosProveedor.agregarCampoTexto(inputNombreComercial, 
                                            lblErrorInputNombreComercial, 
                                            TipoDatoFormulario.NOMBRE_EMPRESA, 
                                            true);
        
        formularioDatosProveedor.agregarCampoTexto( inputCorreo, 
                                            lblErrorInputCorreo, 
                                            TipoDatoFormulario.CORREO, 
                                            true);
        
        formularioDatosProveedor.agregarCampoTexto( inputDireccion, 
                                            lblErrorInputDireccion, 
                                            TipoDatoFormulario.REQUERIDO, 
                                            true);
        
        formularioDatosProveedor.agregarCampoTexto( inputPrimerNombre, 
                                            lblErrorInputPrimerNombre, 
                                            TipoDatoFormulario.NOMBRE_PERSONA, 
                                            true);

        formularioDatosProveedor.agregarCampoTexto( inputSegundoNombre, 
                                            lblErrorInputSegundoNombre, 
                                            TipoDatoFormulario.NOMBRE_PERSONA, 
                                            false);

        formularioDatosProveedor.agregarCampoTexto( inputPrimerApellido, 
                                            lblErrorInputPrimerApellido, 
                                            TipoDatoFormulario.NOMBRE_PERSONA, 
                                            true);

        formularioDatosProveedor.agregarCampoTexto( inputSegundoApellido, 
                                            lblErrorInputSegundoApellido, 
                                            TipoDatoFormulario.NOMBRE_PERSONA, 
                                            false);

        formularioDatosProveedor.agregarCampoTexto( inputTelefono, 
                                            lblErrorInputTelefono, 
                                            TipoDatoFormulario.TELEFONO, 
                                            true);
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipalScrolleable = new javax.swing.JScrollPane();
        contenedorFormulario = new javax.swing.JPanel();
        contenedorTituloFormulario = new javax.swing.JPanel();
        margin_left = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        tituloFormulario = new javax.swing.JLabel();
        contenedorBtnCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        contenedorCuerpoFormulario = new javax.swing.JPanel();
        contenedorIdRegistro = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        lblDatoID = new javax.swing.JLabel();
        contenedorDatosGenerales = new javax.swing.JPanel();
        contenedorTituloDatosGenerales = new javax.swing.JPanel();
        subtituloDatosGenerales = new javax.swing.JLabel();
        contenedorEntradasDatosGenerales = new javax.swing.JPanel();
        labelNombreComercial = new javax.swing.JLabel();
        contenedorInputYErrorNombreComercial = new javax.swing.JPanel();
        inputNombreComercial = new javax.swing.JTextField();
        lblErrorInputNombreComercial = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        contenedorInputYErrorCorreo = new javax.swing.JPanel();
        inputCorreo = new javax.swing.JTextField();
        lblErrorInputCorreo = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        contenedorInputYErrorDireccion = new javax.swing.JPanel();
        inputDireccion = new javax.swing.JTextField();
        lblErrorInputDireccion = new javax.swing.JLabel();
        contenedorEntradaNombreCompleto = new javax.swing.JPanel();
        contenedorTituloDatosContacto = new javax.swing.JPanel();
        subtituloDatosContacto = new javax.swing.JLabel();
        contenedorEntradasNombreCompleto = new javax.swing.JPanel();
        labelPrimerNombre = new javax.swing.JLabel();
        contenedorInputYErrorPrimerNombre = new javax.swing.JPanel();
        inputPrimerNombre = new javax.swing.JTextField();
        lblErrorInputPrimerNombre = new javax.swing.JLabel();
        labelSegundoNombre = new javax.swing.JLabel();
        contenedorInputYErrorSegundoNombre = new javax.swing.JPanel();
        inputSegundoNombre = new javax.swing.JTextField();
        lblErrorInputSegundoNombre = new javax.swing.JLabel();
        labelPrimerApellido = new javax.swing.JLabel();
        contenedorInputYErrorPrimerApellido = new javax.swing.JPanel();
        inputPrimerApellido = new javax.swing.JTextField();
        lblErrorInputPrimerApellido = new javax.swing.JLabel();
        labelSegundoApellido = new javax.swing.JLabel();
        contenedorInputYErrorSegundoApellido = new javax.swing.JPanel();
        inputSegundoApellido = new javax.swing.JTextField();
        lblErrorInputSegundoApellido = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        contenedorInputYErrorTelefono = new javax.swing.JPanel();
        inputTelefono = new javax.swing.JTextField();
        lblErrorInputTelefono = new javax.swing.JLabel();
        contenedorBotones = new javax.swing.JPanel();
        btnEnviarFormulario = new javax.swing.JButton();
        btnLinkEditarEstadoRegistro = new javax.swing.JButton();
        btnLinkEliminarRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 0));
        setName("dialogoProveedor"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipalScrolleable.setBackground(new java.awt.Color(205, 205, 205));
        panelPrincipalScrolleable.setOpaque(false);

        contenedorFormulario.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFormulario.setLayout(new java.awt.BorderLayout());

        contenedorTituloFormulario.setMinimumSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setOpaque(false);
        contenedorTituloFormulario.setPreferredSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setLayout(new java.awt.BorderLayout());
        contenedorTituloFormulario.add(margin_left, java.awt.BorderLayout.WEST);

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(17, 35, 85));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Editar Proveedor");
        tituloFormulario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tituloFormulario.setAlignmentX(0.5F);
        tituloFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        tituloFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setVerifyInputWhenFocusTarget(false);
        contenedorTituloFormulario.add(tituloFormulario, java.awt.BorderLayout.CENTER);

        contenedorBtnCerrar.setMinimumSize(new java.awt.Dimension(40, 0));
        contenedorBtnCerrar.setOpaque(false);
        contenedorBtnCerrar.setPreferredSize(new java.awt.Dimension(40, 0));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        contenedorBtnCerrar.setLayout(flowLayout1);

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(17, 35, 85));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/carbon--close-filled.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusCycleRoot(true);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setPreferredSize(new java.awt.Dimension(30, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDialogo(evt);
            }
        });
        contenedorBtnCerrar.add(btnCerrar);

        contenedorTituloFormulario.add(contenedorBtnCerrar, java.awt.BorderLayout.EAST);

        contenedorFormulario.add(contenedorTituloFormulario, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpoFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 50));
        contenedorCuerpoFormulario.setOpaque(false);
        contenedorCuerpoFormulario.setLayout(new java.awt.GridBagLayout());

        contenedorIdRegistro.setBackground(new java.awt.Color(205, 205, 205));
        contenedorIdRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contenedorIdRegistro.setOpaque(false);
        contenedorIdRegistro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        labelID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        labelID.setText("Id :");
        contenedorIdRegistro.add(labelID);

        lblDatoID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDatoID.setText("001");
        contenedorIdRegistro.add(lblDatoID);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contenedorCuerpoFormulario.add(contenedorIdRegistro, gridBagConstraints);

        contenedorDatosGenerales.setOpaque(false);
        contenedorDatosGenerales.setLayout(new javax.swing.BoxLayout(contenedorDatosGenerales, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloDatosGenerales.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloDatosGenerales.setOpaque(false);
        contenedorTituloDatosGenerales.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloDatosGenerales.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloDatosGenerales.setText("Datos Generales");
        subtituloDatosGenerales.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloDatosGenerales.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloDatosGenerales.add(subtituloDatosGenerales);

        contenedorDatosGenerales.add(contenedorTituloDatosGenerales);

        contenedorEntradasDatosGenerales.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 20, 0, 20));
        contenedorEntradasDatosGenerales.setOpaque(false);
        contenedorEntradasDatosGenerales.setLayout(new java.awt.GridBagLayout());

        labelNombreComercial.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelNombreComercial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombreComercial.setText("Nombre Comercial :");
        labelNombreComercial.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelNombreComercial.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelNombreComercial.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelNombreComercial.setMaximumSize(new java.awt.Dimension(0, 0));
        labelNombreComercial.setMinimumSize(new java.awt.Dimension(0, 0));
        labelNombreComercial.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasDatosGenerales.add(labelNombreComercial, gridBagConstraints);

        contenedorInputYErrorNombreComercial.setOpaque(false);
        contenedorInputYErrorNombreComercial.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorNombreComercial.setLayout(new java.awt.BorderLayout());

        inputNombreComercial.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputNombreComercial.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputNombreComercial.setName("nombreComercial"); // NOI18N
        inputNombreComercial.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorNombreComercial.add(inputNombreComercial, java.awt.BorderLayout.NORTH);

        lblErrorInputNombreComercial.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputNombreComercial.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputNombreComercial.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputNombreComercial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputNombreComercial.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorNombreComercial.add(lblErrorInputNombreComercial, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasDatosGenerales.add(contenedorInputYErrorNombreComercial, gridBagConstraints);

        labelCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCorreo.setText("Correo :");
        labelCorreo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelCorreo.setMaximumSize(new java.awt.Dimension(0, 0));
        labelCorreo.setMinimumSize(new java.awt.Dimension(0, 0));
        labelCorreo.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorEntradasDatosGenerales.add(labelCorreo, gridBagConstraints);

        contenedorInputYErrorCorreo.setOpaque(false);
        contenedorInputYErrorCorreo.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorCorreo.setLayout(new java.awt.BorderLayout());

        inputCorreo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputCorreo.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputCorreo.setName("correoProveedor"); // NOI18N
        inputCorreo.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorCorreo.add(inputCorreo, java.awt.BorderLayout.NORTH);

        lblErrorInputCorreo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputCorreo.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputCorreo.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorCorreo.add(lblErrorInputCorreo, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasDatosGenerales.add(contenedorInputYErrorCorreo, gridBagConstraints);

        labelDireccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDireccion.setText("Direccion :");
        labelDireccion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelDireccion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelDireccion.setMaximumSize(new java.awt.Dimension(0, 0));
        labelDireccion.setMinimumSize(new java.awt.Dimension(0, 0));
        labelDireccion.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasDatosGenerales.add(labelDireccion, gridBagConstraints);

        contenedorInputYErrorDireccion.setOpaque(false);
        contenedorInputYErrorDireccion.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorDireccion.setLayout(new java.awt.BorderLayout());

        inputDireccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputDireccion.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputDireccion.setName("direccionProveedor"); // NOI18N
        inputDireccion.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorDireccion.add(inputDireccion, java.awt.BorderLayout.NORTH);

        lblErrorInputDireccion.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputDireccion.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputDireccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputDireccion.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorDireccion.add(lblErrorInputDireccion, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasDatosGenerales.add(contenedorInputYErrorDireccion, gridBagConstraints);

        contenedorDatosGenerales.add(contenedorEntradasDatosGenerales);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contenedorCuerpoFormulario.add(contenedorDatosGenerales, gridBagConstraints);

        contenedorEntradaNombreCompleto.setOpaque(false);
        contenedorEntradaNombreCompleto.setLayout(new javax.swing.BoxLayout(contenedorEntradaNombreCompleto, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloDatosContacto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloDatosContacto.setOpaque(false);
        contenedorTituloDatosContacto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloDatosContacto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloDatosContacto.setText("Datos de contacto");
        subtituloDatosContacto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloDatosContacto.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloDatosContacto.add(subtituloDatosContacto);

        contenedorEntradaNombreCompleto.add(contenedorTituloDatosContacto);

        contenedorEntradasNombreCompleto.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 0, 20));
        contenedorEntradasNombreCompleto.setOpaque(false);
        contenedorEntradasNombreCompleto.setLayout(new java.awt.GridBagLayout());

        labelPrimerNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelPrimerNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPrimerNombre.setText("Primer Nombre :");
        labelPrimerNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelPrimerNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelPrimerNombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelPrimerNombre.setMaximumSize(new java.awt.Dimension(0, 0));
        labelPrimerNombre.setMinimumSize(new java.awt.Dimension(0, 0));
        labelPrimerNombre.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasNombreCompleto.add(labelPrimerNombre, gridBagConstraints);

        contenedorInputYErrorPrimerNombre.setOpaque(false);
        contenedorInputYErrorPrimerNombre.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorPrimerNombre.setLayout(new java.awt.BorderLayout());

        inputPrimerNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputPrimerNombre.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputPrimerNombre.setName("primerNombreContacto"); // NOI18N
        inputPrimerNombre.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorPrimerNombre.add(inputPrimerNombre, java.awt.BorderLayout.NORTH);

        lblErrorInputPrimerNombre.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputPrimerNombre.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputPrimerNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputPrimerNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputPrimerNombre.setPreferredSize(new java.awt.Dimension(0, 17));
        lblErrorInputPrimerNombre.setRequestFocusEnabled(false);
        contenedorInputYErrorPrimerNombre.add(lblErrorInputPrimerNombre, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorPrimerNombre, gridBagConstraints);

        labelSegundoNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelSegundoNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelSegundoNombre.setText("Segundo Nombre :");
        labelSegundoNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelSegundoNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelSegundoNombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelSegundoNombre.setMaximumSize(new java.awt.Dimension(0, 0));
        labelSegundoNombre.setMinimumSize(new java.awt.Dimension(0, 0));
        labelSegundoNombre.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasNombreCompleto.add(labelSegundoNombre, gridBagConstraints);

        contenedorInputYErrorSegundoNombre.setOpaque(false);
        contenedorInputYErrorSegundoNombre.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorSegundoNombre.setLayout(new java.awt.BorderLayout());

        inputSegundoNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputSegundoNombre.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputSegundoNombre.setName("segundoNombreContacto"); // NOI18N
        inputSegundoNombre.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorSegundoNombre.add(inputSegundoNombre, java.awt.BorderLayout.NORTH);

        lblErrorInputSegundoNombre.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputSegundoNombre.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputSegundoNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputSegundoNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputSegundoNombre.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorSegundoNombre.add(lblErrorInputSegundoNombre, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorSegundoNombre, gridBagConstraints);

        labelPrimerApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelPrimerApellido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelPrimerApellido.setText("Primer Apellido :");
        labelPrimerApellido.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelPrimerApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelPrimerApellido.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelPrimerApellido.setMaximumSize(new java.awt.Dimension(0, 0));
        labelPrimerApellido.setMinimumSize(new java.awt.Dimension(0, 0));
        labelPrimerApellido.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasNombreCompleto.add(labelPrimerApellido, gridBagConstraints);

        contenedorInputYErrorPrimerApellido.setOpaque(false);
        contenedorInputYErrorPrimerApellido.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorPrimerApellido.setLayout(new java.awt.BorderLayout());

        inputPrimerApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputPrimerApellido.setToolTipText("");
        inputPrimerApellido.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputPrimerApellido.setName("primerApellidoContacto"); // NOI18N
        inputPrimerApellido.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorPrimerApellido.add(inputPrimerApellido, java.awt.BorderLayout.NORTH);

        lblErrorInputPrimerApellido.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputPrimerApellido.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputPrimerApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputPrimerApellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputPrimerApellido.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorPrimerApellido.add(lblErrorInputPrimerApellido, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorPrimerApellido, gridBagConstraints);

        labelSegundoApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelSegundoApellido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelSegundoApellido.setText("Segundo Apellido :");
        labelSegundoApellido.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelSegundoApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelSegundoApellido.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelSegundoApellido.setMaximumSize(new java.awt.Dimension(0, 0));
        labelSegundoApellido.setMinimumSize(new java.awt.Dimension(0, 0));
        labelSegundoApellido.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorEntradasNombreCompleto.add(labelSegundoApellido, gridBagConstraints);

        contenedorInputYErrorSegundoApellido.setOpaque(false);
        contenedorInputYErrorSegundoApellido.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorSegundoApellido.setLayout(new java.awt.BorderLayout());

        inputSegundoApellido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputSegundoApellido.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputSegundoApellido.setName("segundoApellidoContacto"); // NOI18N
        inputSegundoApellido.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorSegundoApellido.add(inputSegundoApellido, java.awt.BorderLayout.NORTH);

        lblErrorInputSegundoApellido.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputSegundoApellido.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputSegundoApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputSegundoApellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputSegundoApellido.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorSegundoApellido.add(lblErrorInputSegundoApellido, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorSegundoApellido, gridBagConstraints);

        labelTelefono.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTelefono.setText("Telefono :");
        labelTelefono.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelTelefono.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelTelefono.setMaximumSize(new java.awt.Dimension(0, 0));
        labelTelefono.setMinimumSize(new java.awt.Dimension(0, 0));
        labelTelefono.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasNombreCompleto.add(labelTelefono, gridBagConstraints);

        contenedorInputYErrorTelefono.setOpaque(false);
        contenedorInputYErrorTelefono.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorTelefono.setLayout(new java.awt.BorderLayout());

        inputTelefono.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputTelefono.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputTelefono.setName("telefonoContacto"); // NOI18N
        inputTelefono.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorTelefono.add(inputTelefono, java.awt.BorderLayout.NORTH);

        lblErrorInputTelefono.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputTelefono.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputTelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputTelefono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputTelefono.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorTelefono.add(lblErrorInputTelefono, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasNombreCompleto.add(contenedorInputYErrorTelefono, gridBagConstraints);

        contenedorEntradaNombreCompleto.add(contenedorEntradasNombreCompleto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contenedorCuerpoFormulario.add(contenedorEntradaNombreCompleto, gridBagConstraints);

        contenedorFormulario.add(contenedorCuerpoFormulario, java.awt.BorderLayout.CENTER);

        contenedorBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 10, 40));
        contenedorBotones.setOpaque(false);
        contenedorBotones.setPreferredSize(new java.awt.Dimension(500, 130));
        contenedorBotones.setLayout(new java.awt.GridBagLayout());

        btnEnviarFormulario.setBackground(new java.awt.Color(30, 166, 177));
        btnEnviarFormulario.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEnviarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarFormulario.setText("Actualizar");
        btnEnviarFormulario.setToolTipText("");
        btnEnviarFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarFormulario.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnEnviarFormulario.setMaximumSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setMinimumSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotones.add(btnEnviarFormulario, gridBagConstraints);

        btnLinkEditarEstadoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnLinkEditarEstadoRegistro.setForeground(new java.awt.Color(200, 0, 0));
        btnLinkEditarEstadoRegistro.setText("Deshabilitar Proveedor");
        btnLinkEditarEstadoRegistro.setActionCommand("Deshabilitar Proveedor");
        btnLinkEditarEstadoRegistro.setAlignmentX(0.5F);
        btnLinkEditarEstadoRegistro.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotones.add(btnLinkEditarEstadoRegistro, gridBagConstraints);

        btnLinkEliminarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnLinkEliminarRegistro.setForeground(new java.awt.Color(200, 0, 0));
        btnLinkEliminarRegistro.setText("Eliminar Proveedor");
        btnLinkEliminarRegistro.setAlignmentX(0.5F);
        btnLinkEliminarRegistro.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotones.add(btnLinkEliminarRegistro, gridBagConstraints);

        contenedorFormulario.add(contenedorBotones, java.awt.BorderLayout.PAGE_END);

        panelPrincipalScrolleable.setViewportView(contenedorFormulario);

        getContentPane().add(panelPrincipalScrolleable);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarDialogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarDialogo
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarDialogo

    
    
    /*
    ============================================================================
                      MÉTODOS PÚBLICOS PARA EL CONTROLADOR
    ============================================================================
    */

    
    public void setId( Integer id ){
        lblDatoID.setText( Integer.toString(id) );
    }
    
    public void mostrarBtnLinkEliminarProveedor(){
        btnLinkEliminarRegistro.setVisible(true);
        DinamismoLink.aplicarEfecto(btnLinkEliminarRegistro);
    }
    
    public void mostrarBtnEditarEstadoProveedor(){
        btnLinkEditarEstadoRegistro.setVisible(true);
        DinamismoLink.aplicarEfecto(btnLinkEditarEstadoRegistro);
    }
    
    public void asignarIntencionBtnEditarEstadoProveedor(boolean habilitado){
        
        if(habilitado){
            //Si esta habilitado el proveedor, se muestra el boton para demostrar
            //la intencion de poder deshabilitarlo
            btnLinkEditarEstadoRegistro.setForeground(new java.awt.Color(200, 0, 0));
            btnLinkEditarEstadoRegistro.setText("Deshabilitar Proveedor");
        }else{
            btnLinkEditarEstadoRegistro.setForeground(new java.awt.Color(17, 35, 85));
            btnLinkEditarEstadoRegistro.setText("Habilitar Proveedor");
        }
        btnLinkEditarEstadoRegistro.repaint();
        
    }
    
    
    //Exponer botones
    public JButton getBtnEnviarFormulario(){
        return btnEnviarFormulario;
    }
    
    public JButton getBtnLinkEditarEstadoProveedor(){
        return btnLinkEditarEstadoRegistro;
    }
    
    public JButton getBtnLinkEliminarProveedor(){
        return btnLinkEliminarRegistro;
    }
    
    
    //Exponer metodos para gestionar el formulario
    public boolean validarFormulario(){
        return formularioDatosProveedor.validar();
    }
    
    public HashMap<String, String> recolectarDatosFormulario(){
        return formularioDatosProveedor.recolectarDatos();
    }
    
    public void mostrarErroresValidacionCampos( HashMap<String, String> errores ){
        formularioDatosProveedor.mostrarErroresExternos(errores);
    }
    
    public void asignarDatosEnFormulario( HashMap<String, String> datos ){
        formularioDatosProveedor.asignarDatos(datos);
    }
    
    
    /* 
        Metodos para dialogos de mensajes de Alertas
    */
    public void mostrarAlertaErrorFormatoCampos(){
        DialogoAlerta.mostrarErrorFormatoCampos( this );
    }    
    
    public void mostrarAlertaExitosa(String mensajeExitoso ){
        
        DialogoAlerta.mostrarExito(
                    this, 
                    "Operacion Exitosa", 
                    mensajeExitoso
            );
        
    }
    
    public boolean mostrarAlertaAdvertencia( String mensaje ){
        
       return DialogoAlerta.mostrarAdvertenciaConRespuesta(
                   this,
                   "Advertencia", 
                   mensaje
                );
    
    }
    
    public void mostrarAlertaError( String mensaje ){
        DialogoAlerta.mostrarError( this, "Error", mensaje );
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviarFormulario;
    private javax.swing.JButton btnLinkEditarEstadoRegistro;
    private javax.swing.JButton btnLinkEliminarRegistro;
    private javax.swing.JPanel contenedorBotones;
    private javax.swing.JPanel contenedorBtnCerrar;
    private javax.swing.JPanel contenedorCuerpoFormulario;
    private javax.swing.JPanel contenedorDatosGenerales;
    private javax.swing.JPanel contenedorEntradaNombreCompleto;
    private javax.swing.JPanel contenedorEntradasDatosGenerales;
    private javax.swing.JPanel contenedorEntradasNombreCompleto;
    private javax.swing.JPanel contenedorFormulario;
    private javax.swing.JPanel contenedorIdRegistro;
    private javax.swing.JPanel contenedorInputYErrorCorreo;
    private javax.swing.JPanel contenedorInputYErrorDireccion;
    private javax.swing.JPanel contenedorInputYErrorNombreComercial;
    private javax.swing.JPanel contenedorInputYErrorPrimerApellido;
    private javax.swing.JPanel contenedorInputYErrorPrimerNombre;
    private javax.swing.JPanel contenedorInputYErrorSegundoApellido;
    private javax.swing.JPanel contenedorInputYErrorSegundoNombre;
    private javax.swing.JPanel contenedorInputYErrorTelefono;
    private javax.swing.JPanel contenedorTituloDatosContacto;
    private javax.swing.JPanel contenedorTituloDatosGenerales;
    private javax.swing.JPanel contenedorTituloFormulario;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputDireccion;
    private javax.swing.JTextField inputNombreComercial;
    private javax.swing.JTextField inputPrimerApellido;
    private javax.swing.JTextField inputPrimerNombre;
    private javax.swing.JTextField inputSegundoApellido;
    private javax.swing.JTextField inputSegundoNombre;
    private javax.swing.JTextField inputTelefono;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombreComercial;
    private javax.swing.JLabel labelPrimerApellido;
    private javax.swing.JLabel labelPrimerNombre;
    private javax.swing.JLabel labelSegundoApellido;
    private javax.swing.JLabel labelSegundoNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel lblDatoID;
    private javax.swing.JLabel lblErrorInputCorreo;
    private javax.swing.JLabel lblErrorInputDireccion;
    private javax.swing.JLabel lblErrorInputNombreComercial;
    private javax.swing.JLabel lblErrorInputPrimerApellido;
    private javax.swing.JLabel lblErrorInputPrimerNombre;
    private javax.swing.JLabel lblErrorInputSegundoApellido;
    private javax.swing.JLabel lblErrorInputSegundoNombre;
    private javax.swing.JLabel lblErrorInputTelefono;
    private javax.swing.Box.Filler margin_left;
    private javax.swing.JScrollPane panelPrincipalScrolleable;
    private javax.swing.JLabel subtituloDatosContacto;
    private javax.swing.JLabel subtituloDatosGenerales;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
