
package jafrinventarios.vistas.inventario;

import jafrinventarios.vistas.utilidades.componentes.EfectoHoverPanel;
import jafrinventarios.vistas.utilidades.formularios.CampoTexto;
import jafrinventarios.vistas.utilidades.formularios.TipoDatoFormulario;
import javax.swing.JCheckBox;

/**
 *
 * @author JOHN FORERO
 */
public class FilaTablaInventario extends javax.swing.JPanel {
    
    CampoTexto campoNuevaCantidad;

    /**
     * Creates new form FilaTablaUsuarios
     */
    public FilaTablaInventario() {
        initComponents();
        
        EfectoHoverPanel.aplicarEfecto(contenedorDatos);
        
        campoNuevaCantidad = new CampoTexto(    inputNuevaCantidad,
                                                lblErrorInputNuevaCantidad,
                                                TipoDatoFormulario.NUMERO_ENTERO,
                                                true        
        );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorFila = new javax.swing.JPanel();
        contenedorDatos = new javax.swing.JPanel();
        lblDatoId = new javax.swing.JLabel();
        lblDatoProveedor = new javax.swing.JLabel();
        lblDatoProducto = new javax.swing.JLabel();
        lblDatoCantidad = new javax.swing.JLabel();
        contenedorInputYErrorNuevaCantidad = new javax.swing.JPanel();
        inputNuevaCantidad = new javax.swing.JTextField();
        lblErrorInputNuevaCantidad = new javax.swing.JLabel();
        checkBoxConfirmar = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(32767, 80));
        setMinimumSize(new java.awt.Dimension(0, 80));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(0, 80));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        contenedorFila.setMaximumSize(new java.awt.Dimension(32767, 80));
        contenedorFila.setMinimumSize(new java.awt.Dimension(41, 80));
        contenedorFila.setOpaque(false);
        contenedorFila.setPreferredSize(new java.awt.Dimension(100, 80));
        contenedorFila.setLayout(new java.awt.BorderLayout());

        contenedorDatos.setBackground(new java.awt.Color(255, 255, 255));
        contenedorDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 0, 0, 0));
        contenedorDatos.setMaximumSize(new java.awt.Dimension(32767, 68));
        contenedorDatos.setMinimumSize(new java.awt.Dimension(41, 68));
        contenedorDatos.setPreferredSize(new java.awt.Dimension(0, 68));
        contenedorDatos.setLayout(new java.awt.GridBagLayout());

        lblDatoId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoId.setText("Id");
        lblDatoId.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDatoId.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        lblDatoId.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoId.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoId.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoId, gridBagConstraints);

        lblDatoProveedor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoProveedor.setText("Proveedor");
        lblDatoProveedor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDatoProveedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        lblDatoProveedor.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoProveedor.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoProveedor.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoProveedor, gridBagConstraints);

        lblDatoProducto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoProducto.setText("Producto");
        lblDatoProducto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDatoProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        lblDatoProducto.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoProducto.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoProducto.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoProducto, gridBagConstraints);

        lblDatoCantidad.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDatoCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatoCantidad.setText("Cantidad");
        lblDatoCantidad.setToolTipText("");
        lblDatoCantidad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDatoCantidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        lblDatoCantidad.setMaximumSize(new java.awt.Dimension(0, 0));
        lblDatoCantidad.setMinimumSize(new java.awt.Dimension(0, 0));
        lblDatoCantidad.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        contenedorDatos.add(lblDatoCantidad, gridBagConstraints);

        contenedorInputYErrorNuevaCantidad.setOpaque(false);
        contenedorInputYErrorNuevaCantidad.setLayout(new java.awt.BorderLayout());

        inputNuevaCantidad.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputNuevaCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputNuevaCantidad.setText("0");
        inputNuevaCantidad.setToolTipText("");
        inputNuevaCantidad.setMaximumSize(new java.awt.Dimension(0, 0));
        inputNuevaCantidad.setMinimumSize(new java.awt.Dimension(0, 0));
        inputNuevaCantidad.setName("cantidadProducto"); // NOI18N
        inputNuevaCantidad.setPreferredSize(new java.awt.Dimension(0, 28));
        contenedorInputYErrorNuevaCantidad.add(inputNuevaCantidad, java.awt.BorderLayout.NORTH);

        lblErrorInputNuevaCantidad.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputNuevaCantidad.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputNuevaCantidad.setAlignmentX(0.5F);
        lblErrorInputNuevaCantidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputNuevaCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputNuevaCantidad.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorNuevaCantidad.add(lblErrorInputNuevaCantidad, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        contenedorDatos.add(contenedorInputYErrorNuevaCantidad, gridBagConstraints);

        checkBoxConfirmar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        checkBoxConfirmar.setAlignmentX(0.5F);
        checkBoxConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkBoxConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBoxConfirmar.setMaximumSize(new java.awt.Dimension(30, 30));
        checkBoxConfirmar.setMinimumSize(new java.awt.Dimension(30, 30));
        checkBoxConfirmar.setOpaque(false);
        checkBoxConfirmar.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 24, 20);
        contenedorDatos.add(checkBoxConfirmar, gridBagConstraints);

        contenedorFila.add(contenedorDatos, java.awt.BorderLayout.PAGE_START);

        add(contenedorFila);
    }// </editor-fold>//GEN-END:initComponents

    /*
    ============================================================================
                                METODOS PRIVADOS
    ============================================================================
    */

    /*
    Estos setter son privados puesto que el controlador tendra que mandar toda
    la informacion ya sea para actualizar la fila o asignar los datos iniciales.
    */
    private void setId( int  id ) {
        this.lblDatoId.setText( Integer.toString(id) );
    }
    
    private void setProveedor (String dato) {
        this.lblDatoProveedor.setText(dato);
    }
    
    private void setProducto(String dato) {
        this.lblDatoProducto.setText(dato);
    }

    private void setCantidadProducto ( int cantidad ) {
        this.lblDatoCantidad.setText( String.valueOf(cantidad) );
    }

    
    /*
    ============================================================================
                    METODOS PUBLICOS PARA EL CONTROLADOR
    ============================================================================
    */
    
    
    //SETTERS
    
    public void setDatos(   int id,
                            String nombreProveedor,
                            String nombreProducto,
                            int cantidadProducto ){
    
        setId(id);
        setProducto(nombreProducto);
        setProveedor(nombreProveedor);
        setCantidadProducto(cantidadProducto);
        
    }
    
    //Metodo para cambiar el color de la fila si es un item ya verificado
    public void setEstadoVisual(boolean confirmado){
        if(confirmado){
            contenedorDatos.setBackground(new java.awt.Color(217, 217, 217));
            
        }else{
            contenedorDatos.setBackground(new java.awt.Color(255, 255, 255));
        }
        inputNuevaCantidad.setEnabled( confirmado );
    }
    
  
    public void configurarModoVerificacion( boolean modoVerificar){
        contenedorInputYErrorNuevaCantidad.setVisible(modoVerificar);
        checkBoxConfirmar.setVisible(modoVerificar);
        contenedorDatos.revalidate(); // Re calcula el diseño GridBagLayout
        contenedorDatos.repaint();    // Redibuja el panel en pantalla
    }
    
    
    //GETTERS
    public JCheckBox getCheckBoxConfirmar() {
        return checkBoxConfirmar;
    }
    
    
    /*
    Metodos para gestionar el campo nueva cantidad, para validar y obtener el valor
    usamos la variable de tipo CampoTexto, que permite hacer la gestion de errores
    de manera grafica, si contiene numero o si esta vacio.
    */
    public boolean validarCampoNuevaCantidad(){
        return campoNuevaCantidad.validar();
    }
    
    public String obtenerValorNuevaCantidad(){
        return campoNuevaCantidad.getValorComponente();
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxConfirmar;
    private javax.swing.JPanel contenedorDatos;
    private javax.swing.JPanel contenedorFila;
    private javax.swing.JPanel contenedorInputYErrorNuevaCantidad;
    private javax.swing.JTextField inputNuevaCantidad;
    private javax.swing.JLabel lblDatoCantidad;
    private javax.swing.JLabel lblDatoId;
    private javax.swing.JLabel lblDatoProducto;
    private javax.swing.JLabel lblDatoProveedor;
    private javax.swing.JLabel lblErrorInputNuevaCantidad;
    // End of variables declaration//GEN-END:variables
}
