/*
     NOTA: Se decide crear una clase propia que simule un JoptionPane, ya que 
     por defecto esta clase no permite personalizarla y daña completamente
     el estilo que se quiere mantener en toda la aplicacion. 

     Ademas para globalizar los iconos a utilizar se crea un enum dentro del paquete
     jafrinventarios.vistas.utilidades.iconos
     Llamada IconosDialogosMensajePersonalizado
     Desde alli se puede acceder a cada uno de los iconos ya convertidos 
     en el formato necesario para incrustarlo en este JDialog

 */
package jafrinventarios.vistas.utilidades.dialogos;

import jafrinventarios.vistas.utilidades.iconos.IconosBotones;
import jafrinventarios.vistas.utilidades.iconos.IconosDialogosMensajePersonalizado;
import java.awt.Window;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author johna
 * Esta clase se realiza para poder personalizar dialogos propios
 * y asi mantener el diseño de la aplicacion uniforme
 */
public class DialogoMensajePersonalizado extends DialogoBaseConSombra {

    /*
    Variable de respuesta utilizada para cuando se utilicen los dos botones
    continuar o cancelar
    */
    private boolean respuesta = false;
    
    
    /*
    ========================================================================================
        CONSTRUCTOR PRIVADO PARA EVITAR QUE SE CREE SIN SU DEBIDA CONFIGURACION
    =========================================================================================
    */
    private DialogoMensajePersonalizado(
                                    Window parent, 
                                    String titulo, 
                                    String mensaje, 
                                    IconosDialogosMensajePersonalizado tipoIcono, 
                                    boolean mostrarBotones) {
        super(parent);

        initComponents();
        
        btnCerrar.setIcon(IconosBotones.CERRAR.getIcono());

        configurarContenidoDialogo(titulo, mensaje, tipoIcono);
        
        contenedorBotonesAdvertencia.setVisible(mostrarBotones);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorFondoBlanco = new javax.swing.JPanel();
        contenedorHeader = new javax.swing.JPanel();
        margin_left = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        iconoDialogo = new javax.swing.JLabel();
        contenedorBtnCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        contenedorCuerpo = new javax.swing.JPanel();
        tituloDialogo = new javax.swing.JLabel();
        mensajeDialogo = new javax.swing.JLabel();
        contenedorBotonesAdvertencia = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        contenedorFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFondoBlanco.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 0, 20, 0)));
        contenedorFondoBlanco.setLayout(new java.awt.BorderLayout());

        contenedorHeader.setMinimumSize(new java.awt.Dimension(0, 100));
        contenedorHeader.setOpaque(false);
        contenedorHeader.setPreferredSize(new java.awt.Dimension(0, 120));
        contenedorHeader.setLayout(new java.awt.BorderLayout());
        contenedorHeader.add(margin_left, java.awt.BorderLayout.WEST);

        iconoDialogo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        iconoDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/dialogos/vaadin--ban.png"))); // NOI18N
        iconoDialogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        iconoDialogo.setMaximumSize(new java.awt.Dimension(3000, 60));
        iconoDialogo.setMinimumSize(new java.awt.Dimension(0, 60));
        iconoDialogo.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorHeader.add(iconoDialogo, java.awt.BorderLayout.CENTER);

        contenedorBtnCerrar.setMinimumSize(new java.awt.Dimension(40, 0));
        contenedorBtnCerrar.setOpaque(false);
        contenedorBtnCerrar.setPreferredSize(new java.awt.Dimension(40, 0));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(17, 35, 85));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/carbon--close-filled.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusCycleRoot(true);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setPreferredSize(new java.awt.Dimension(30, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDialogo(evt);
            }
        });
        contenedorBtnCerrar.add(btnCerrar);

        contenedorHeader.add(contenedorBtnCerrar, java.awt.BorderLayout.EAST);

        contenedorFondoBlanco.add(contenedorHeader, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpo.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 60, 25, 60));
        contenedorCuerpo.setOpaque(false);
        contenedorCuerpo.setLayout(new java.awt.BorderLayout(0, 25));

        tituloDialogo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        tituloDialogo.setForeground(new java.awt.Color(17, 35, 85));
        tituloDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDialogo.setText("titulo del dialogo");
        contenedorCuerpo.add(tituloDialogo, java.awt.BorderLayout.PAGE_START);

        mensajeDialogo.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        mensajeDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeDialogo.setText("Texto de prueba");
        contenedorCuerpo.add(mensajeDialogo, java.awt.BorderLayout.CENTER);

        contenedorFondoBlanco.add(contenedorCuerpo, java.awt.BorderLayout.CENTER);

        contenedorBotonesAdvertencia.setMaximumSize(new java.awt.Dimension(0, 60));
        contenedorBotonesAdvertencia.setMinimumSize(new java.awt.Dimension(0, 60));
        contenedorBotonesAdvertencia.setOpaque(false);
        contenedorBotonesAdvertencia.setPreferredSize(new java.awt.Dimension(0, 60));
        contenedorBotonesAdvertencia.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        btnContinuar.setBackground(new java.awt.Color(255, 0, 0));
        btnContinuar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar.setMaximumSize(new java.awt.Dimension(160, 35));
        btnContinuar.setMinimumSize(new java.awt.Dimension(160, 35));
        btnContinuar.setPreferredSize(new java.awt.Dimension(160, 35));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        contenedorBotonesAdvertencia.add(btnContinuar);

        btnCancelar.setBackground(new java.awt.Color(17, 35, 85));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setMaximumSize(new java.awt.Dimension(160, 35));
        btnCancelar.setMinimumSize(new java.awt.Dimension(160, 35));
        btnCancelar.setPreferredSize(new java.awt.Dimension(160, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDialogo(evt);
            }
        });
        contenedorBotonesAdvertencia.add(btnCancelar);

        contenedorFondoBlanco.add(contenedorBotonesAdvertencia, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(contenedorFondoBlanco, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.respuesta = true;
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void cerrarDialogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarDialogo
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarDialogo

    
    /*
    ===========================================================================
            METODO ESTATICO PARA ARMAR CUALQUIER TIPO DE MENSAJE
    ===========================================================================
    */
    public static boolean mostrar(
                                    Window ventanaPadre, 
                                    String titulo, 
                                    String mensaje, 
                                    IconosDialogosMensajePersonalizado tipoIcono, 
                                    boolean mostrarBotones) {
        
        DialogoMensajePersonalizado dialogo =
                new DialogoMensajePersonalizado(ventanaPadre, 
                                                titulo, 
                                                mensaje, 
                                                tipoIcono, 
                                                mostrarBotones);
        
        dialogo.hacerVisibleDialogo();
        // Mostrar el diálogo (el código se pausa aquí hasta que se cierra el modal)
        
        return dialogo.respuesta;
    }
    
    /*
    ===========================================================================
                   METODO ESTATICO PARA MOSTRAR UN ERROR 
    ===========================================================================
    */
    public static void mostrarError(Window ventanaPadre, 
                                    String titulo, 
                                    String mensaje){
    
        mostrar(
                    ventanaPadre,
                    titulo, 
                    mensaje,
                    IconosDialogosMensajePersonalizado.ERROR, 
                    false
            );
    
    }
    
    
    /*
    ===========================================================================
        METODO ESTATICO PARA MOSTRAR ERROR DE FORMATO DE CAMPOS
    ===========================================================================
    Metodo estatico para mostrar un error ya preestablecido con su titulo y mensaje
    para cuando en un formulario sus campos tengan algun error de tipo de formato o estan vacios
    */
    public static void mostrarErrorFormatoCampos(Window ventanaPadre){
    
        mostrarError(
                ventanaPadre,
                "Información incompleta o inválida", 
                "Algunos datos ingresados no cumplen con el formato requerido o se encuentran vacíos.\n\nPor favor, revise los campos resaltados en el formulario y corrija la información antes de continuar."
        );
    
    }
    
    /*
    ===========================================================================
      METODO ESTATICO PARA MOSTRAR EL ERROR DE RESPUESTA DE LA BASE DE DATOS
    ===========================================================================
        Metodo estatico para mostrar el error de cada campo de un formulario
        segun la respuesta de la base de datos
    */
    public static void mostrarErrorRespuestaBD(Window ventanaPadre, HashMap<String, String> erroresFormulario){
        
        StringBuilder armadoErrores = new StringBuilder();
        
        for (Map.Entry<String, String> campo : erroresFormulario.entrySet()) {
           // Extraer la clave y capitalizar la primera letra (ej: "correo" -> "Correo")
            String nombreCampo = campo.getKey().substring(0, 1).toUpperCase() + campo.getKey().substring(1);
            
            armadoErrores.append("\n• ") // Agregamos un salto de línea y una viñeta visual
                         .append(nombreCampo)
                         .append(": ")
                         .append(campo.getValue());
        }
        
        mostrarError(
                ventanaPadre,
                "Error de validación", 
                "El sistema ha detectado problemas con la información ingresada:\n"
                + armadoErrores.toString()
                + "\n\nPor favor, revise los campos marcados en el formulario e intente nuevamente."
        );
    
    }
    
    
    /*
    ===========================================================================
                METODO ESTATICO PARA MOSTRAR UN MENSAJE DE EXITO
    ===========================================================================
    */
    public static void mostrarExito(Window ventanaPadre, 
                                    String titulo, 
                                    String mensaje){
    
        mostrar(
                    ventanaPadre,
                    titulo, 
                    mensaje,
                    IconosDialogosMensajePersonalizado.EXITO, 
                    false
            );
    
    }
    
    
    
    /*
    ===========================================================================
       METODO ESTATICO PARA MOSTRAR UN MENSAJE DE ADVERTENCIA CON RESPUESTA
    ===========================================================================
    */
    public static boolean mostrarAdvertenciaConRespuesta(
                                    Window ventanaPadre, 
                                    String titulo, 
                                    String mensaje){
    
       return mostrar(
                        ventanaPadre,
                        titulo, 
                        mensaje,
                        IconosDialogosMensajePersonalizado.ADVERTENCIA, 
                        true
                );
    
    }
    
    
    /*
    ===========================================================================
       METODO ESTATICO PARA MOSTRAR UN MENSAJE DE ADVERTENCIA SIN RESPUESTA
    ===========================================================================
    */
    public static void mostrarAdvertenciaSinRespuesta(
                                    Window ventanaPadre, 
                                    String titulo, 
                                    String mensaje){
    
       mostrar(
                ventanaPadre,
                titulo, 
                mensaje,
                IconosDialogosMensajePersonalizado.ADVERTENCIA, 
                false
        );
    
    }
    
    
    /*
    ===========================================================================
        FUNCION PRIVADA PARA CONFIGURAR EL CONTENIDO DEL DIALOGO
    ===========================================================================
    */
    private void configurarContenidoDialogo( 
                                String titulo, 
                                String mensaje, 
                                IconosDialogosMensajePersonalizado tipoIcono){
        //Asignar el incono segun el tipo recibido
        iconoDialogo.setIcon( tipoIcono.getIcono()  );  
        
        // Asignar los textos a los JLabels del diseño
        tituloDialogo.setText(titulo);
        mensajeDialogo.setText(empaquetarMensaje(mensaje));
    }
    
    
    /*
    ===========================================================================
        FUNCION PRIVADA PARA RECIBIR EL MENSAJE Y CONVERTIRLO A HTML
    ===========================================================================
    Esta permite determinar segun la longitud del mensaje el ancho que ocupara
    en el jLabel, para asi poder personalizar el tamaño mismo del JDialog
    Ademas se aprovecha la funcionalidad de los JLabel para inyectar HTML
    y que el texto automaticamente haga los saltos de lineas necesarios
    ya que al incrustar el texto directamente en el JLabel, este no tiene la 
    capacidad de por si solo hacer dichos saltos.
    */
    private String empaquetarMensaje(String mensaje){
        
        /*
         Para que al incrustar el mensaje al jLabel, este no se rompa por 
            el html que se va a generar, se tienen encuenta cuatro condiciones
            una de ellas es para poder hacer un salto de linea, las demas
            son caracteres especiales en html.      
        */
        mensaje = mensaje
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\n", "<br>");
        
        
        int ancho;

        if (mensaje.length() < 120) {
            ancho = 250;
        } else if (mensaje.length() < 250) {
            ancho = 300;
        } else {
            ancho = 350;   
        }
        
        return  "<html>"
                + "<p style=' "
                +   "width:" + ancho + "px; "
                +   "font-family:'Segoe UI', Arial; "
                +   "font-size:19px; "
                +   "text-align:center;"
                + " '>"
                + mensaje
                + "</p>"
                + "</html>";
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JPanel contenedorBotonesAdvertencia;
    private javax.swing.JPanel contenedorBtnCerrar;
    private javax.swing.JPanel contenedorCuerpo;
    private javax.swing.JPanel contenedorFondoBlanco;
    private javax.swing.JPanel contenedorHeader;
    private javax.swing.JLabel iconoDialogo;
    private javax.swing.Box.Filler margin_left;
    private javax.swing.JLabel mensajeDialogo;
    private javax.swing.JLabel tituloDialogo;
    // End of variables declaration//GEN-END:variables
}
