/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jafrinventarios.vistas.reportes;

import javax.swing.JButton;

/**
 *
 * @author JOHN FORERO
 */
public class ReportePanel extends javax.swing.JPanel {

    /**
     * Creates new form reportes
     */
    public ReportePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedorPrincipal = new javax.swing.JPanel();
        contenedorSeleccionReporte = new javax.swing.JPanel();
        tituloSeleccionTipoReporte = new javax.swing.JLabel();
        contenedorBotonesFiltros = new javax.swing.JPanel();
        btnReporteCantidadesComprar = new javax.swing.JButton();
        btnReporteCompras = new javax.swing.JButton();
        btnReporteVentas = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 205, 205));
        setMaximumSize(new java.awt.Dimension(37210, 37210));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        contenedorPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        contenedorPrincipal.setMaximumSize(new java.awt.Dimension(600, 37210));
        contenedorPrincipal.setMinimumSize(new java.awt.Dimension(600, 0));
        contenedorPrincipal.setOpaque(false);
        contenedorPrincipal.setPreferredSize(new java.awt.Dimension(600, 0));
        contenedorPrincipal.setLayout(new javax.swing.BoxLayout(contenedorPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        contenedorSeleccionReporte.setBackground(new java.awt.Color(255, 255, 255));
        contenedorSeleccionReporte.setMaximumSize(new java.awt.Dimension(600, 450));
        contenedorSeleccionReporte.setMinimumSize(new java.awt.Dimension(600, 450));
        contenedorSeleccionReporte.setPreferredSize(new java.awt.Dimension(600, 450));
        contenedorSeleccionReporte.setLayout(new java.awt.BorderLayout());

        tituloSeleccionTipoReporte.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionTipoReporte.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloSeleccionTipoReporte.setForeground(new java.awt.Color(17, 35, 85));
        tituloSeleccionTipoReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloSeleccionTipoReporte.setText("Selecciona el tipo de reporte a crear");
        tituloSeleccionTipoReporte.setAlignmentX(0.5F);
        tituloSeleccionTipoReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloSeleccionTipoReporte.setMaximumSize(new java.awt.Dimension(500, 120));
        tituloSeleccionTipoReporte.setMinimumSize(new java.awt.Dimension(500, 120));
        tituloSeleccionTipoReporte.setOpaque(true);
        tituloSeleccionTipoReporte.setPreferredSize(new java.awt.Dimension(500, 120));
        tituloSeleccionTipoReporte.setVerifyInputWhenFocusTarget(false);
        contenedorSeleccionReporte.add(tituloSeleccionTipoReporte, java.awt.BorderLayout.PAGE_START);

        contenedorBotonesFiltros.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 80, 40, 80));
        contenedorBotonesFiltros.setMinimumSize(new java.awt.Dimension(0, 0));
        contenedorBotonesFiltros.setOpaque(false);
        contenedorBotonesFiltros.setPreferredSize(new java.awt.Dimension(0, 0));
        contenedorBotonesFiltros.setLayout(new java.awt.GridBagLayout());

        btnReporteCantidadesComprar.setBackground(new java.awt.Color(17, 35, 85));
        btnReporteCantidadesComprar.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btnReporteCantidadesComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteCantidadesComprar.setText("Cantidades a comprar");
        btnReporteCantidadesComprar.setToolTipText("");
        btnReporteCantidadesComprar.setAlignmentX(0.5F);
        btnReporteCantidadesComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteCantidadesComprar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnReporteCantidadesComprar.setIconTextGap(6);
        btnReporteCantidadesComprar.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnReporteCantidadesComprar.setMaximumSize(new java.awt.Dimension(270, 48));
        btnReporteCantidadesComprar.setMinimumSize(new java.awt.Dimension(270, 48));
        btnReporteCantidadesComprar.setPreferredSize(new java.awt.Dimension(270, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotonesFiltros.add(btnReporteCantidadesComprar, gridBagConstraints);

        btnReporteCompras.setBackground(new java.awt.Color(17, 35, 85));
        btnReporteCompras.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btnReporteCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteCompras.setText("Reporte de compras");
        btnReporteCompras.setToolTipText("");
        btnReporteCompras.setAlignmentX(0.5F);
        btnReporteCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteCompras.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnReporteCompras.setIconTextGap(6);
        btnReporteCompras.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnReporteCompras.setMaximumSize(new java.awt.Dimension(270, 48));
        btnReporteCompras.setMinimumSize(new java.awt.Dimension(270, 48));
        btnReporteCompras.setPreferredSize(new java.awt.Dimension(270, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotonesFiltros.add(btnReporteCompras, gridBagConstraints);

        btnReporteVentas.setBackground(new java.awt.Color(17, 35, 85));
        btnReporteVentas.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btnReporteVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteVentas.setText("Reporte de ventas");
        btnReporteVentas.setToolTipText("");
        btnReporteVentas.setAlignmentX(0.5F);
        btnReporteVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteVentas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnReporteVentas.setIconTextGap(6);
        btnReporteVentas.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnReporteVentas.setMaximumSize(new java.awt.Dimension(270, 48));
        btnReporteVentas.setMinimumSize(new java.awt.Dimension(270, 48));
        btnReporteVentas.setPreferredSize(new java.awt.Dimension(270, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotonesFiltros.add(btnReporteVentas, gridBagConstraints);

        contenedorSeleccionReporte.add(contenedorBotonesFiltros, java.awt.BorderLayout.CENTER);

        contenedorPrincipal.add(contenedorSeleccionReporte);

        add(contenedorPrincipal);
    }// </editor-fold>//GEN-END:initComponents

/*
================================================================================
                        METODOS PARA EL CONTROLADOR
================================================================================
*/

    public JButton getBtnReporteCantidadComprar(){
        return btnReporteCantidadesComprar;
    }
    
    public JButton getBtnReporteCompras(){
        return btnReporteCompras;
    }
    
    public JButton getBtnReporteVentas(){
        return btnReporteVentas;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteCantidadesComprar;
    private javax.swing.JButton btnReporteCompras;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JPanel contenedorBotonesFiltros;
    private javax.swing.JPanel contenedorPrincipal;
    private javax.swing.JPanel contenedorSeleccionReporte;
    private javax.swing.JLabel tituloSeleccionTipoReporte;
    // End of variables declaration//GEN-END:variables
}
