################################################
# REGLAS GLOBALES DE DISE\u00d1O DE LOS COMPONENTES 
################################################

Component.focusWidth=1.8

Component.focusColor=#1EA6B188


# Redondear otros componentes como el ComboBox
Component.arc=15

####################################
# TEXTFIELD
####################################

# Redondear todas las cajas de texto (inputs)
TextComponent.arc=15


####################################
# BUTTON
####################################

#Redondear todos los botones (el n\u00famero es el radio de la curva)
Button.arc=15






