
package jafrinventarios.vistas.productos;

import jafrinventarios.vistas.utilidades.componentes.DinamismoLink;
import jafrinventarios.vistas.utilidades.dialogos.DialogoAlerta;
import jafrinventarios.vistas.utilidades.dialogos.DialogoBaseConSombra;
import jafrinventarios.vistas.utilidades.formularios.TipoDatoFormulario;
import jafrinventarios.vistas.utilidades.formularios.GestorFormulario;
import java.awt.Window;
import java.util.HashMap;
import java.util.LinkedHashMap;
import javax.swing.JButton;

/**
 *
 * @author JOHN FORERO
 */
public class DialogoFormularioProducto extends DialogoBaseConSombra{

    /*
      Objeto enum auxiliar para mejorar la legibilidad del codigo
    */
    public static enum TipoDialogo {
        EDITAR_PRODUCTO,
        CREAR_NUEVO_PRODUCTO
    }
    
    private GestorFormulario formularioDatosProducto;
    
    private TipoDialogo tipoDialogo;
    
    /*
    ============================================================================
                            CONSTRUCTOR PUBLICO
    ============================================================================
    El controlador ofrece metodos estaticos para poder establecer con el mismo
    cuales son los paremetros que sean acorde a la intencion del metodo estatico.
    */
    public DialogoFormularioProducto(   Window parent, 
                                        TipoDialogo tipoDialogo) {
        
        super(parent);
        initComponents();
        
        formularioDatosProducto = new GestorFormulario();
        this.tipoDialogo = tipoDialogo;
        
        if (this.tipoDialogo == TipoDialogo.CREAR_NUEVO_PRODUCTO) {
            contenedorIdRegistro.setVisible(false);
            tituloFormulario.setText("Crear Nuevo Producto");
        }
        
        //Ocultamos los botones por que es el controlador quien decide cual mostrar
        btnLinkEditarEstadoRegistro.setVisible(false);
        btnLinkEliminarRegistro.setVisible(false);
        
        agregarCamposAGestorFormulario();
        
    }
    
    
    private void agregarCamposAGestorFormulario(){
        
        formularioDatosProducto.agregarCampoTexto(inputNombre, 
                                          lblErrorInputNombre, 
                                          TipoDatoFormulario.NOMBRE_PRODUCTO, 
                                          true);
        /*
            El combo box rol se agrega desde el controlador por medio de 
            inicializarComboBoxProveedores para que se le asigne el diccionario de proveedores
        */
        
        formularioDatosProducto.agregarCampoTexto(inputPrecioCompra, 
                                          lblErrorInputPrecioCompra, 
                                          TipoDatoFormulario.NUMERO_DOUBLE, 
                                          true);

        formularioDatosProducto.agregarCampoTexto(inputPrecioVenta, 
                                          lblErrorInputPrecioVenta, 
                                          TipoDatoFormulario.NUMERO_DOUBLE, 
                                          true);

        formularioDatosProducto.agregarCampoTexto(inputCantidadDisponible, 
                                          lblErrorInputCantidadDisponible, 
                                          TipoDatoFormulario.NUMERO_ENTERO, 
                                          true);
        
        formularioDatosProducto.agregarCampoTexto(inputCantidadMinStock, 
                                          lblErrorInputCantidadMinStock, 
                                          TipoDatoFormulario.NUMERO_ENTERO, 
                                          true);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipalScrolleable = new javax.swing.JScrollPane();
        contenedorFormulario = new javax.swing.JPanel();
        contenedorTituloFormulario = new javax.swing.JPanel();
        margin_left = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        tituloFormulario = new javax.swing.JLabel();
        contenedorBtnCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        contenedorCuerpoFormulario = new javax.swing.JPanel();
        contenedorIdRegistro = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        lblDatoID = new javax.swing.JLabel();
        contenedorDatosGenerales = new javax.swing.JPanel();
        contenedorTituloDatosGenerales = new javax.swing.JPanel();
        subtituloDatosGenerales = new javax.swing.JLabel();
        contenedorEntradasDatosGenerales = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        contenedorInputYErrorNombre = new javax.swing.JPanel();
        inputNombre = new javax.swing.JTextField();
        lblErrorInputNombre = new javax.swing.JLabel();
        labelProveedor = new javax.swing.JLabel();
        contenedorInputYErrorProveedor = new javax.swing.JPanel();
        comboBoxProveedores = new javax.swing.JComboBox<>();
        lblErrorComboBoxProveedores = new javax.swing.JLabel();
        contenedorPrecios = new javax.swing.JPanel();
        contenedorTituloPrecios = new javax.swing.JPanel();
        subtituloPrecios = new javax.swing.JLabel();
        contenedorEntradasPrecios = new javax.swing.JPanel();
        labelPrecioCompra = new javax.swing.JLabel();
        contenedorInputYErrorPrecioCompra = new javax.swing.JPanel();
        inputPrecioCompra = new javax.swing.JTextField();
        lblErrorInputPrecioCompra = new javax.swing.JLabel();
        labelPrecioVenta = new javax.swing.JLabel();
        contenedorInputYErrorPrecioVenta = new javax.swing.JPanel();
        inputPrecioVenta = new javax.swing.JTextField();
        lblErrorInputPrecioVenta = new javax.swing.JLabel();
        contenedorInventario = new javax.swing.JPanel();
        contenedorTituloInventario = new javax.swing.JPanel();
        subtituloInventario = new javax.swing.JLabel();
        contenedorEntradasInventario = new javax.swing.JPanel();
        labelCantidadDisponible = new javax.swing.JLabel();
        contenedorInputYErrorCantidadDisponible = new javax.swing.JPanel();
        inputCantidadDisponible = new javax.swing.JTextField();
        lblErrorInputCantidadDisponible = new javax.swing.JLabel();
        labelCantidadMinStock = new javax.swing.JLabel();
        contenedorInputYErrorCantidadMinStock = new javax.swing.JPanel();
        inputCantidadMinStock = new javax.swing.JTextField();
        lblErrorInputCantidadMinStock = new javax.swing.JLabel();
        contenedorBotones = new javax.swing.JPanel();
        btnEnviarFormulario = new javax.swing.JButton();
        btnLinkEditarEstadoRegistro = new javax.swing.JButton();
        btnLinkEliminarRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 0));
        setName("dialogoUsuario"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipalScrolleable.setBackground(new java.awt.Color(205, 205, 205));
        panelPrincipalScrolleable.setOpaque(false);

        contenedorFormulario.setBackground(new java.awt.Color(255, 255, 255));
        contenedorFormulario.setLayout(new java.awt.BorderLayout());

        contenedorTituloFormulario.setMinimumSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setOpaque(false);
        contenedorTituloFormulario.setPreferredSize(new java.awt.Dimension(500, 80));
        contenedorTituloFormulario.setLayout(new java.awt.BorderLayout());
        contenedorTituloFormulario.add(margin_left, java.awt.BorderLayout.WEST);

        tituloFormulario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        tituloFormulario.setForeground(new java.awt.Color(17, 35, 85));
        tituloFormulario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setText("Editar Producto");
        tituloFormulario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tituloFormulario.setAlignmentX(0.5F);
        tituloFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        tituloFormulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloFormulario.setVerifyInputWhenFocusTarget(false);
        contenedorTituloFormulario.add(tituloFormulario, java.awt.BorderLayout.CENTER);

        contenedorBtnCerrar.setMinimumSize(new java.awt.Dimension(40, 0));
        contenedorBtnCerrar.setOpaque(false);
        contenedorBtnCerrar.setPreferredSize(new java.awt.Dimension(40, 0));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        contenedorBtnCerrar.setLayout(flowLayout1);

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(17, 35, 85));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jafrinventarios/recursos/iconos/botones/carbon--close-filled.png"))); // NOI18N
        btnCerrar.setToolTipText("");
        btnCerrar.setAlignmentY(0.0F);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusCycleRoot(true);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 26));
        btnCerrar.setPreferredSize(new java.awt.Dimension(30, 26));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDialogo(evt);
            }
        });
        contenedorBtnCerrar.add(btnCerrar);

        contenedorTituloFormulario.add(contenedorBtnCerrar, java.awt.BorderLayout.EAST);

        contenedorFormulario.add(contenedorTituloFormulario, java.awt.BorderLayout.PAGE_START);

        contenedorCuerpoFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 50));
        contenedorCuerpoFormulario.setOpaque(false);
        contenedorCuerpoFormulario.setLayout(new java.awt.GridBagLayout());

        contenedorIdRegistro.setBackground(new java.awt.Color(205, 205, 205));
        contenedorIdRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contenedorIdRegistro.setOpaque(false);
        contenedorIdRegistro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        labelID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        labelID.setText("Id :");
        contenedorIdRegistro.add(labelID);

        lblDatoID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDatoID.setText("001");
        contenedorIdRegistro.add(lblDatoID);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contenedorCuerpoFormulario.add(contenedorIdRegistro, gridBagConstraints);

        contenedorDatosGenerales.setOpaque(false);
        contenedorDatosGenerales.setLayout(new javax.swing.BoxLayout(contenedorDatosGenerales, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloDatosGenerales.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloDatosGenerales.setOpaque(false);
        contenedorTituloDatosGenerales.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloDatosGenerales.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloDatosGenerales.setText("Datos Generales");
        subtituloDatosGenerales.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloDatosGenerales.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloDatosGenerales.add(subtituloDatosGenerales);

        contenedorDatosGenerales.add(contenedorTituloDatosGenerales);

        contenedorEntradasDatosGenerales.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 20, 0, 20));
        contenedorEntradasDatosGenerales.setOpaque(false);
        contenedorEntradasDatosGenerales.setLayout(new java.awt.GridBagLayout());

        labelNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombre.setText("Nombre :");
        labelNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelNombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelNombre.setMaximumSize(new java.awt.Dimension(0, 0));
        labelNombre.setMinimumSize(new java.awt.Dimension(0, 0));
        labelNombre.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasDatosGenerales.add(labelNombre, gridBagConstraints);

        contenedorInputYErrorNombre.setOpaque(false);
        contenedorInputYErrorNombre.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorNombre.setLayout(new java.awt.BorderLayout());

        inputNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputNombre.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputNombre.setName("nombreProducto"); // NOI18N
        inputNombre.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorNombre.add(inputNombre, java.awt.BorderLayout.NORTH);

        lblErrorInputNombre.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputNombre.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputNombre.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorNombre.add(lblErrorInputNombre, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasDatosGenerales.add(contenedorInputYErrorNombre, gridBagConstraints);

        labelProveedor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelProveedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelProveedor.setText("Proveedor :");
        labelProveedor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelProveedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelProveedor.setMaximumSize(new java.awt.Dimension(0, 0));
        labelProveedor.setMinimumSize(new java.awt.Dimension(0, 0));
        labelProveedor.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasDatosGenerales.add(labelProveedor, gridBagConstraints);

        contenedorInputYErrorProveedor.setOpaque(false);
        contenedorInputYErrorProveedor.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorProveedor.setLayout(new java.awt.BorderLayout());

        comboBoxProveedores.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Proveedor" }));
        comboBoxProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxProveedores.setName("proveedor"); // NOI18N
        comboBoxProveedores.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorProveedor.add(comboBoxProveedores, java.awt.BorderLayout.NORTH);

        lblErrorComboBoxProveedores.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorComboBoxProveedores.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorComboBoxProveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorComboBoxProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorComboBoxProveedores.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorProveedor.add(lblErrorComboBoxProveedores, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasDatosGenerales.add(contenedorInputYErrorProveedor, gridBagConstraints);

        contenedorDatosGenerales.add(contenedorEntradasDatosGenerales);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contenedorCuerpoFormulario.add(contenedorDatosGenerales, gridBagConstraints);

        contenedorPrecios.setOpaque(false);
        contenedorPrecios.setLayout(new javax.swing.BoxLayout(contenedorPrecios, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloPrecios.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloPrecios.setOpaque(false);
        contenedorTituloPrecios.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloPrecios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloPrecios.setText("Precios");
        subtituloPrecios.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloPrecios.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloPrecios.add(subtituloPrecios);

        contenedorPrecios.add(contenedorTituloPrecios);

        contenedorEntradasPrecios.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 0, 20));
        contenedorEntradasPrecios.setOpaque(false);
        contenedorEntradasPrecios.setLayout(new java.awt.GridBagLayout());

        labelPrecioCompra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelPrecioCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPrecioCompra.setText("Precio de compra :");
        labelPrecioCompra.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelPrecioCompra.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelPrecioCompra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelPrecioCompra.setMaximumSize(new java.awt.Dimension(0, 0));
        labelPrecioCompra.setMinimumSize(new java.awt.Dimension(0, 0));
        labelPrecioCompra.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasPrecios.add(labelPrecioCompra, gridBagConstraints);

        contenedorInputYErrorPrecioCompra.setOpaque(false);
        contenedorInputYErrorPrecioCompra.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorPrecioCompra.setLayout(new java.awt.BorderLayout());

        inputPrecioCompra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputPrecioCompra.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputPrecioCompra.setName("precioCompra"); // NOI18N
        inputPrecioCompra.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorPrecioCompra.add(inputPrecioCompra, java.awt.BorderLayout.NORTH);

        lblErrorInputPrecioCompra.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputPrecioCompra.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputPrecioCompra.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputPrecioCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputPrecioCompra.setPreferredSize(new java.awt.Dimension(0, 17));
        lblErrorInputPrecioCompra.setRequestFocusEnabled(false);
        contenedorInputYErrorPrecioCompra.add(lblErrorInputPrecioCompra, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasPrecios.add(contenedorInputYErrorPrecioCompra, gridBagConstraints);

        labelPrecioVenta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelPrecioVenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPrecioVenta.setText("Precio de venta :");
        labelPrecioVenta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelPrecioVenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelPrecioVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelPrecioVenta.setMaximumSize(new java.awt.Dimension(0, 0));
        labelPrecioVenta.setMinimumSize(new java.awt.Dimension(0, 0));
        labelPrecioVenta.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasPrecios.add(labelPrecioVenta, gridBagConstraints);

        contenedorInputYErrorPrecioVenta.setOpaque(false);
        contenedorInputYErrorPrecioVenta.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorPrecioVenta.setLayout(new java.awt.BorderLayout());

        inputPrecioVenta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputPrecioVenta.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputPrecioVenta.setName("precioVenta"); // NOI18N
        inputPrecioVenta.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorPrecioVenta.add(inputPrecioVenta, java.awt.BorderLayout.NORTH);

        lblErrorInputPrecioVenta.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputPrecioVenta.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputPrecioVenta.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputPrecioVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputPrecioVenta.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorPrecioVenta.add(lblErrorInputPrecioVenta, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasPrecios.add(contenedorInputYErrorPrecioVenta, gridBagConstraints);

        contenedorPrecios.add(contenedorEntradasPrecios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contenedorCuerpoFormulario.add(contenedorPrecios, gridBagConstraints);

        contenedorInventario.setOpaque(false);
        contenedorInventario.setLayout(new javax.swing.BoxLayout(contenedorInventario, javax.swing.BoxLayout.Y_AXIS));

        contenedorTituloInventario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(5, 10, -5, 0)));
        contenedorTituloInventario.setOpaque(false);
        contenedorTituloInventario.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        subtituloInventario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        subtituloInventario.setText("Inventario");
        subtituloInventario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        subtituloInventario.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        contenedorTituloInventario.add(subtituloInventario);

        contenedorInventario.add(contenedorTituloInventario);

        contenedorEntradasInventario.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 20, 0, 20));
        contenedorEntradasInventario.setOpaque(false);
        contenedorEntradasInventario.setLayout(new java.awt.GridBagLayout());

        labelCantidadDisponible.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCantidadDisponible.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCantidadDisponible.setText("Cantidad disponible :");
        labelCantidadDisponible.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelCantidadDisponible.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelCantidadDisponible.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelCantidadDisponible.setMaximumSize(new java.awt.Dimension(0, 0));
        labelCantidadDisponible.setMinimumSize(new java.awt.Dimension(0, 0));
        labelCantidadDisponible.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        contenedorEntradasInventario.add(labelCantidadDisponible, gridBagConstraints);

        contenedorInputYErrorCantidadDisponible.setOpaque(false);
        contenedorInputYErrorCantidadDisponible.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorCantidadDisponible.setLayout(new java.awt.BorderLayout());

        inputCantidadDisponible.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputCantidadDisponible.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputCantidadDisponible.setName("cantidadMinimaStock"); // NOI18N
        inputCantidadDisponible.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorCantidadDisponible.add(inputCantidadDisponible, java.awt.BorderLayout.NORTH);

        lblErrorInputCantidadDisponible.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputCantidadDisponible.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputCantidadDisponible.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputCantidadDisponible.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputCantidadDisponible.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorCantidadDisponible.add(lblErrorInputCantidadDisponible, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasInventario.add(contenedorInputYErrorCantidadDisponible, gridBagConstraints);

        labelCantidadMinStock.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCantidadMinStock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCantidadMinStock.setText("Cantidad min stock :");
        labelCantidadMinStock.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelCantidadMinStock.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        labelCantidadMinStock.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelCantidadMinStock.setMaximumSize(new java.awt.Dimension(0, 0));
        labelCantidadMinStock.setMinimumSize(new java.awt.Dimension(0, 0));
        labelCantidadMinStock.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        contenedorEntradasInventario.add(labelCantidadMinStock, gridBagConstraints);

        contenedorInputYErrorCantidadMinStock.setOpaque(false);
        contenedorInputYErrorCantidadMinStock.setPreferredSize(new java.awt.Dimension(0, 52));
        contenedorInputYErrorCantidadMinStock.setLayout(new java.awt.BorderLayout());

        inputCantidadMinStock.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        inputCantidadMinStock.setMargin(new java.awt.Insets(4, 10, 4, 10));
        inputCantidadMinStock.setName("cantidadDisponible"); // NOI18N
        inputCantidadMinStock.setPreferredSize(new java.awt.Dimension(0, 34));
        contenedorInputYErrorCantidadMinStock.add(inputCantidadMinStock, java.awt.BorderLayout.NORTH);

        lblErrorInputCantidadMinStock.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblErrorInputCantidadMinStock.setForeground(new java.awt.Color(179, 38, 30));
        lblErrorInputCantidadMinStock.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 0));
        lblErrorInputCantidadMinStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblErrorInputCantidadMinStock.setPreferredSize(new java.awt.Dimension(0, 17));
        contenedorInputYErrorCantidadMinStock.add(lblErrorInputCantidadMinStock, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        contenedorEntradasInventario.add(contenedorInputYErrorCantidadMinStock, gridBagConstraints);

        contenedorInventario.add(contenedorEntradasInventario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contenedorCuerpoFormulario.add(contenedorInventario, gridBagConstraints);

        contenedorFormulario.add(contenedorCuerpoFormulario, java.awt.BorderLayout.CENTER);

        contenedorBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 10, 40));
        contenedorBotones.setOpaque(false);
        contenedorBotones.setPreferredSize(new java.awt.Dimension(500, 130));
        contenedorBotones.setLayout(new java.awt.GridBagLayout());

        btnEnviarFormulario.setBackground(new java.awt.Color(30, 166, 177));
        btnEnviarFormulario.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEnviarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarFormulario.setText("Actualizar");
        btnEnviarFormulario.setToolTipText("");
        btnEnviarFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarFormulario.setMargin(new java.awt.Insets(6, 12, 6, 12));
        btnEnviarFormulario.setMaximumSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setMinimumSize(new java.awt.Dimension(200, 40));
        btnEnviarFormulario.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotones.add(btnEnviarFormulario, gridBagConstraints);

        btnLinkEditarEstadoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnLinkEditarEstadoRegistro.setForeground(new java.awt.Color(200, 0, 0));
        btnLinkEditarEstadoRegistro.setText("Deshabilitar Producto");
        btnLinkEditarEstadoRegistro.setAlignmentX(0.5F);
        btnLinkEditarEstadoRegistro.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotones.add(btnLinkEditarEstadoRegistro, gridBagConstraints);

        btnLinkEliminarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnLinkEliminarRegistro.setForeground(new java.awt.Color(200, 0, 0));
        btnLinkEliminarRegistro.setText("Eliminar Producto");
        btnLinkEliminarRegistro.setAlignmentX(0.5F);
        btnLinkEliminarRegistro.setIconTextGap(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        contenedorBotones.add(btnLinkEliminarRegistro, gridBagConstraints);

        contenedorFormulario.add(contenedorBotones, java.awt.BorderLayout.PAGE_END);

        panelPrincipalScrolleable.setViewportView(contenedorFormulario);

        getContentPane().add(panelPrincipalScrolleable);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarDialogo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarDialogo
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarDialogo

    
    
    /*
    ============================================================================
                      MÉTODOS PÚBLICOS PARA EL CONTROLADOR
    ============================================================================
    */

    
    public void setId( Integer id ){
        lblDatoID.setText( Integer.toString(id) );
    }
    
    public void mostrarBtnLinkEliminarProducto(){
        btnLinkEliminarRegistro.setVisible(true);
        DinamismoLink.aplicarEfecto(btnLinkEliminarRegistro);
    }
    
    public void mostrarBtnEditarEstadoProducto(){
        btnLinkEditarEstadoRegistro.setVisible(true);
        DinamismoLink.aplicarEfecto(btnLinkEditarEstadoRegistro);
    }
    
    public void asignarIntencionBtnEditarEstadoProducto(boolean habilitado){
        
        if(habilitado){
            //Si esta habilitado el producto, se muestra el boton para demostrar
            //la intencion de poder deshabilitarlo
            btnLinkEditarEstadoRegistro.setForeground(new java.awt.Color(200, 0, 0));
            btnLinkEditarEstadoRegistro.setText("Deshabilitar Producto");
        }else{
            btnLinkEditarEstadoRegistro.setForeground(new java.awt.Color(17, 35, 85));
            btnLinkEditarEstadoRegistro.setText("Habilitar Producto");
        }
        btnLinkEditarEstadoRegistro.repaint();
        
    }
    
    //Exponer inicializar el combo box esperando la lista de proveedores a asignar
    public void inicializarComboBoxProveedores ( LinkedHashMap<Integer, String> diccionarioProveedores ) {
        
        formularioDatosProducto.agregarCampoComboBox(comboBoxProveedores,
                                                "Proveedor",
                                                diccionarioProveedores, 
                                                lblErrorComboBoxProveedores, 
                                                true);
        
    }
    
    
    //Exponer botones
    public JButton getBtnEnviarFormulario(){
        return btnEnviarFormulario;
    }
    
    public JButton getBtnLinkEditarEstadoProducto(){
        return btnLinkEditarEstadoRegistro;
    }
    
    public JButton getBtnLinkEliminarProducto(){
        return btnLinkEliminarRegistro;
    }
    
    
    //Exponer metodos para gestionar el formulario
    public boolean validarFormulario(){
        return formularioDatosProducto.validar();
    }
    
    public HashMap<String, String> recolectarDatosFormulario(){
        return formularioDatosProducto.recolectarDatos();
    }
    
    public void mostrarErroresValidacionCampos( HashMap<String, String> errores ){
        formularioDatosProducto.mostrarErroresExternos(errores);
    }
    
    public void asignarDatosEnFormulario( HashMap<String, String> datos ){
        formularioDatosProducto.asignarDatos(datos);
    }
    
    
    /* 
        Metodos para dialogos de mensajes de Alertas
    */
    public void mostrarAlertaErrorFormatoCampos(){
        DialogoAlerta.mostrarErrorFormatoCampos( this );
    }
      
    public void mostrarAlertaExitosa(String mensajeExitoso ){
        
        DialogoAlerta.mostrarExito(
                    this, 
                    "Operacion Exitosa", 
                    mensajeExitoso
            );
        
    }
    
    public boolean mostrarAlertaAdvertencia( String mensaje ){
        
       return DialogoAlerta.mostrarAdvertenciaConRespuesta(
                   this,
                   "Advertencia", 
                   mensaje
                );
    
    }
    
    public void mostrarAlertaError( String mensaje ){
        DialogoAlerta.mostrarError( this, "Error", mensaje );
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviarFormulario;
    private javax.swing.JButton btnLinkEditarEstadoRegistro;
    private javax.swing.JButton btnLinkEliminarRegistro;
    private javax.swing.JComboBox<String> comboBoxProveedores;
    private javax.swing.JPanel contenedorBotones;
    private javax.swing.JPanel contenedorBtnCerrar;
    private javax.swing.JPanel contenedorCuerpoFormulario;
    private javax.swing.JPanel contenedorDatosGenerales;
    private javax.swing.JPanel contenedorEntradasDatosGenerales;
    private javax.swing.JPanel contenedorEntradasInventario;
    private javax.swing.JPanel contenedorEntradasPrecios;
    private javax.swing.JPanel contenedorFormulario;
    private javax.swing.JPanel contenedorIdRegistro;
    private javax.swing.JPanel contenedorInputYErrorCantidadDisponible;
    private javax.swing.JPanel contenedorInputYErrorCantidadMinStock;
    private javax.swing.JPanel contenedorInputYErrorNombre;
    private javax.swing.JPanel contenedorInputYErrorPrecioCompra;
    private javax.swing.JPanel contenedorInputYErrorPrecioVenta;
    private javax.swing.JPanel contenedorInputYErrorProveedor;
    private javax.swing.JPanel contenedorInventario;
    private javax.swing.JPanel contenedorPrecios;
    private javax.swing.JPanel contenedorTituloDatosGenerales;
    private javax.swing.JPanel contenedorTituloFormulario;
    private javax.swing.JPanel contenedorTituloInventario;
    private javax.swing.JPanel contenedorTituloPrecios;
    private javax.swing.JTextField inputCantidadDisponible;
    private javax.swing.JTextField inputCantidadMinStock;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputPrecioCompra;
    private javax.swing.JTextField inputPrecioVenta;
    private javax.swing.JLabel labelCantidadDisponible;
    private javax.swing.JLabel labelCantidadMinStock;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrecioCompra;
    private javax.swing.JLabel labelPrecioVenta;
    private javax.swing.JLabel labelProveedor;
    private javax.swing.JLabel lblDatoID;
    private javax.swing.JLabel lblErrorComboBoxProveedores;
    private javax.swing.JLabel lblErrorInputCantidadDisponible;
    private javax.swing.JLabel lblErrorInputCantidadMinStock;
    private javax.swing.JLabel lblErrorInputNombre;
    private javax.swing.JLabel lblErrorInputPrecioCompra;
    private javax.swing.JLabel lblErrorInputPrecioVenta;
    private javax.swing.Box.Filler margin_left;
    private javax.swing.JScrollPane panelPrincipalScrolleable;
    private javax.swing.JLabel subtituloDatosGenerales;
    private javax.swing.JLabel subtituloInventario;
    private javax.swing.JLabel subtituloPrecios;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
